### ISSUE TITLE
Allow Installation of Dexter Industries Raspbian for Robots

### ISSUE THREAD

**Issue by CleoQc** [raspberrypi/rpi-imager#11]
Dexter Industries, now Modular Robotics, has been around for years, and is a reliable partner.

Raspbian for Robots is a variation on Raspbian that supports the Dexter robots. 
The images are on SourceForge for now, but we're open to moving them elsewhere 
https://sourceforge.net/projects/dexterindustriesraspbianflavor/

Thanks

**Comment by tdewey-rpi** [comment]
Please fill out the OS addition request form at https://forms.gle/35ESMTmyST4kHAdT7
