### ISSUE TITLE
*Suggestion*   [Feature Request] Have an option to choose which raspberry pi's that you have

### ISSUE THREAD

**Issue by jack60612** [raspberrypi/rpi-imager#110]
You would only be shown images for raspberry pi's that you selected
so only images that are compatible with the one that you selected

**Comment by lurch** [comment]
AFAIK, one of the driving factors for RPi-Imager was to make it as easy to use as possible. And it sounds like this suggestion would only make it more complex? :confused: 

[NOOBS](https://github.com/raspberrypi/noobs) and [PINN](https://github.com/procount/pinn) automatically know what Pi they're being run on, so they **do** do the filtering you're asking for.

**Comment by jack60612** [comment]
like an advanced option or something

**Comment by mobluse** [comment]
Some Pis e.g. Pi Zero, Pi 1 A, Pi 4 B can be connected to the computer that runs Imager and thus be automatically identified and also used as an SD card writer/reader.

**Comment by maxnet** [comment]
>Some Pis e.g. Pi Zero, Pi 1 A, Pi 4 B can be 
>connected to the computer that runs Imager and
> thus be automatically identified and also used 
>as an SD card writer/reader.

Correct me if I am wrong.
But I don't think Pi 4 is supported by rpiboot, since on CM4 it requires setting a jumper to disable bootrom and get it to work.

And not sure if the target audience of the models that do support usb boot need help with figuring out which Image is supported by their board.

**Comment by cillian64** [comment]
This is implemented by #645 which will be included in the 1.8.0 release coming shortly
