### ISSUE TITLE
Please add Fedora iot image to the list of available images

### ISSUE THREAD

**Issue by gitsop01** [raspberrypi/rpi-imager#114]
Although just started as a separate image for Fedora will eventually support a large range of Iot products including Raspberry Pi.
Send any updates directly to Fedora iot developers for inclusion in the image

**Comment by ghollingworth** [comment]
Are you the maintainer of the image?

**Comment by gitsop01** [comment]
No I am not the maintainer, just contact the maintainers from the Fedora Iot official page. already have some support for RPI already but it just been started,

**Comment by ghollingworth** [comment]
It would be better to wait until they contact us
