### ISSUE TITLE
Add ssh and WiFi settings for Raspbian

### ISSUE THREAD

**Issue by YarmoM** [raspberrypi/rpi-imager#12]
For the official raspbian images, it would be a helpful feature and a time saver to add two buttons that perform post-writing operations: one adds an empty ssh file and the other prompts WiFi credentials and writes a corresponding wpa_supplicant.conf file.

**Comment by ghollingworth** [comment]
Problem here is, when you finish writing to the SD card you finalize the card (writing the MBR and partition headers) then eject it.

To have this functionality the user would have to remove it and then re-insert the card before they could continue.

If you don't eject / un-mount it, then (on operating systems which don't flush out mass storage devices), it's possible people could remove the SD card when they see the final screen thinking it's OK to remove the device.

So it makes it more difficult to use for a first time beginner...

Also this would only work with Raspbian (although I'm sure there are other random OSes which support the idea of putting the ssh file into the root partition) which again would be inconsistent.

Finally there is software that already does this, it's PiBakery, I'd suggest you use that.

**Comment by YarmoM** [comment]
Thanks for the suggestion. I understand the technical implications and inconsistencies are reasons enough to dismiss this.

However, I do not agree on the "first time beginner" argument. Now, I don't know if many first time beginners make headless setups, but this software supports the no-desktop image. One could argue a first time beginner would even be more lost if they decided to try this out and WiFi wasn't working because they haven't learned about wpa_supplicant yet.

My 2 cents. Thanks for releasing a great simple tool for all!

**Comment by probonopd** [comment]
> Finally there is software that already does this, it's PiBakery, I'd suggest you use that.

How does that software achieve this feat, then? Could we do the same here?

**Comment by alexadam16** [comment]
Would be great to have a feature like this. I think ejecting and reinserting the card is not a big problem.
