### ISSUE TITLE
When running windows version on windows 10, RPI imager crashes out

### ISSUE THREAD

**Issue by paulmac57** [raspberrypi/rpi-imager#126]
Log Name:      Application
Source:        Application Error
Date:          25/11/2020 11:25:07
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Zeuss
Description:
Faulting application name: rpi-imager.exe, version: 1.4.0.0, time stamp: 0x00000000
Faulting module name: BfLLR.dll, version: 6.0.0.23, time stamp: 0x4df4f68b
Exception code: 0xc0000409
Fault offset: 0x0000bc9b
Faulting process ID: 0x1e54
Faulting application start time: 0x01d6c31da02012d0
Faulting application path: C:\Program Files (x86)\Raspberry Pi Imager\rpi-imager.exe
Faulting module path: C:\WINDOWS\system32\BfLLR.dll
Report ID: 50803169-355a-43fa-b7bb-33b6e6bae49e
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-11-25T11:25:07.5185167Z" />
    <EventRecordID>24254</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Zeuss</Computer>
    <Security />
  </System>
  <EventData>
    <Data>rpi-imager.exe</Data>
    <Data>1.4.0.0</Data>
    <Data>00000000</Data>
    <Data>BfLLR.dll</Data>
    <Data>6.0.0.23</Data>
    <Data>4df4f68b</Data>
    <Data>c0000409</Data>
    <Data>0000bc9b</Data>
    <Data>1e54</Data>
    <Data>01d6c31da02012d0</Data>
    <Data>C:\Program Files (x86)\Raspberry Pi Imager\rpi-imager.exe</Data>
    <Data>C:\WINDOWS\system32\BfLLR.dll</Data>
    <Data>50803169-355a-43fa-b7bb-33b6e6bae49e</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by maxnet** [comment]
>Faulting module name: BfLLR.dll, version: 6.0.0.23, time stamp: 0x4df4f68b

You have the "Killer control center" software that allows you to control download/upload speed by application installed?
If it is something you can disable, you may want to try if it works better without that.
