### ISSUE TITLE
Fuzzy text on macOS Retina Displays

### ISSUE THREAD

**Issue by oznu** [raspberrypi/rpi-imager#13]
On macOS using a Retina display (5k) the text is fuzzy. It looks fine on non-retina displays.

I'm not sure how well this will be replicated in a screenshot, but here it is:

<img width="723" alt="fuzzy-text" src="https://user-images.githubusercontent.com/3979615/76039451-95272c80-5fa0-11ea-8fec-7a94571a8b5e.png">

**Comment by tvoverbeek** [comment]
On my MacBook Pro (Retina mid 2012) under Catalina (10.15.3) text looks fine (as in your screenshot).
