### ISSUE TITLE
Unable to open dmg image on mac

### ISSUE THREAD

**Issue by lidderupk** [raspberrypi/rpi-imager#138]
Downloaded imager-1.5.dmg on Mac version 10.15.6. I get an error `No mountable file systems". 

![image](https://user-images.githubusercontent.com/3187457/103106311-355e4880-45e9-11eb-86a9-8a259f853bb6.png)

**Comment by maxnet** [comment]
Tried downloading it a second time?

**Comment by lidderupk** [comment]
I did try a bunch of times. From raspberry site. and from github. Did it work for you? I am going to restart my mac. Saw that as one of the answers. Thank you.

**Comment by maxnet** [comment]
>Did it work for you?

Yes, the .dmg opens fine for me.

Also may want to double-check the shasum to make sure there is nothing wrong with download.
(The mirror I got my file from, may be a different one than yours).

![Screenshot 2020-12-24 at 23 30 57](https://user-images.githubusercontent.com/1123701/103107642-936a4a80-4640-11eb-9e3b-70f34d8b81f1.png)

**Comment by maxnet** [comment]
BTW you do can successfully open .dmg files from other vendors?

And don't have anything special installed that installs kernel drivers that can affect file system operations such as USB drive encryption software and non-Apple filesystem drivers?

**Comment by lidderupk** [comment]
Restarting worked. Not sure what was going on. Thank you for your help.

**Comment by maxnet** [comment]
Good to hear it is solved.
