### ISSUE TITLE
Feature request: minor change to installer prompt

### ISSUE THREAD

**Issue by kubycsolutions** [raspberrypi/rpi-imager#145]
As expected, the Raspberry Pi Imager is perfectly happy to install to anything mounted as a USB drive -- including thumb drives and USB hard drives. This makes creating (or re-creating) a system that bypasses the SD card significantly easier, so it may be worth documenting by changing the on-screen prompt from "SD card" to something like "SD card or USB drive".

**Comment by CharlesGodwin** [comment]
The latest version (v1.6) says "Choose Storage"
