### ISSUE TITLE
Unable to use custom image on Fedora 33

### ISSUE THREAD

**Issue by ethanholz** [raspberrypi/rpi-imager#159]
I attempted to write a custom .img file and when I selected it with Nautilus, I am returned to the menu to select an image but the custom image is not selected nor is there any error in the command line.

**Comment by maxnet** [comment]
You did compile rpi-imager from source?
(As opposed to using any sandboxed environment like snaps)

**Comment by ethanholz** [comment]
@maxnet that is correct, compiled from the repo. If I call the imager  from the command line and pass it the .img file, that allows for me to flash an SD card with the image; I just can't from the GUI directly n

**Comment by maxnet** [comment]
Can you try compiling from latest git again, and see if it works better now?


Think the code we had to workaround monitors with broken EDID caused problems on Fedora.
Reverted it.

**Comment by ethanholz** [comment]
Yup, that worked! Thank you for taking a look at this!

**Comment by maxnet** [comment]
Good to hear it works now.
