### ISSUE TITLE
[OS Request] OctoPi

### ISSUE THREAD

**Issue by guysoft** [raspberrypi/rpi-imager#162]
Hey,
I am the maintainer of OctoPi, and a few other distros since I am also the creator of CustomPiOS. So this is the first attempt our of expected several.
I got a request to add OctoPi to rpi-imager on my issue tracker https://github.com/guysoft/OctoPi/issues/726

I can't see any docs on how to add an image. So I am copying more or less what I saw in #83

Note that it should go in the ``Other spesific purpose OS`` section.
```json
{
    "os_list": [
        {
            "name": "OctoPi",
            "description": "A Raspberry Pi distribution for 3d printers. Ships OctoPrint out-of-the-box.",
            "icon": "https://raw.githubusercontent.com/guysoft/OctoPi/devel/media/rpi-imager-OctoPi.png",
            "subitems_url": "http://unofficialpi.org/rpi-imager/rpi-imager-octopi.json"
        }
    ]
}
```

And the json file is in place:
http://unofficialpi.org/rpi-imager/rpi-imager-octopi.json

Note: We are expecting next release to also include a 64bit builds which is already in the nightly. If there is a section to add in advance it might also be helpful

**Comment by ghollingworth** [comment]
The icon needs to be 40x40 and the text needs to be limited to fit into the box.  You can test it with rpi-imager by copying a local version of the global os_list_imagingutility.json and running it with the --repo command-line option:

C:\Program Files (x86)\Raspberry Pi Imager>rpi-imager.exe --repo os_list_imagingutility.json

![image](https://user-images.githubusercontent.com/2048540/110768303-056d2b80-824f-11eb-9890-4f41e566b128.png)

**Comment by guysoft** [comment]
Fixed json in the original request.

Here is how it looks.

Also I warmly recommend adding this to the README file in the repo, or to the wiki page on this githubl, otherwise I expect you will be repeating yourself.

![Screenshot_20210311_121202](https://user-images.githubusercontent.com/325670/110771394-1e7fd780-8263-11eb-9e1d-794065f84ee3.png)

![Screenshot_20210311_121346](https://user-images.githubusercontent.com/325670/110771520-41aa8700-8263-11eb-9f15-bed9f711847b.png)

**Comment by ghollingworth** [comment]
Does the one image support all Raspberry Pi devices?  In which case I'll probably add it without the submenu

**Comment by guysoft** [comment]
All Raspberry Pi devices are supported.

**Comment by ghollingworth** [comment]
Ok, approved for adding, should appear sometime today...

**Comment by guysoft** [comment]
Looks like its there now, thanks!

I hope to automate the json stuff here now and also post other CustomPiOS popular distos.

![Screenshot_20210311_173308](https://user-images.githubusercontent.com/325670/110812128-0a060400-8290-11eb-9643-e0a4d3cb70da.png)

**Comment by guysoft** [comment]
@ghollingworth Hey, sorry to bug again, but @foosel has pointed out to me that the url should be HTTPS and not HTTP in order to avoid man-in-the-middle attacks.

So it should be:

```
{
    "os_list": [
        {
            "name": "OctoPi",
            "description": "A Raspberry Pi distribution for 3d printers. Ships OctoPrint out-of-the-box.",
            "icon": "https://raw.githubusercontent.com/guysoft/OctoPi/devel/media/rpi-imager-OctoPi.png",
            "subitems_url": "https://unofficialpi.org/rpi-imager/rpi-imager-octopi.json"
        }
    ]
}```

**Comment by XECDesign** [comment]
Should be using HTTPS now.

**Comment by guysoft** [comment]
Works, closing
