### ISSUE TITLE
New version 1.6 - Update translation

### ISSUE THREAD

**Issue by bovirus** [raspberrypi/rpi-imager#166]
In the new version 1.6 there are several new strings in language files.

I already make a PR for Italian language

@YuzukiTsuru - Chinese
@kosssi - French
@AaronDewes - German
@jose1711 - Slovak
@Zaryob - Turkish

Could you please update your language translation?

Thanks.

**Comment by cillian64** [comment]
Closing this as 1.6 was rather a while ago now
