### ISSUE TITLE
Raspberry pi logo doesn't have to be that big. Make it work and fit fine on lower resolutions

### ISSUE THREAD

**Issue by mgrouch** [raspberrypi/rpi-imager#175]
Raspberry pi logo doesn't have to be that big. Make it work and fit fine on lower resolutions. With resolution 800x480 takes too much screen 
space and header goes under desktop toolbar. There are only few buttons and a logo. It should be made usable  even with smaller screen
resolutions.

**Comment by maxnet** [comment]
You may have better luck running Imager fullscreen under console, instead of under X.

```
sudo raspi-config -> system options -> boot -> console autologin
*reboot*
sudo QT_QPA_PLATFORM=eglfs QT_QPA_EGLFS_ALWAYS_SET_MODE=1 rpi-imager
```

**Comment by mgrouch** [comment]
Will console version work with touchscreen?

**Comment by mgrouch** [comment]
So it’s not an option

**Comment by lurch** [comment]
But I guess you'd need to have a USB keyboard plugged in anyway in order to type the `sudo QT_QPA_PLATFORM=eglfs QT_QPA_EGLFS_ALWAYS_SET_MODE=1 rpi-imager` command? :confused:

**Comment by mgrouch** [comment]
Correct.

**Comment by lurch** [comment]
Perhaps I'm missing something obvious, but why is it so important for (the advanced options of) RPi Imager to work on a touchscreen without plugging in a USB keyboard? Isn't RPi Imager something that you're likely to run fairly infrequently? :shrug: 

P.S. Please take my comments with a grain of salt, I don't work on RPi Imager myself; I'm just curious.

**Comment by cillian64** [comment]
The logo is made smaller in 1.8.0, but on crazy-low-resolution displays the GUI is never going to work very well.
