### ISSUE TITLE
Automatically set up wifi

### ISSUE THREAD

**Issue by Timmmm** [raspberrypi/rpi-imager#178]
It's a recurring annoyance when setting up a Raspberry Pi without a screen (which I'd guess is the most common use) that you have to:

1. Unplug and plug the SD card in, so that Windows mounts it. Ignore the message to format the drive!
2. Find the drive called boot.
3. Create a new file called `wpa_supplicant.conf`. Make sure you spell `supplicant` right! Common word that beginners will probably know.
4. Oh by the way make sure you have file extensions shown so you don't get `wpa_supplicant.conf.txt`.
5. Right now you can edit the file, but not in Notepad or Wordpad. You have to download Nodepad++.
6. Make sure you are in LF mode not CRLF.
7. Ok now google the `wpa_supplicant.conf` format. Very easy. Beginners probably love this. Probably don't bother setting the country properly since that involves looking up your country code in some list somewhere.
8. Ok paste it in and save it at last!

Not exactly beginner friendly! It's pretty annoying even for pros. So much so that somebody has made a [website to generate the file for you](https://steveedson.co.uk/tools/wpa/).

Since you now have this fairly slick imager, it would be great if it just asked you for wifi credentials up front. It could even get them from the current machine.

**Comment by ghollingworth** [comment]
Maybe you should try pressing Ctrl-Alt-X

https://www.raspberrypi.org/blog/raspberry-pi-imager-update-to-v1-6/
