### ISSUE TITLE
Error while writing firstrun.sh while ubuntu 20.10 64bit writing to SD card

### ISSUE THREAD

**Issue by AlexanderGreckov** [raspberrypi/rpi-imager#181]
When i'm trying to configure and write new ubuntu 20.10 64bit on my SD card with the new confuguration menu i'm getting the `Writing failed firstrun.sh on FAT partition`

**Comment by maxnet** [comment]
If you are running Windows 10, the error you are getting is probably related to https://github.com/raspberrypi/rpi-imager/issues/171

Also be aware that only RPI OS can be customized. Not Ubuntu.

**Comment by AlexanderGreckov** [comment]
Understood. Thanks for your reply!
