### ISSUE TITLE
[Feature Request] Inform the user that settings have been successfully saved in Advanced Settings

### ISSUE THREAD

**Issue by cl-ement05** [raspberrypi/rpi-imager#184]
In advanced settings, when you save the enabled customizations, nothing happens except for the button which turns a little darker. But this is not a way of saying "settings saved". So it would be great if you could make a toast notification which disappears after some seconds just to inform the user settings have been saved

**Comment by cl-ement05** [comment]
> 
> 
> For me (on Linux), when I click the "SAVE" button the options window disappears (which is kinda what I'd expect).

Well this is not happening for me when I change some settings. I am creating an issue

**Comment by lurch** [comment]
Ahh, I guess this can be closed in light of #188 ?

**Comment by cl-ement05** [comment]
Yeah of course sorry
