### ISSUE TITLE
Delete after download

### ISSUE THREAD

**Issue by m42e** [raspberrypi/rpi-imager#186]
I had the issue that the imager tried to download the image, which did not happen beacause it seems some proxy settings were not respected (MacOS). 
But before downloading it already started to delete the partitions on the SD card.

At least it should check if the download is possible before deleting the SDCard content.

**Comment by maxnet** [comment]
That do is a rare corner case.
Keep in mind that in the typical case of there not being Internet connectivity, Imager would not be able to download the list of OS images that can be downloaded either, so you would not be able to select an OS to download.

**Comment by lurch** [comment]
If you're about to overwrite the contents of the SD card anyway (_if_ the download would have worked), what's the use-case for **not** deleting the SDCard content?

**Comment by m42e** [comment]
Might be just a kind of user friendly behaviour. if it doesn't work, do not touch it at all.
