### ISSUE TITLE
Advanced Settings pop-up not disappearing if you change some settings (Windows)

### ISSUE THREAD

**Issue by cl-ement05** [raspberrypi/rpi-imager#188]
I tried to change settings multiples times and I also tried to restart the app but the bug is still here. 

***Steps to reproduce :***
Just open the advanced settings, enable some settings (I enabled SSH, wifi and changed keyboard layout)

***Issue it self :***
You should notice that when clicking on the "save" button, the pop-up does not disappear and settings are not saved

**Comment by lurch** [comment]
@maxnet Maybe it'd be worth showing a red asterisk or something to indicate that there's some fields that are still missing required info, like you get on websites if you enter your credit card number but forget to enter the expiry date? :wink:

**Comment by cl-ement05** [comment]
> 
> 
> @maxnet Maybe it'd be worth showing a red asterisk or something to indicate that there's some fields that are still missing required info, like you get on websites if you enter your credit card number but forget to enter the expiry date? 😉

Well yes since this is what just happened to me lol

**Comment by reukiodo** [comment]
Related: #318

**Comment by reukiodo** [comment]
A workaround is outlined in [a forum post](https://forums.raspberrypi.com/viewtopic.php?p=2048006#p2048006):

Use RPi imager to write the SD with special options and 'password' as the password.
From the FAT32 boot drive, open the firstrun.sh in Notepad.
Find the section with cat >/etc/wpa_supplicant/wpa_supplicant.conf <<'WPAEOF'
Replace the line from psk=...gibberish... to key_mgmt=NONE
Save, close, and eject the SD card.
Put into your RPi and it after a long boot, should be on your open WiFi network!
