### ISSUE TITLE
Suggestion/Feature Request: Add a logfile showing both successful and failed writes

### ISSUE THREAD

**Issue by raspberrypieman** [raspberrypi/rpi-imager#190]
I would like to see a logfile which is appended to each time the imager is used, like the one I maintain, using HDDRawCopy.
It could be stored in the existing folder: C:\Users\Username\AppData\Local\Raspberry Pi\Imager
It need only be a simple CSV file, with one line per operation, ideally with these fields:
1. Date + Time, ideally: yyyy/mm/dd_hh:mm:ss
2. Name of file being read from, example: 2021-01-11-raspios-buster-armhf-full.zip
3. Device being written to, example: Generic Mass-Storage(I:) <- This is what HDDRawCopy reports on my system
4. How many sectors written, example: 675840
5. Time taken, ideally mm:ss, example: 06:12
6. Result, example: Success or Failure Message
The sectors / time gives a write speed - useful in determining the best SDCard brand to use
I additionally note the DOS VSN of the boot partition, which helps me uniquely identify the card, using DIR without having to boot it.

**Comment by tdewey-rpi** [comment]
An interesting idea, but not one I intend to implement.

Essentially, your proposal sounds more like a feature that would be useful for a commercial enterprise than a new home user - and I'd expect such features to covered by adjacent projects.

rpi-imager is unashamedly aimed at less experienced users.
