### ISSUE TITLE
Full Disk Encryption Support

### ISSUE THREAD

**Issue by kevATin** [raspberrypi/rpi-imager#207]
Do you plan on adding support for full disk encryption?
It seems like a pain to get it set up manually on the RPi.

**Comment by maxnet** [comment]
No.
Imager only writes full disk images and does not know anything about encrypting individual partitions.

(Other tools like Berryboot do are able to handle that, as they do deal with partitions).

**Comment by acmpo6ou** [comment]
But berryboot is not maintained anymore. I'm trying to install Ubuntu Server with disk encryption, and it's not possible. I tried all options here, and nothing worked: https://askubuntu.com/questions/1287837/luks-disk-encryption-on-raspberry-pi-4-and-ubuntu-desktop-20-10/1296450#1296450
