### ISSUE TITLE
It is crashed when open respberry pi imager on my macbook

### ISSUE THREAD

**Issue by buddhist182** [raspberrypi/rpi-imager#208]
My macos version: 10.15.7

It is crashed when open respberry pi imager on my macbook,the detail as below:

![image](https://user-images.githubusercontent.com/47661168/114376852-9a4da680-9bb8-11eb-9396-c528a69a0681.png)

**Comment by maxnet** [comment]
Please try if this build works better: https://github.com/raspberrypi/rpi-imager/issues/202#issuecomment-813091261

**Comment by buddhist182** [comment]
It works ok, thank you!

**Comment by maxnet** [comment]
Good to hear
