### ISSUE TITLE
1.6.1 (and 1.6.2 b57da41 )  Blank Window displayed (and nothing else, non-functional)  on Ubuntu 20.04 

### ISSUE THREAD

**Issue by marcandrebenoit** [raspberrypi/rpi-imager#210]
Installed from sudo snap install rpi-imager And also tried earlier to install from the Software store both installing removing v. 1.6.1
when starting from the terminal I get this output  and repeats endlessly afterwards
I suppose it's just a dependency that's been omitted in the deb build at some point. 
The result is the same from latest/edge v. b57da41 installed from Software store (from snapcraft.io)

$: rpi-imager
Qt: Session management error: Could not open network socket
/usr/share/libdrm/amdgpu.ids: No such file or directory
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
/usr/share/libdrm/amdgpu.ids: No such file or directory
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.410\" (uid=1000 pid=613300 comm=\"/snap/rpi-imager/170/usr/local/bin/rpi-imager \" label=\"snap.rpi-imager.rpi-imager (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1134 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.410\" (uid=1000 pid=613300 comm=\"/snap/rpi-imager/170/usr/local/bin/rpi-imager \" label=\"snap.rpi-imager.rpi-imager (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1134 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
"Object path cannot be empty"
Buffer creation failed
Buffer creation failed
Buffer creation failed
QOpenGLShaderProgram: could not create shader program
QOpenGLShader: could not create shader
QOpenGLShader: could not create shader
shader compilation failed: 
""
QOpenGLShaderProgram::uniformLocation(matrix): shader program is not linked
QOpenGLShaderProgram::uniformLocation(opacity): shader program is not linked
QOpenGLShaderProgram::uniformLocation(pixelSize): shader program is not linked
QOpenGLShaderProgram: could not create shader program
QOpenGLShader: could not create shader
QOpenGLShader: could not create shader
shader compilation failed: 
""
QOpenGLShaderProgram: could not create shader program
QOpenGLShader: could not create shader
QOpenGLShader: could not create shader
shader compilation failed: 
""
QOpenGLShaderProgram: could not create shader program
QOpenGLShader: could not create shader
QOpenGLShader: could not create shader
shader compilation failed: 
""

**Comment by marcandrebenoit** [comment]
Installing the deb file from  https://downloads.raspberrypi.org/imager/imager_latest_amd64.deb   and using gdebi to install fixed the issue ( read in the output the now filled dependencies that are probably missing for your build) 

:$ sudo gdebi imager_1.6.1_amd64.deb 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
Requires the installation of the following packages: **libqt5quickcontrols2-5 libqt5quicktemplates2-5 qml-module-qtquick-controls2 qml-module-qtquick-templates2** 

Raspberry Pi imaging utility
 Graphical user-interface to write disk images and format SD cards.
Do you want to install the software package? [Y/N]:y
/usr/bin/gdebi:113: FutureWarning: Possible nested set at position 1
  c = findall("[[(](\S+)/\S+[])]", msg)[0].lower()
Fetched 0 B in 0s (0 B/s)                                                      
Selecting previously unselected package libqt5quicktemplates2-5:amd64.
(Reading database ... 338891 files and directories currently installed.)
Preparing to unpack .../libqt5quicktemplates2-5_5.12.8+dfsg-0ubuntu1_amd64.deb ...
Unpacking libqt5quicktemplates2-5:amd64 (5.12.8+dfsg-0ubuntu1) ...
Selecting previously unselected package libqt5quickcontrols2-5:amd64.
Preparing to unpack .../libqt5quickcontrols2-5_5.12.8+dfsg-0ubuntu1_amd64.deb ...
Unpacking libqt5quickcontrols2-5:amd64 (5.12.8+dfsg-0ubuntu1) ...
Selecting previously unselected package qml-module-qtquick-templates2:amd64.
Preparing to unpack .../qml-module-qtquick-templates2_5.12.8+dfsg-0ubuntu1_amd64.deb ...
Unpacking qml-module-qtquick-templates2:amd64 (5.12.8+dfsg-0ubuntu1) ...
Selecting previously unselected package qml-module-qtquick-controls2:amd64.
Preparing to unpack .../qml-module-qtquick-controls2_5.12.8+dfsg-0ubuntu1_amd64.deb ...
Unpacking qml-module-qtquick-controls2:amd64 (5.12.8+dfsg-0ubuntu1) ...
Setting up libqt5quicktemplates2-5:amd64 (5.12.8+dfsg-0ubuntu1) ...
Setting up qml-module-qtquick-templates2:amd64 (5.12.8+dfsg-0ubuntu1) ...
Setting up libqt5quickcontrols2-5:amd64 (5.12.8+dfsg-0ubuntu1) ...
Setting up qml-module-qtquick-controls2:amd64 (5.12.8+dfsg-0ubuntu1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
Selecting previously unselected package rpi-imager.
(Reading database ... 339321 files and directories currently installed.)
Preparing to unpack imager_1.6.1_amd64.deb ...
Unpacking rpi-imager (1.6.1) ...
Setting up rpi-imager (1.6.1) ...

**Comment by maxnet** [comment]
>Installed from sudo snap install rpi-imager
[...]
>Installing the deb file from https://downloads.raspberrypi.org/imager/imager_latest_amd64.deb and using gdebi to install fixed 
>the issue ( read in the output the now filled dependencies that are probably missing for your build)

The .deb IS our build. :-)

Please report snap issues here: https://github.com/popey/imager-snap/issues/
