### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ComputerDoktor** [raspberrypi/rpi-imager#211]
add automatic decompression for bzip2 .bz2 and zstd .zstd

**Comment by maxnet** [comment]
Not sure if the interest in those are worth the extra trouble on Windows and Mac OS X to add the extra dependencies.

On Linux every archive format supported by libarchive should already work out-of-the-box.

**Comment by ComputerDoktor** [comment]
Just an idea to help with the goal  "make Imager as easy to use as possible". Personally I know how to use bzip2 and zstd under Windows, although the decompression adds another timeconsuming step. But for a newbie bzip2 decompression may represent a hurdle.

**Comment by lurch** [comment]
How commonly are OS images distributed in bzip2 or zstd? :thinking:

**Comment by maxnet** [comment]
>zstd might become more common because of decompression speed.

Note that according to [zstd's own tests](https://facebook.github.io/zstd/) .gz (zlib) does 400 MB/sec as well on modern hardware.
So decompression speed is not really a limiting factor when writing to your average SD card that may do 40 MB/sec.

**Comment by mdevaev** [comment]
Zstd has a very high compression level and I would prefer to see it in the imager.

**Comment by hecko** [comment]
> Not sure if the interest in those are worth the extra trouble on Windows and Mac OS X to add the extra dependencies.
> 
> On Linux every archive format supported by libarchive should already work out-of-the-box.

Yocto Linux is by default built into bz2
