### ISSUE TITLE
[Third Party OS] DragonOS Pi64

### ISSUE THREAD

**Issue by alphafox02** [raspberrypi/rpi-imager#218]
Are there specific procedures to follow to have an OS added to the Raspberry Pi imager? DragonOS Pi64 is a Raspberry Pi 64bit Software Defined Radio Distribution. 

Here’s a link that’ll direct you to the Pi download along with one direct to the project on sourceforge. It would be nice if it could receive official Raspberry Pi imager support. 

https://cemaxecuter.com/

https://sourceforge.net/projects/dragonos-pi64/files/

**Comment by ghollingworth** [comment]
Like the other requests you'll have to provide a .json entry for your image.  Note your image should be stored on an https server that you own (so we can check the validity and prevent MitM attacks...)

Gordon
