### ISSUE TITLE
[OS Request] Homebridge (JSON ready)

### ISSUE THREAD

**Issue by oznu** [raspberrypi/rpi-imager#219]
Hello,

I'm a maintainer of the [Homebridge](https://github.com/homebridge/homebridge) project and would like to investigate the possibility of having the [Homebridge Raspberry Pi Image](https://github.com/homebridge/homebridge-raspbian-image) added to the *Other specific purpose OS* section of the RPI Imager tool.

I have created the relevant JSON:

```json
{
  "name": "Homebridge",
  "description": "Turn your Raspberry Pi into a HomeKit smart home bridge.",
  "icon": "https://user-images.githubusercontent.com/3979615/116509191-3c35f880-a906-11eb-9a7f-7cad7c2aa641.png",
  "subitems_url": "https://homebridge.io/rpi-image-repo.json"
}
```

As displayed under the **"Other specific purpose OS"** category:

<img width="792" alt="Screen Shot 2021-04-29 at 4 51 52 pm" src="https://user-images.githubusercontent.com/3979615/116512326-368ee180-a90b-11eb-9b80-a4299fcba9dc.png">

OS List:

![image](https://user-images.githubusercontent.com/3979615/116512784-e5332200-a90b-11eb-91fd-9b111e37af29.png)

**Comment by ghollingworth** [comment]
Done

**Comment by oznu** [comment]
Thanks!

**Comment by ghollingworth** [comment]
Can you email me at gordon@ this organisation dot com
