### ISSUE TITLE
Invalid wpa_supplicant if password contains double quote ( " )

### ISSUE THREAD

**Issue by matthew1471** [raspberrypi/rpi-imager#229]
Setting a wireless password that contains a " creates a wpa_supplicant which is invalid. The correct way to specify these passwords is by using wpa_passphrase (or the online version at https://www.wireshark.org/tools/wpa-psk.html)

firstrun.sh

```
...
cat >/etc/wpa_supplicant/wpa_supplicant.conf <<WPAEOF
country=GB
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
ap_scan=1

update_config=1
network={
	ssid="MyWiFi"
	psk="Ilovefishes"Ido!"
}

WPAEOF
...
```

I believe rpi-imager at a minimum should refuse to accept a password with a " or ideally could generate the correct passphrase (or escape if that's even possible?).

**Comment by maxnet** [comment]
Already fixed in #206
(Just no new version released since)

**Comment by matthew1471** [comment]
Doesn't say fixed in linked issue.. what version number is this fixed in please?

**Comment by maxnet** [comment]
>what version number is this fixed in please?

Fixed in source code in git commit b57da413a62b6c175807278dc0996e11372399de

As I said though, there has not been any new version publicly released since.
So you will either have to build from source or wait.

**Comment by lurch** [comment]
It's fixed in the source-code https://github.com/raspberrypi/rpi-imager/commit/b57da413a62b6c175807278dc0996e11372399de but there's not yet been a "release build" of RPi Imager which includes those changes. If you're desperate to pick up this fix in the short-term (before the next release build) you'll need to build your own version of RPi Imager from source.

**Comment by matthew1471** [comment]
I understand - thank you! :)

**Comment by lurch** [comment]
1.6.2 has just been officially released :smiley:
