### ISSUE TITLE
Tag for 1.6.2

### ISSUE THREAD

**Issue by XECDesign** [raspberrypi/rpi-imager#230]
I was just taking a look at updating the Raspberry Pi OS debs, but I'm not sure what commit was used to build the 1.6.2 files.

**Comment by lurch** [comment]
1.6.2 is also missing from https://github.com/raspberrypi/rpi-imager/releases but it _is_ in https://downloads.raspberrypi.org/imager/ :confused:

**Comment by maxnet** [comment]
>1.6.2 is also missing from https://github.com/raspberrypi/rpi-imager/releases but it is in https://downloads.raspberrypi.org/imager/ confused

Yeah, wasn't sure if the builds I sent in passed testing department/management scrutiny yet :)

Tagged and added to releases.
