### ISSUE TITLE
Imager overwrote my external 12TB RAID Array

### ISSUE THREAD

**Issue by xmready** [raspberrypi/rpi-imager#234]
Thanks a lot guys. Your software just overwrote my 12TB RAID external raid array. I put in an SD card and apparently Ubuntu didn't see it. I selected the only option as I have done this many times before with no problem. What I selected was my external RAID array which shouldn't even show up in the list because it's not an SD card. So there goes years of work. Thanks a lot. What a great piece of software.

**Comment by SeaGull711** [comment]
100% User Error

**Comment by cillian64** [comment]
It sounds like the tool worked as expected - given Pi can boot off USB, writing an OS to a USB drive is a valid use-case.
