### ISSUE TITLE
Standard out empty in CLI mode (Windows)

### ISSUE THREAD

**Issue by mbacke73** [raspberrypi/rpi-imager#238]
Trying to run the rpi-imager version 1.6.2 in CLI mode on an Windows PC. We intend to call the program from National Instruments TestStand and to be able to decide if the writing was successful or not we need to fetch the output from the program as standard out and standard error. Unfortunately these are empty.
Also tried to redirect the output to a file when calling the program from a command prompt but the output is still output to the window and the text file is empty.

Example command:
 rpi-imager-cli.cmd test.img  \\.\PhysicalDrive2 > test.txt 2> err.txt

Is there a way to have the output redirected to standard out?

**Comment by maxnet** [comment]
>to be able to decide if the writing was successful or not we need to fetch the output

Just for success/failure you can use the exit code of the program.

```
rpi-imager-cli.cmd test.img \.\PhysicalDrive2
IF %ERRORLEVEL% NEQ 0   echo Something went wrong
```

Not sure how to deal with output redirection properly on Windows (where there is a disctinction between cli and gui programs, and we are compiled as gui program).

**Comment by tdewey-rpi** [comment]
Workaround provided, which should meet the OP's request for success/failure determination. Please raise another issue if you required additional log messages.
