### ISSUE TITLE
Improvement - Changes on main GUI layout

### ISSUE THREAD

**Issue by bovirus** [raspberrypi/rpi-imager#241]
Current layout

![image](https://user-images.githubusercontent.com/1262554/121920678-8fd69700-cd38-11eb-879c-3154b44ec9bc.png)

Proposal of new layout

![image](https://user-images.githubusercontent.com/1262554/121921258-1e4b1880-cd39-11eb-9a4e-b6329be732fa.png)

**Changes**

- Move Write in bottom centered on wdth
- Enlarge button width for "S.O. name/ file name"
- Enlarge button width for "Select SD card /SD card name"
- Change "Operative system" text in "Operative system / file name"

**Comment by ghollingworth** [comment]
Thanks we'll take it into consideration.

**Comment by bovirus** [comment]
@ghollingworth

Pelase don't close it.
It's a pending request.
Leave it open. Thanks. KR.
