### ISSUE TITLE
rpi-imager advanced option to add a ssh key bricks ubuntu image

### ISSUE THREAD

**Issue by vonDowntown** [raspberrypi/rpi-imager#242]
Hey,
I noticed that if i write a ubuntu based image to my sd card and a added key the raspberry pi does not boot afterwards.
I use a headless install so until my microHDMI adapter arrives I am blind for the real error output.

As far as i am concerned it crashes because the user 'pi' is not present on a default ubuntu image (default: 'ubuntu'). 

Probably related to #213

**Comment by maxnet** [comment]
That's to be expected.
We only support customization on operating systems that mount the FAT partition at /boot

**Comment by cillian64** [comment]
We now only allow customisation to be applied to images which support it
