### ISSUE TITLE
Add an option to define partition sizes before installing on the expert menu.

### ISSUE THREAD

**Issue by gscorrea** [raspberrypi/rpi-imager#254]
Would like to define the size of patrtitions before installation, so we can resize at least the boot partition.
With new SD cards we can have /boot with 5G and not have issues with upgrading OS.

**Comment by lurch** [comment]
To do that, Rpi Imager would need to be able to also resize the filesystems inside the partitions, and on Windows it's not possible to resize Linux filesystems.

**Comment by gscorrea** [comment]
The issue is that the /boot partition is too small and do not allow to add more kernels.

**Comment by tdewey-rpi** [comment]
Marking as 'Won't fix'.

I don't see new or inexperienced users getting benefit from this feature, nor do I see clearly how to expose it in a manner where an inexperienced user doesn't do the 'wrong' thing.
