### ISSUE TITLE
[Feature request] SSID/Password illegal character check

### ISSUE THREAD

**Issue by HansTo** [raspberrypi/rpi-imager#255]
I've run into a couple of issues where either the SSID or the password contained troublesome characters. 
Raspberry Pi Imager v1.6 on Windows was used to generate the boot image.

The SSID/Password i have is the following Network_Things / A$T@Crlp[}l@ . The password is complex but it works for all my IOT devices so far. My understanding is that this password is considered legal according to Wifi standards.

I checked the **firstrun.sh** that raspberry pi imager creates and the password is listed correctly:
.......
```
systemctl enable ssh
cat >/etc/wpa_supplicant/wpa_supplicant.conf <<WPAEOF
country=US
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
ap_scan=1
update_config=1
network={
ssid="Network_Things"
psk="A$T@Crlp[}l@"
}
WPAEOF
chmod 600 /etc/wpa_supplicant/wpa_supplicant.conf
```
.....
After the script completed, I checked wpa_supplicant.conf and it had the following:

```
country=US
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
ap_scan=1
update_config=1
network={
ssid="Network_Things"
psk="A@Crlp[}l@"
```

it dropped the "**$T**", which is typical for I/O redirection. 

Can we escape the $ character somehow or build in a regexp in the program that highlights issues like this for new users?
https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Here-Documents

**Comment by maxnet** [comment]
>I checked the firstrun.sh that raspberry pi imager creates and the password is listed correctly:

Then you are a running an old version of Imager.
As in newer versions you should not see the password in clear text in firstrun.sh, but a hash instead.

Try if newer version likes your password better.
