### ISSUE TITLE
[OS Update Request] New JSON snippet for OctoPi

### ISSUE THREAD

**Issue by foosel** [raspberrypi/rpi-imager#259]
Hi there! In #162, OctoPi was added to the OS list - thanks for that, that's been a huge improvement for the OctoPrint community! 

Today I'd like to request a change of the `os-list` JSON snippet to this:

```json
{
    "name": "OctoPi",
    "description": "A Raspberry Pi distribution for 3D printers. Ships OctoPrint out-of-the-box.",
    "website": "https://octopi.octoprint.org",
    "icon": "https://octopi.octoprint.org/rpi-imager.png",
    "subitems_url": "https://octopi.octoprint.org/rpi-imager.json"
}
```

The goal is to change the JSON URL to a new canonical place and also add a website as recently suggested by @ghollingworth.

Pinging @guysoft so he can confirm.

Screenshots:

![image](https://user-images.githubusercontent.com/83657/128327782-0e92a2ea-f855-43b9-87e2-c3435fa1ba73.png)

![image](https://user-images.githubusercontent.com/83657/128327602-fd9ffea2-dfc3-4c15-ab2b-5b8068159f98.png)

**Comment by guysoft** [comment]
I confirm :)

**Comment by XECDesign** [comment]
Updated

**Comment by foosel** [comment]
Thank you, just confirmed!
