### ISSUE TITLE
& in SSID PSK changed to &;amp in interface

### ISSUE THREAD

**Issue by donb55** [raspberrypi/rpi-imager#260]
rpi-imager v1.6.2 being used to create OctoPi boot card for RPi 3B+ downloaded 8/4/2021 for Windows 10. Running Windows 10 Education OS Build 19043.1151.

In prepping for the write, I used Ctrl-Shift-X to enter the SSID and PSK. The PSK has an & in it (along with other alpha/numeric/special characters) and when booted, the Pi would not join the network. My solution was to check for any errors in the imager to prepare for another write. When I opened up the Ctrl-Shift-X interface, the **&** in the PSK had been changed to **&;amp** in the string. Just that one character was changed. 

My solution was to change the PSK on my router and in the rpi-imager interface to a simple alpha string and all worked fine. Then I changed the router back to the complex PSK and used raspi-config after first boot to change the PSK in Octopi and on reboot all was well.

Apparently the & in the PSK is causing a problem.

Thanks for a great program that makes an otherwise tedious process much easier. Appreciate what you do.

Don

**Comment by tdewey-rpi** [comment]
Closing this one as:

1. Stale
2. Likely resolved by hashing the password before passing it to the networking stack - which has been implemented in recent versions.
