### ISSUE TITLE
Eject media && play sound when finished not working at all with Ubuntu

### ISSUE THREAD

**Issue by mrkskwsnck** [raspberrypi/rpi-imager#261]
Hei @ll,

I′m running Raspberry Pi Imager v1.6.2 on an Ubuntu 20.04 based GNU/Linux distribution. Unfortunately, both check-marks

- Play sound when finished
- Eject media when finished

![image](https://user-images.githubusercontent.com/486983/128626322-5d87c685-34b2-4330-b94d-f861550294f8.png)

do not seem to work at all. In fact, both have no effect. I would appreciate a fix, though.

Thanks in advance
Markus

**Comment by tdewey-rpi** [comment]
Closing as 'Stale'.

v1.6.2 was.....a long time ago. If this still applies to v1.8.5, it deserves a fresh issue.
