### ISSUE TITLE
RasPi OS UI crash after install qml-module-qt-labs-folderlistmodel

### ISSUE THREAD

**Issue by cavonlee** [raspberrypi/rpi-imager#263]
I have a qt application using qml-module-qt-labs-folderlistmodel.

Somehow, my application crash the rpi-imager's UI, makes the CHOOSE OS button and CHOOSE STORAGE button disappear.  So I check for a long time, until i uninstall my dependency qml-module-qt-labs-folderlistmodel, rpi-imager works fine.

So here it is, I don't know if it's true, but some how, installing qml-module-qt-labs-folderlistmodel crashes rpi-imager.

**Comment by tdewey-rpi** [comment]
Cannot reproduce with v1.8.5 and Bookworm. Not clear what's changed, but it appears to be fixed.
