### ISSUE TITLE
How to change language

### ISSUE THREAD

**Issue by kardenwu** [raspberrypi/rpi-imager#271]
I noticed that there is a folder "`i18n`" in this warehouse. In fact, I am not used to using English, but I am used to my mother tongue, so I would like to ask how to change the language, because I did not find the button

**Comment by maxnet** [comment]
It will use the language of your operating system.

**Comment by Wowooco** [comment]
![image](https://user-images.githubusercontent.com/67304509/131244710-514928ec-222e-4df5-8d9d-0bc7622660d4.png)
What might be the problem? I set it up as you said, but it didn’t take effect!

**Comment by Wowooco** [comment]
> 它将使用您操作系统的语言。
![image](https://user-images.githubusercontent.com/67304509/131244744-bafaf0fa-ba54-4f61-8767-66db8f8720cf.png)
What might be the problem? I set it up as you said, but it didn’t take effect

**Comment by maxnet** [comment]
May need to restart after changing it.

Also note that we only currently have a translation for zh-CN, which I think is mainland China, simplified characters.
If you have some different variant, like zh-TW or zh-HK it will not work.

**Comment by Wowooco** [comment]
> May need to restart after changing it.
> 
> Also note that we only currently have a translation for zh-CN, which I think is mainland China, simplified characters.
> If you have some different variant, like zh-TW or zh-HK it will not work.

I'm sure I set zh_CN, Windows restarted, and other versions of rpi-imager were installed, but it didn't take effect.
System: Windows 10 Pro 21H1
Rpi-imager: 1.6.2

**Comment by maxnet** [comment]
Hmm, seems to be indeed a bug there.

Judging by the output of "powershell" "Get-WinUserLanguageList" it seems that Windows uses "zh-Hans-CN".
(On Linux and MacOS X it does seem to be zh_CN, so if the person that contributed the Chinese translations was using that, he may not have noticed).

Wonder if we should just change rpi-imager_zh_cn.ts to rpi-imager_zh.ts to have it match everything starting with "zh".

**Comment by Wowooco** [comment]
> Hmm, seems to be indeed a bug there.
> 
> Judging by the output of "powershell" "Get-WinUserLanguageList" it seems that Windows uses "zh-Hans-CN".
> (On Linux and MacOS X it does seem to be zh_CN, so if the person that contributed the Chinese translations was using that, he or she may not have noticed).
> 
> Wonder if we should just change rpi-imager_zh_cn.ts to rpi-imager_zh.ts to have it match everything starting with "zh".

What should I do, because I don’t know how to compile software by myself

**Comment by maxnet** [comment]
We will take care of it in a future version.
Unfortunately do not have a quick solution right now. (and am about to catch a plane, so cannot build it for you right now)
