### ISSUE TITLE
Flashing Ubuntu fails if advanced options have been previously saved

### ISSUE THREAD

**Issue by mairas** [raspberrypi/rpi-imager#273]
This made me waste one full day of my life: If I have previously saved the advanced options in Raspberry Pi imager and then, in a separate session, attempt to flash e.g. an Ubuntu image, flashing succeeds but the OS does not start properly because the `config.txt` file is (obviously) not compatible.

In my opinion, the `config.txt` customization should only be applied to Raspberry Pi OS derivatives (as indicated e.g. by the `/boot/issue.txt` file contents, or alternatively, it application of the advanced options should be made an explicit choice in the UI.

This is not a duplicate of Issue #242 because I never intended to apply the advanced options - it happened without me realizing it.

**Comment by cillian64** [comment]
We now only allow customisation to be applied to images which support it
