### ISSUE TITLE
[Feature request] Add support for hidden SSID

### ISSUE THREAD

**Issue by HansPeterHaastrup** [raspberrypi/rpi-imager#276]
Having the option to add the line 'Scan_SSID=1' into the wpa_supplicant.conf file during the writing of the image would be extremely helpful.

I'll see if I can make a pull request with this addition if time permits.

**Comment by 63BeetleSmurf** [comment]
This was annoying me as well so added the option: https://github.com/raspberrypi/rpi-imager/pull/332
