### ISSUE TITLE
Can't open advanced options. Keyboard shortcut collides with printer drivers 

### ISSUE THREAD

**Issue by highfredo** [raspberrypi/rpi-imager#279]
Hi,

The keyboard shortcut (Ctrl + Shift + x) used to open the advanced options collides with the one used with HP Uniersal Printing.

Is there any other way to open the advanced options without uninstalling the printer drivers?

![image](https://user-images.githubusercontent.com/5951524/134216103-8b8cbfb0-62bc-45d1-96c5-50ca37e3ca5c.png)

**Comment by cillian64** [comment]
Advanced options has an icon now
