### ISSUE TITLE
Two little typos in German translation file

### ISSUE THREAD

**Issue by meandthemachine** [raspberrypi/rpi-imager#281]
See line 346 of German translation file:
https://github.com/raspberrypi/rpi-imager/blob/a1da552aadb24a79d0b4da5dbf17d436c625491a/i18n/rpi-imager_de.ts#L346

"Authethifizierung" should be "Authentifizierung".

**Comment by lurch** [comment]
ping @AaronDewes

**Comment by AaronDewes** [comment]
Sorry. I'll submit a correction PR soon.
