### ISSUE TITLE
add hacktoberfest topic

### ISSUE THREAD

**Issue by niwla23** [raspberrypi/rpi-imager#282]
Hi,
What do you guys think about adding the hacktoberfest topic to this and maybe other raspberry projects so contributions count for https://hacktoberfest.digitalocean.com/ ?

**Comment by lurch** [comment]
Sounds like a question / suggestion that's more suitable for discussion at https://www.raspberrypi.org/forums/ :question:

**Comment by niwla23** [comment]
well it is very hardly related to the repo, not sure where that goes
