### ISSUE TITLE
Imager is creating misaligned partitions on USB disks with SATA controllers.

### ISSUE THREAD

**Issue by mike-silva** [raspberrypi/rpi-imager#284]
Imager is creating misaligned partitions, on external USB disks with a SATA controller, which can lead to some performance degradation. Likely because it is using a partitioning tool that hasn't had an important fix back ported to it. See:
http://gparted-forum.surf4.info/viewtopic.php?id=17839

**Comment by tdewey-rpi** [comment]
Closing as stale - no reply since '21.
