### ISSUE TITLE
Unable to boot successfully when using advanced options with Ubuntu Server 20.04.3 LTS

### ISSUE THREAD

**Issue by saltedlolly** [raspberrypi/rpi-imager#286]
When trying to use advanced mode to enable SSH, set hostname, password etc. with Ubuntu Server 64-bit the screen goes blank towards the end of the boot process when booting from the Pi 4 8Gb. No errors are displayed on the screen - the display seems to cut out.

**Comment by suabahasa** [comment]
I have the exact same issue.
Is there any workaround? I didn't have a wired keyboard to do first-run wizard

**Comment by lurch** [comment]
> Is there any workaround? I didn't have a wired keyboard to do first-run wizard

That's probably a question for the Ubuntu forums? :shrug:

**Comment by saltedlolly** [comment]
Just a heads up in case people are unaware of this - the Advanced settings are only for Raspberry Pi OS and not for any other distros. The imager really doesn't make this clear, and it really should.

**Comment by lurch** [comment]
> I have since learnt that the Advanced Settings are only for customising Raspberry Pi OS and don't work with any other distros.

Just like it says in the issue #213 that I linked to? :wink:

**Comment by maxnet** [comment]
There is some experimental support for customizing Ubuntu server in git, if you are adventurous, and know how to compile it from source.
Not general release ready yet.

(Requires that you use the "use custom image file from disk" option for now. As it only does customization for images from the repository if they are marked there as supporting it, and that is not setup yet).

**Comment by saltedlolly** [comment]
> There is some experimental support for customizing Ubuntu server in git, if you are adventurous, and know how to compile it from source. Not general release ready yet.
> 
> (Requires that you use the "use custom image file from disk" option for now. As it only does customization for images from the repository if they are marked there as supporting it, and that is not setup yet).

I'm pleased to hear that support for this is coming. It's a really useful feature to have. I'd love to be able to set the default user anme as well - currently, you are stuck with 'pi'. IIIRC that's not possible to change at the moment.

**Comment by lurch** [comment]
> I'd love to be able to set the default user name as well - currently, you are stuck with 'pi'. IIIRC that's not possible to change at the moment.

That's being discussed in #287

**Comment by guysoft** [comment]
Anyone knows if what fixes this is this: https://github.com/raspberrypi/rpi-imager/commit/8f9fbcffebb2a37c0f9ad0c58e3bddc2789c05a1 (First attempt at cloudinit support)?
Or this: https://github.com/raspberrypi/rpi-imager/commit/71c1ea21dddcf36181e8e653cb194e4608bccf91 ( Customization: also apply changes if there is only firstrun and no cmdline/config changes)?

**Comment by maxnet** [comment]
>Anyone knows if what fixes this is this: 8f9fbcf (First attempt at cloudinit support)?
>Or this: 71c1ea2 ( Customization: also apply changes if there is only firstrun and no cmdline/config changes)?

Need both.

If you only cherry pick the first, it only applies custom settings if you also have an option selected that modifies config.txt, such as "disable overscan"

**Comment by guysoft** [comment]
Thanks, also worth mentioning this comment of yours since knowing that custom images work differently is also something important if you want to debug this :)
https://github.com/raspberrypi/rpi-imager/issues/324#issuecomment-994186726

**Comment by colinwang1703** [comment]
What a coincidence, so am I. I also encountered this issue on Ubuntu 22.04.
