### ISSUE TITLE
Distorted GUI appearance due to QT environment variable

### ISSUE THREAD

**Issue by femto-code** [raspberrypi/rpi-imager#292]
The Imager GUI seems to behave completely erroneous (Win10 latest, latest 1.6.2 Imager)
![image](https://user-images.githubusercontent.com/59444046/137702293-875fa833-3fc7-4f7c-8614-b10442248eae.png)

This seems to be the case if the QT environment variable is set as follows:

`QT_QUICK_BACKEND: software`

Due to development requirements this variable is needed and therefore results in the situation of RPi Imager being hardly usable.
Same applies to machines where hardware acceleration might not be available.
Thanks in advance!

**Comment by tdewey-rpi** [comment]
Closing as:

1. Stale
2. Not clearly a case typical users will encounter, nor one that is obviously the fault of Raspberry Pi Imager. This seems as likely to affect any QtQuick2 application.
