### ISSUE TITLE
Typing with password selected only deletes, does not use keystroke in password (Advanced Options UI)

### ISSUE THREAD

**Issue by steveredden** [raspberrypi/rpi-imager#296]
First character pressed while highlighting `Set password for 'pi' user:` password value, does not add the character to the input-field.  It solely wipes out the existing masked password

### Steps to Reproduce

1. have an existing password saved (use `to always use`)
2. restart raspberry pi imager
3. open advanced options
4. highlight the existing masked password
5. type the first two characters of your desired password
6. -> see only one character in the masked input

![baddelete](https://user-images.githubusercontent.com/35814432/138385307-b381720d-b69c-4f72-8d64-4a2b5ccf0c3b.gif)

**Comment by lurch** [comment]
Fixed by #753
