### ISSUE TITLE
Neither symlinks nor ZFS work?

### ISSUE THREAD

**Issue by NetwarSystem** [raspberrypi/rpi-imager#297]
I'm running rpi-imager 1.6.2 on Ubuntu 20.04.

My system has a 4TB drive that's ZFS formatted - it's /fourtb and there is a /fourtb/inst area that hold various ISOs and OVAs. I place an IMG for my Pi4 there, when I click to the top level of the system, rpi-imager does not see /fourtb.

As an alternative, I created a symlink /home/install that points to /fourtb/inst. Again, rpi-imager doesn't seem to see this link.

I tried various permutations of this, messing with directory ownership, there's nothing I can do to convince rpi-imager to use an image stored on ZFS outside my account's home directory. This is super odd ... because /home/me is actually a ZFS dataset with its mount point set there.

This isn't a show stopper, it's just an irritation for me having a 9GB img sitting in my home directory. It's just weird to me that an app has any idea about file system types and symlinks, that should be abstracted well away from the user application space ... which is kinda the whole reason for using Unix in the first place.

**Comment by lurch** [comment]
Perhaps this is similar to the network-mounts problem, where the network-mount is only visible at the "user process" level, but not visible at other user-levels? (e.g. the elevated-level needed by RPi Imager to be able perform raw block-level writes to an SD card)

**Comment by maxnet** [comment]
>e.g. the elevated-level needed by RPi Imager to be able perform raw block-level writes to an SD card

Imager does not run elevated on Linux.
(When writing we ask the privileged udisks2 process through DBus to open the raw device and pass us the file descriptor through DBus).

Think the oppositie is true though.
Symptoms sounds like Imager is run in a sandbox.


>I'm running rpi-imager 1.6.2 on Ubuntu 20.04.

If you happen to be running the snap (distributed through Ubuntu software center and the like) uninstall it.
Grab our .deb from the "releases" page here instead...

**Comment by lurch** [comment]
Thanks for correcting my misinformation :+1: :smiley:
