### ISSUE TITLE
Discussion: verification of writes

### ISSUE THREAD

**Issue by davidferguson** [raspberrypi/rpi-imager#3]
Currently the app verifies all SD card writes, which adds on a couple of minutes after the write, depending on how large the image file is. I haven't currently exposed a way of disabling this.

My thoughts are it should be enabled by default, but I'm currently unsure whether we want an option for disabling it at all. Verification is rather useful, and eliminates bad SD cards and other issues. However some users may get irritated with the extra few minutes it takes.

**Comment by Saijin-Naib** [comment]
Was going to ask for a hash/verification option.

If it's on by default, that's wonderful. Hopefully the GUI provides feedback (progress bar?) for this part of the process, as well.

**Comment by maxnet** [comment]
>If it's on by default, that's wonderful. Hopefully the GUI provides feedback (progress bar?) for this 
>part of the process, as well.

It does two types of verification:

1) While it downloads/writes/extracts it verifies if the sha256 is correct with what is listed in the .json file on the repository
If the download has been tampered with, it will fail with an error, as well as prevent the user from using the SD card. (will have a blank partition table).

2) After writing it verifies if the write went successful by reading back the contents of the SD card and computing the sha256 hash a second time.
During verify you will see a green progress bar.
It is on by default but can be cancelled by user, by pressing "cancel verify" button.
Read failures / hash mismatches will be reported back to user, but user is not prevented from using the card in that case.

**Comment by Saijin-Naib** [comment]
Absolutely fantastic. I look forward to trying it shortly.
