### ISSUE TITLE
Ubuntu 18.04 small font on 4K

### ISSUE THREAD

**Issue by judgewooden** [raspberrypi/rpi-imager#30]
Ubuntu 18.04.4 LTS
GNOME 3.28.2
Linux mad 4.15.0-88-generic #88-Ubuntu SMP x86_64
Dimensions: 7680x2160 pixels (2032x571 millimeters)
Resolution: 3840x2160 (16:9)
Scaling: 200%

Seems application is not using Scale percentages. 

![Screenshot from 2020-03-11 14-32-18](https://user-images.githubusercontent.com/1908675/76422348-57ae0f00-63a5-11ea-87c2-84fc0aece55e.png)
![Screenshot from 2020-03-11 14-22-35](https://user-images.githubusercontent.com/1908675/76422351-5846a580-63a5-11ea-9e91-53ae8bd3ebc1.png)

**Comment by judgewooden** [comment]
I noticed a workaround for the same issue on Windows using:
`export QT_SCALE_FACTOR=2
rpi-imager`

This solves the scaling for the main display but get error:
`QObject::setParent: Cannot set parent, new parent is in a different thread`

![Screenshot from 2020-03-11 14-41-30](https://user-images.githubusercontent.com/1908675/76422996-6e089a80-63a6-11ea-8989-61a1afd429d3.png)
![Screenshot from 2020-03-11 14-41-05](https://user-images.githubusercontent.com/1908675/76422999-6f39c780-63a6-11ea-9efd-5967435c5563.png)

**Comment by maxnet** [comment]
Might be specific to window manager used, or some other settings.
Not reproducible under Kubuntu 18.04 (Ubuntu with KDE desktop)

![kubuntu-1804](https://user-images.githubusercontent.com/1123701/76424664-d5bfe500-63a8-11ea-8d30-eba5fa207201.png)

**Comment by judgewooden** [comment]
QObject::setParent: Cannot set parent, new parent is in a different thread

> Might be specific to window manager used, or some other settings.
> Not reproducible under Kubuntu 18.04 (Ubuntu with KDE desktop)
> 
> ![kubuntu-1804](https://user-images.githubusercontent.com/1123701/76424664-d5bfe500-63a8-11ea-8d30-eba5fa207201.png)

I switched to kubuntu and had the same problem with the dropdown. Did a clean install on another machine and did not have the problem with ubuntu 18.04 Gnome or Ubuntu. I played around with resolutions and other options but the problem does not go away for the drop bow.. 

My machine have been a clean install on 16.04 and recently upgraded to 18.04 LTS.

What can I do to help find the cause?

**Comment by maxnet** [comment]
>I switched to kubuntu and had the same problem with the dropdown.

Using the same installation, without removing any accessibility settings you had in GNOME first?

My guess you have some special setting somewhere that causes fonts to be drawn larger then the application requests, but does not do any other scaling. (The fonts in your Libreoffice also look disproportionately large to the other controls).

**Comment by waveform80** [comment]
I have noticed that Qt-based applications (quassel, keepassx, and the pi imager) don't obey the scaling if it's applied while the application is running, but close and re-open the application and suddenly things are fine(ish). In other words, Qt only appears to read (or apply?) the scaling setting at startup.

If there's an issue specific to the pi imager here, it would be useful to confirm that it's an issue encountered when opening the application fresh after applying scaling settings. Otherwise, this may just be a general upstream Qt issue.

**Comment by judgewooden** [comment]
Installed ubuntu 20.04 and the problem went away. I also have a windows 10 machine configured to the same display using HDMI-2 - there I still have the problem.

I have 2x Panasonic TX-40FXW654

**Comment by akhepcat** [comment]
FYI -  this is a known issue for all QT apps  on high-DPI   monitors.

setting the environment variable  "QT_AUTO_SCREEN_SCALE_FACTOR=1 "    before starting the app
resolves the issue.

if  rpi-imager  could automatically detect the high-DPI screen and set the scale correctly, that would fix for everybody

**Comment by judgewooden** [comment]
okay - you can close the issue
