### ISSUE TITLE
Advanced options causing error

### ISSUE THREAD

**Issue by bylov** [raspberrypi/rpi-imager#301]
I'm using version 1.6.2 on Ubuntu 21.10 [installing Nextcloud](https://ubuntu.com/appliance/nextcloud/raspberry-pi) which works fine, but changing any of the advanced options, e.g. "Set hostname: raspberrypi.local" results in "Error creating firstrun.sh on FAT partition" when writing to a micro SD card (both via the internal card reader and also via a USB card reader).

![image](https://user-images.githubusercontent.com/74765587/140827346-9f88cbac-32b0-43de-8c01-e6f2cfa24102.png)

The card is writable. In order to troubleshoot, I actually managed to copy an empty file called firstrun.sh to the card just when the drive was mounted after the writing process had finished, but then I got a new error about not being able to find "/config.txt".

**Comment by lurch** [comment]
Are you using the snap package? If so, this might be a duplicate of #298 ?

**Comment by bylov** [comment]
Yep, that worked. Thanks @lurch.
