### ISSUE TITLE
Xbian .img fails when copied using Raspberry Pi Imager v1.6.2

### ISSUE THREAD

**Issue by slrslr** [raspberrypi/rpi-imager#303]
Hello,

i have used Raspberry Pi Imager v1.6.2-2 on Linux and selected last option from its menu - to use custom .img
and used Xbian_2021.11.05_Rpi4.img and booting failed as described [here](https://github.com/xbianonpi/xbian/issues/908).

**Comment by lurch** [comment]
Looking at the issue you've linked to, it seems that the problem is that your download is getting corrupted?

**Comment by slrslr** [comment]
Yes, it is likely i think. It was downloaded to a SD card (unsafe storage) which today fails to connect/load while other SD from same manufacturer and same type loads OK. :-S thank you for your input.
