### ISSUE TITLE
Config.txt

### ISSUE THREAD

**Issue by jamesbehling** [raspberrypi/rpi-imager#307]
My PC
Windows 10
RPI Imager 1.6.2

Steps
Start RPI
Choose OS - Custom - 2021-10-30-raspios-bullseye-arm64-lite.img
Chose Storage - SD Card
Ctrl + Shift + X
This session only
Enable SSH - set password
Enable WIFI - set SSID, set password
Save
Click Write Button

Error Message: 
Unable to customize. File D:/config.txt does not exist

**Comment by lurch** [comment]
Duplicate of #289 ?

**Comment by jamesbehling** [comment]
Same error message, but different steps.  I was using a custom OS, 64bit plus different advanced configuration.

**Comment by tdewey-rpi** [comment]
Closing as duplicate of #289 - different steps still translate into the same failure and likely cause.
