### ISSUE TITLE
[Feature Request] Option to enable / disable eject on successful image burn

### ISSUE THREAD

**Issue by raspberrycoulis** [raspberrypi/rpi-imager#317]
Whilst 99% of users may not use this, more advanced users may wish to add stuff to their SD card before the first boot and having the auto-eject option enabled by default (with no way of disabling) is a bit annoying.

For example, I like to add my own `.bash_profile` to my newly flashed Raspberry Pi's and I usually do this by copying the file to my SD card, SSH-ing into my Raspberry Pi then move it to the `/home/pi` location once I'm connected. However, as Raspberry Pi Imager automatically ejects my SD card when it has successfully burnt an image, it means I have to pull out my SD card then re-insert it before I can finish setting everything up.

On Balena Etcher, there was an option to turn off things like auto-eject (and verify) which was really handy when trying to get something done in as little time as possible, so having those options here would be fantastic.

**Comment by maxnet** [comment]
Scroll down in the advanced options (where you tried to set your ssh keys). There is an option for that at the bottom.
