### ISSUE TITLE
Add option to config headless wifi (ssid, password) from the UI

### ISSUE THREAD

**Issue by thewh1teagle** [raspberrypi/rpi-imager#319]
I would like to have the ability to choose the WiFi SSID and PSK when burning the file into to SD.
The ability to choose it right from the UI of this program.
Do you think you can implement that in your program?

**Comment by maxnet** [comment]
Try shift+ctrl+x

**Comment by thewh1teagle** [comment]
Damn!!
I don't believe the solution exist
Why it's hidden like that?

**Comment by lurch** [comment]
More details here: https://www.raspberrypi.com/news/raspberry-pi-imager-update-to-v1-6/

**Comment by cillian64** [comment]
This option is now accessible without the keyboard shortcut
