### ISSUE TITLE
Blurry window, strange resolution (Windows 11 x64)

### ISSUE THREAD

**Issue by thewh1teagle** [raspberrypi/rpi-imager#320]
When using the app from windows, the window is looking blurry, the text is small, and it feels bad

You can view part of it in this screenshot
![image](https://user-images.githubusercontent.com/61390950/144685976-538d621c-1409-4a3f-81c8-d3af11a903d4.png)

**Comment by tdewey-rpi** [comment]
@thewh1teagle Are you still seeing this with v1.8.5?

**Comment by thewh1teagle** [comment]
@thewh1teagle 
It was 2 years ago, I checked and looks like it doesn't happen now
