### ISSUE TITLE
[UI, UX] Empty window when clicking choose storage and there's no one.

### ISSUE THREAD

**Issue by thewh1teagle** [raspberrypi/rpi-imager#321]
When there's no storage to choose, you just opens an empty window
instead, let the user know there's no available stroage

Windows 11 x64 

![image](https://user-images.githubusercontent.com/61390950/144686208-744e8776-32ef-412d-9153-4d81ada99059.png)

**Comment by gabefair** [comment]
I am having the same issue. More info is that its also happening to me with M1 Macbook Air running Monterey (12.3.1)

**Comment by wing-py** [comment]
Me as the same
Ubuntu 20.04LTS
32GB microCard

**Comment by tdewey-rpi** [comment]
Fixed in a recent PR - will follow in a post-1.8.5 release.
