### ISSUE TITLE
Imager 1.6.2 for Mac: No OS options only erase or custom install

### ISSUE THREAD

**Issue by exidyboy** [raspberrypi/rpi-imager#328]
Imager 1.6.2 for Mac: No OS options only erase or custom instal
<img width="683" alt="Screen Shot 2021-12-29 at 11 03 04 am" src="https://user-images.githubusercontent.com/81691/147615888-d8e8412e-8f02-4426-ae2b-116940bf4f40.png">
l

**Comment by maxnet** [comment]
Any proxy server configured in Mac OS, or anything else out-of-the-ordinary network wise?

**Comment by exidyboy** [comment]
Yes I am behind a proxy. I didn't realise the Imager needed Internet access to populate the list of options. Perhaps it could display an error if there is a network problem preventing it from accessing the resources it needs?

**Comment by maxnet** [comment]
It do is supposed to show an error once it fails.
Not sure if that always works with proxy servers though, e.g. if they just take forever to respond instead of failing.

**Comment by exidyboy** [comment]
I timed it and if you are behind the proxy (where I work) you get an error  that says "Error downloading OS list from the Internet" after 12 minutes. Perhaps it could fail more gracefully.
<img width="683" alt="Screen Shot 2021-12-31 at 2 04 59 pm" src="https://user-images.githubusercontent.com/81691/147800809-a1f954e2-741b-4561-bc7d-31ce8b004e8e.png">

**Comment by maxnet** [comment]
Yes, might be 2 Qt bugs in here.

1) Qt does have does have code to automatically fetch and use the proxy settings of your operating systems.
Not sure why it does not work.
Could be that the more advanced proxy types (e.g. the proxies that require authentication) are not implemented.

2) We do set a network timeout of 5 seconds.
So normally you do should get that error really fast.
But it wouldn't surprised me if the timeout code is not working correctly in the more advanced corner cases. Like when proxies are used.
