### ISSUE TITLE
Windows 10: Doesn't recognize SD card

### ISSUE THREAD

**Issue by reibuehl** [raspberrypi/rpi-imager#33]
On my Windows 10 54bit system, the card is not shown in the card selection. Windows sees the card fine as drive J:, but Raspberry Pi Imager only shows me two internal 250 GB SSDs that belong to a dynamic volume / mirrored disk in Windows and what seems to be two empty slots of my SD/CF/MMC/etc. card reader. 

![Screenshot](https://user-images.githubusercontent.com/4268514/76568783-e6a84d80-64b1-11ea-81ae-ef238532375f.JPG)

![Screenshot2](https://user-images.githubusercontent.com/4268514/76568920-2ff89d00-64b2-11ea-8628-6793d47554dc.JPG)

**Comment by maxnet** [comment]
Can you try if it appears when using scroll wheel of your mouse?
As someone else mentioned the list not spanning the full height, and only seeing 4 items at the time, while there do was a 5th. #32

**Comment by reibuehl** [comment]
Yes, scroll wheel works now that you point me to it. There should be a slider or so to show that there are more options and I think that raw devices of dynamic volumes should not be shown.

**Comment by ghollingworth** [comment]
Should remove 0GB entries since that's usually how empty MSDs appear in multi-volume readers...

**Comment by ghollingworth** [comment]
#48 and #32 

Will close this one
