### ISSUE TITLE
Version update check failure

### ISSUE THREAD

**Issue by jpsingleton** [raspberrypi/rpi-imager#335]
It looks like you are preparing a new patch release (`1.6.3`?) but the update check doesn't currently work. The `latest_version` in [`os_list_imagingutility_v2.json`](https://downloads.raspberrypi.com/os_list_imagingutility_v2.json) only specifies major and minor but not patch (e.g. `1.6` not `1.6.2`).

It's probably worth adding the update of this file to the release process. It may also be good to add a flag to the app settings to disable update checking.

**Comment by maxnet** [comment]
Was intentional.
We did not want to nag users with an update prompt for some minor bug fixes that the average user wouldn't need.
