### ISSUE TITLE
[OS Request] FullPageOS

### ISSUE THREAD

**Issue by guysoft** [raspberrypi/rpi-imager#340]
Hey,
I am the maintainer of FullPageOS.

Note that it should go in the ``Other spesific purpose OS`` section.
```json
{
    "os_list": [
        {
            "name": "FullPageOS",
            "description": "Display a full page browser on boot in kiosk mode",
            "icon": "https://github.com/guysoft/FullPageOS/raw/devel/media/rpi-imager-FullPageOS.png",
            "subitems_url": "https://unofficialpi.org/rpi-imager/rpi-imager-fullpageos.json"
        }
    ]
}
```

The json file is built automatically using CustomPiOS new scripts

Tested locally and it works:
![Screenshot_20220126_005805](https://user-images.githubusercontent.com/325670/151073808-c19b6f16-c4a9-4c6d-9e8d-b6545affbe5f.png)

**Comment by ghollingworth** [comment]
Added
