### ISSUE TITLE
Bug  wrote contents of zip not the image contained within

### ISSUE THREAD

**Issue by DarkElvenAngel** [raspberrypi/rpi-imager#341]
Raspberry Pi Imager 1.6.2,

Image file downloaded from [tinycorelinux.net](http://tinycorelinux.net/13.x/armv6/releases/RPi/ )
File name `piCore-13.1.0.zip`

Bug report:  The files of piCore-13.1.0.zip were written to the SD card not the Image file it contained.

**Comment by maxnet** [comment]
If the .zip contains more than one file Imager will assume it is a NOOBS style .zip file that is meant to be extracted.

If the distro wants its files to work with Imager it must only put the .img file in the .zip, and nothing else.

**Comment by DarkElvenAngel** [comment]
Okay, I see thank you for clearing that up I though it was a bug.

I'll close this issue.
