### ISSUE TITLE
Setting up new user other than "pi" does not change /etc/subuid

### ISSUE THREAD

**Issue by ProjectInitiative** [raspberrypi/rpi-imager#356]
When using v1.7.1, and setting up custom install settings, if the username and password is changed from "pi" to a custom user, the /etc/subuid and /etc/subgid files still contains "pi" instead of inserting the new user which causes some permission issues for some apps. 

Kernel: 5.10.92-v8+
OS: RPIOS lite (64-bit) release: 2022-01-28

**Comment by lurch** [comment]
ping @XECDesign as this might be an "OS issue" rather than an "RPi Imager issue" ?

**Comment by XECDesign** [comment]
Looks like an Imager issue. I don't quite understand what these files do, but it sounds like something container software wouldn't like.

**Comment by maxnet** [comment]
Not sure why usermod does not modify those files for the new user name, if it was useradd that added the user to /etc/subuid in the first place.

Anyone knows the logic of that, or should we ask the shadow-utils folks?

**Comment by cillian64** [comment]
I've just checked and these files are updated with the correct username on the latest imager with the latest images.
