### ISSUE TITLE
Feature request - gadget mode options

### ISSUE THREAD

**Issue by WilliamNoad** [raspberrypi/rpi-imager#361]
I'd like to see a way to configure gadget modes with

- serial port
- Ethernet with optional static IP

The Pi Zero makes a useful tool for teaching shell scripting, Python, SQL, Perl, C/C++. Doing that through a basic CLI environment changes the teaching dynamic to focus much more on the subject matter than the application of some set of GUI tools.

**Comment by maniflopi** [comment]
I support the interest to parameterize the static ip

**Comment by tdewey-rpi** [comment]
Feature request rejected.

Raspberry Pi *Imager* isn't the right tool for this, but a custom image built with *pi-gen* or *pi-gen-micro* absolutely is.

Expect more documentation in this area in the future.
