### ISSUE TITLE
Unable to boot raspberry pi 3 B+ after power off before shutdown

### ISSUE THREAD

**Issue by saad-addverb** [raspberrypi/rpi-imager#368]
I am installing rasbian using rasberry pi imager. but first time it is getting started and I did the initial settings like language, wifi etc. after that I rebooted it and getting error as follows:

[end kernel panic - not syncing: VFS: unable to mount root fs on unknown -block(179,2) ].

after that I erased the data of sd card and again installed the rasbian from rasberrypi imager, this time i am unable to use sudo command and getting the error as follows whenever i am running any command:

syntax error /etc/apt/apt.conf.d/70debconf:1: Extra junk at end of the file

**Comment by lurch** [comment]
Sounds like perhaps your SD card is failing and giving you random errors? Safest option is to probably just buy a new SD card.

**Comment by tdewey-rpi** [comment]
Closing as won't fix. This isn't an issue with rpi-imager.
