### ISSUE TITLE
Error creating firstrun.sh on FAT partition on Ubuntu

### ISSUE THREAD

**Issue by EddieTheHead** [raspberrypi/rpi-imager#369]
Write process ends with "Error creating firstrun.sh on FAT partition".
Version: v1.7.1
Host os: Ubuntu 20.04.3 LTS
RPi os: RASPBERRY Pi OS (32 bit)
Options:
Enabled ssh, changed locale to pl/Warsaw, added custom password, added WiFi credentials. 
![pi imager](https://user-images.githubusercontent.com/7189283/154488590-c2df1feb-4369-4467-8e9d-99a51faf5545.jpg)
[rpi.log](https://github.com/raspberrypi/rpi-imager/files/8088851/rpi.log)

**Comment by maxnet** [comment]
>/snap/rpi-imager/221/usr/local/bin/rpi-imager

- Uninstall snap.
- Get the .deb from the releases page.

**Comment by CatoAntonsen** [comment]
Why is sthis closed? I have the same error, same version on Ubuntu  (20.04.4 LTS)

**Comment by maxnet** [comment]
>Why is sthis closed?

Because the log file of the user shows he is not using Raspberry Imager, but Canonical's Imager variant which is not provided by us.

>I have the same error, same version on Ubuntu (20.04.4 LTS)

And your Imager did came from a .deb file that you downloaded from the raspberrypi.com site or from the "releases" page here?

**Comment by CatoAntonsen** [comment]
I download it via raspberrypi.com > Software > Imager > Download for Ubuntu a86). When downloaded, FireFox opens it with Software Install (default). Failed to install file: Not supported.

 Ehere is "releases?

**Comment by maxnet** [comment]
> FireFox opens it with Software Install (default). Failed to install file: Not supported.

Not sure what application "Software install" is exactly.
If it's Ubuntu's ownsoftware manager, or something else accidently got associated with .deb files on your system.

Do you have a screenshot of it, complete with error message?

Alternatively, save the .deb to file first, and run: "sudo apt install ./rpi-imager_1.7.1_amd64.deb" from terminal.

>Ehere is "releases?

rpi-imager_1.7.1_amd64.deb at https://github.com/raspberrypi/rpi-imager/releases

**Comment by CatoAntonsen** [comment]
Thank you guys! It's working now! :-)

**Comment by simonschllng** [comment]
> but Canonical's Imager variant which is not provided by us.

Why are there always so many unofficial variants which just cause pain?

Thanks all for clarification. Annoying problem.
