### ISSUE TITLE
Error at writing on SD card

### ISSUE THREAD

**Issue by santimirandarp** [raspberrypi/rpi-imager#370]
I plug the SD card and when attempting to write, get this
```
code:~$ rpi-imager
/usr/share/libdrm/amdgpu.ids: No such file or directory
qrc:/main.qml:304:21: QML Rectangle: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
QObject::setParent: Cannot set parent, new parent is in a different thread
Custom config.txt entries: ""
Custom cmdline.txt entries: ""
Custom firstuse.sh: ""
Cloudinit: ""
Available disk space for caching: 0 GB
```

Any ideas?

**Comment by santimirandarp** [comment]
I don't know exactly why, but using Awesome WM I didn't get any prompt for a password. I logged into a different DE (plasma) and when pressing **write** it prompted for a password and wrote the image.

Very neat option for allowing ssh (I lack of a monitor so really needed to set up ssh config, and changing several files like netplan config, ssh stuff etc was a bit messy.).

**Comment by maxnet** [comment]
If you do have more than a gigabyte worth of space, it probably means that some environment variable like HOME is not set properly.

Caching downloaded files to disk is optional though.
It can stream the image straight from the Internet to your SD card. So wouldn't worry about it.

**Comment by santimirandarp** [comment]
@maxnet it seems the problem was installing as a snap. It was alerting me "FAT32 can not be read" or something of the sort.
I've seen exactly this issue before but it was closed.

I reckon the package is not anymore in apt, but downloading the .deb and installing it solved the issue, now it is burn into the SD card.

**Comment by santimirandarp** [comment]
Apart from that, my network got assigned wrong ID and password in the netplan config. I dont know if this may be because it has spaces in the name, so I quoted it, and fixd the pwd, and it worked fine!

**Comment by lurch** [comment]
@waveform80 We're consistently seeing errors when people use the snap version of RPi-Imager rather than the deb version (the snap version is maintained by a [third party](https://github.com/popey/imager-snap)). Any chance you could get Ubuntu to stop defaulting to the snap version and instead install the deb version?

**Comment by ghollingworth** [comment]
I think this isn't suitable, upstream will still be years out of date so we'd prefer not to have this there...
