### ISSUE TITLE
Please Add multi SD card write

### ISSUE THREAD

**Issue by MkLHX** [raspberrypi/rpi-imager#380]
Hello, thank you for the latest release with the parameters section it's soo helpful!

Is it possible to add the feature to select multiple SD card target for one write?

I mean, I need to create many SD cards with OS and minimal configuration (like the advanced options allow us now).

**Comment by ghollingworth** [comment]
What is it that you are trying to do here?

Why do you need to program more than one card at a time?

This isn't really suitable for mass provisioning, since things like passwords will all be the same.

**Comment by MkLHX** [comment]
The goal is to massively burn sd cards like balena etcher allowing us but with the Advanced Options like RPI Imager.
I need to burn sd cards with settings and config script to make many devices using RPI as heart.

**Comment by maxnet** [comment]
>to make many devices using RPI as heart.

It wouldn't be possible to let those devices write their own SD card?
https://github.com/raspberrypi/cmprovision supports customization through post-install scripts.

**Comment by MkLHX** [comment]
Thanks for this link but actually the RPI we used is RPI 3A+

**Comment by tdewey-rpi** [comment]
Closing as 'Won't fix'.

As Gordon identified, this mechanism is absolutely not what you're looking for. If you're looking to mass provision devices, you need to investigate creating a custom image using pi-gen or similar. Using rpi-imager for this may result in shared passwords and authentication secrets - which pose a security risk to the entire family of devices.
