### ISSUE TITLE
[OS Request] PleromaPi

### ISSUE THREAD

**Issue by guysoft** [raspberrypi/rpi-imager#382]
Hey,
I am [maintaining the Pleroma RaspeberryPi distribution known as PleromaPi](https://git.pleroma.social/pleroma/pleroma#raspberry-pi).
[Pleroma](https://pleroma.social/) implements the [ActivityPub 2.0 W3C standard for social networks](https://www.w3.org/TR/activitypub/) making it part of the federated social network the [Fediverse](https://en.wikipedia.org/wiki/Fediverse).
Pleroma has been built to be light enough to run on a raspberrypi 4 [as stated in their FAQ](https://blog.soykaf.com/post/what-is-pleroma/).

The distribution flashes a docker-managed of Pleroma. It handled all the certificate management on Let's encrypt.

The code and instructions are here: https://github.com/guysoft/PleromaPi
```json
{
    "os_list": [
        {
            "name": "PlermoaPi",
            "description": "Runs a Pleroma fediverse federated social network node",
            "icon": "https://raw.githubusercontent.com/guysoft/PleromaPi/devel/media/rpi-imager-PleromaPi.png",
            "website": "https://github.com/guysoft/PleromaPi",
            "subitems_url": "https://unofficialpi.org/rpi-imager/rpi-imager-pleromapi.json"
        }
    ]
}
```

**Comment by tdewey-rpi** [comment]
Please fill out the form to request an addition to the OS list at https://forms.gle/cbsU27aLLVaxUXbw8.
