### ISSUE TITLE
Pi4 set to SSH and WiFi on Imager 1.7.1, doesn't actually work

### ISSUE THREAD

**Issue by WanaGo** [raspberrypi/rpi-imager#384]
Burning the latest OS to uSD for the Pi4, and setting up SSH and WiFi etc in Raspbery Pi Imager 1.7.1, does not seem to work when the card is put into the Pi.

SSH is not enabled.
WiFi is not enabled.
Once I got SSH working by taking the card out again and putting a blank ssh file onto the /boot and putting it back in the Pi again, and then I SSH into the Pi (using Ethernet), the terminal looks like this:
![image](https://user-images.githubusercontent.com/759846/156962978-5a53b9ee-e13b-42b4-9a6e-bddb4938d913.png)

Here are the Pi Imager settings:
![image](https://user-images.githubusercontent.com/759846/156962961-605d722e-9d86-457e-8368-b603d5bfb072.png)

Am I doing something wrong, or is this simply not working right?

First time using this feature, thought it would nice to have SSH enabled and set up WiFi before I get in so it works right off the bat, but its not working at all.

**Comment by WanaGo** [comment]
> It did provided you with a "cog icon" button to do so? (As you can also access the advanced settings with a key combination, but settings will not be applied if using an OS image that does not support customization).

Cog icon yes. Latest 32bit OS, didnt use key-combinations, this is via PC so used keyboard and mouse v1.7.1 imager for windows.
 
> After pressing "OK" in the advanced settings, the advanced setting window did close? (If not, there may be a setting highlighted in RED that you incorrectly set)

Yes it closed. I also saved the settings and can go back in and all is set as per my picture above. No issues there.

> If after writing the customized image, you reinsert the card in your SD card reader again instead of sticking it in your Pi, did it create a firstrun.sh file on the FAT partition of your SD card?

Yes, image below.
 
> Concerns the same Windows computer as in your different issue about CM4?

Yes same computer. New a few months ago, Latest up-to-date Windows 10 Pro x64 21H1, Ryzen 9 5950X AMD processor, 64GB RAM, 3080 GPU, etc.

![image](https://user-images.githubusercontent.com/759846/157123279-e8c0a8f5-38a9-413a-b034-cefc54cb592c.png)
![image](https://user-images.githubusercontent.com/759846/157123366-0855e211-0041-4efc-82d3-f3e4de3d32f5.png)
![image](https://user-images.githubusercontent.com/759846/157123432-dafd9c67-628d-4637-a221-fce482663ad5.png)
![image](https://user-images.githubusercontent.com/759846/157123481-36ce6ca8-5965-4c6a-828a-741f560e5670.png)
![image](https://user-images.githubusercontent.com/759846/157124258-fdcde6b0-723d-4d2b-b634-335fe08d2a49.png)
![image](https://user-images.githubusercontent.com/759846/157124412-4ea2ff8b-6d45-4b8a-be1a-ea239050d55e.png)
![image](https://user-images.githubusercontent.com/759846/157124470-06dad333-5d4f-4da8-b988-a964a3547d6d.png)

This time it worked - SSH enabled, Wifi working, but I had just updated the bootloader to the beta... would that have made a difference?
Nothing changed in my settings, same uSD card, same Pi4, same computer, same everything other than new bootloader.

**Comment by maxnet** [comment]
>This time it worked - SSH enabled, Wifi working, but I had just updated the bootloader to the beta... would that have made a 
>difference?

Negative.
firstrun.sh logic does not depend on the bootloader. Entirely handled by Linux/systemd.

If there was something very wrong with the SD card reader (driver) in your computer. E.g. if it did not finish writing the file to storage yet when we tell it to eject the card, and does not correctly flush the data to storage before doing so, than such things do could happen.
But that does not explain why it did not work correctly with CM4 either earlier.

**Comment by d3-worgan** [comment]
Im having the exact same problem. I have tried editing the config in /netplan as described in ubuntu [guide](https://ubuntu.com/tutorials/how-to-install-ubuntu-on-your-raspberry-pi#4-boot-ubuntu-server) but no joy. Very odd.

**Comment by d3-worgan** [comment]
Yes the imager doesnt actually work. Or maybe my Pi is broken? I have a Pi 3 and used the imager with Ubuntu Server 22.04 LTS 64 bit. The website says Raspberry pi 3 is officially supported. For some reason the wlan0 is not listed in /sys/class/net. I tried manually running the driver. In the boot logs I get an error saying the chip is not supported. Anyone have any suggestions?
![IMG_0658](https://github.com/raspberrypi/rpi-imager/assets/56825720/9a40f87a-7747-421a-89c5-b241bfd8f572)

**Comment by maxnet** [comment]
>Ubuntu Server 22.04 LTS 64 bit

Suggest you try a different Linux distribution like RPI OS first before anything else...
