### ISSUE TITLE
[OS Request] RealtimePi

### ISSUE THREAD

**Issue by guysoft** [raspberrypi/rpi-imager#387]
An out of the box RaspberryPi OS distro with a realtime kernel. The kernel is a [RaspberryPi kernel](https://github.com/raspberrypi/linux) patched with the [Preempt RT patch](https://wiki.linuxfoundation.org/realtime/start). Kernel patches are [taken from here](https://wiki.linuxfoundation.org/realtime/documentation/howto/applications/preemptrt_setup).

It has been running for quite some time, and has a few hundred instances that I know of. Its quite popular with realtime audio processing and some hardware stuff.

```json
    "os_list": [
        {
            "name": "RealtimePi",
            "description": "An out-of-the-box RaspberryPi OS with a realtime kernel",
            "icon": "https://raw.githubusercontent.com/guysoft/RealtimePi/devel/media/rpi-imager-RealtimePi.png",
            "website": "https://github.com/guysoft/RealtimePi",
            "subitems_url": "https://unofficialpi.org/rpi-imager/rpi-imager-realtimepi.json"
        }
    ]
```

**Comment by tdewey-rpi** [comment]
Please fill out the form to request an addition to the OS list at https://forms.gle/cbsU27aLLVaxUXbw8.
