### ISSUE TITLE
[OS Request] UbuntuDockerPi

### ISSUE THREAD

**Issue by guysoft** [raspberrypi/rpi-imager#389]
Ready to use 64bit ARM Docker for Raspberry Pi running on Ubuntu

pi-imager PR: https://github.com/guysoft/pi-imager-web/pull/3

This image in many cases used by people to build stuff for arm64.
My telemetry has ~100 people using it now. Might be more I can't see.

```json
    "os_list": [
        {
            "name": "UbuntuDockerPi",
            "description": "Ready to use 64bit ARM Docker for Raspberry Pi based on Ubuntu",
            "icon": "https://raw.githubusercontent.com/guysoft/CustomPiOS/devel/media/rpi-imager-CustomPiOS.png",
            "website": "https://github.com/guysoft/UbuntuDockerPi",
            "subitems_url": "https://unofficialpi.org/rpi-imager/rpi-imager-ubuntudockerpi.json"
        }
    ]
```

**Comment by lurch** [comment]
"Ready to use 64bit ARM Docker for Raspberry Pi running on Ubuntu" makes it sound like an image that you'd run on your desktop Ubuntu PC, rather than on your Raspberry Pi? :confused: (i.e. perhaps it needs rewording slightly)

**Comment by guysoft** [comment]
@lurch
Sure enough, fixed

**Comment by tdewey-rpi** [comment]
Please fill out the form to request an addition to the OS list at https://forms.gle/cbsU27aLLVaxUXbw8.
