### ISSUE TITLE
[OS Request] PrimeOS - Android for PC's

### ISSUE THREAD

**Issue by NonstickAtom785** [raspberrypi/rpi-imager#393]
PrimeOS was ported to the Raspberry Pi. There isn't any source code but the latest image is hosted here:
[PrimeOS-2.1.0-20220304-Raspberry-Pi4.zip](https://sourceforge.net/projects/primeos/files/rpi4/PrimeOS-2.1.0-20220304-Raspberry-Pi4.zip/download)

Official Post from Prime OS on Raspberry Pi forums:
[[ROM][BETA] PrimeOS 2.1.0 for Rpi4 and Pi4B](https://forums.raspberrypi.com/viewtopic.php?t=330784)

**Comment by ghollingworth** [comment]
No source means you're breaking the GPL, so it won't be accepted

**Comment by NonstickAtom785** [comment]
Fair point. I wasn't thinking about that.
