### ISSUE TITLE
[OS Request] FreedomBox, a home server for privacy and data ownership

### ISSUE THREAD

**Issue by SunilMohanAdapa** [raspberrypi/rpi-imager#395]
I am a part of the core development team for FreedomBox.

FreedomBox is a self-hosting home server for privacy and data ownership. Using FreedomBox, owners of Raspberry Pi can easily setup and manage various services at home such as instant messaging, hosting blogs & websites, file sync, file sharing, audio conference, calendar, email, vpn, etc. FreedomBox manages security updates, TLS certificates and firewall automatically. See documentation for a full list of [features](https://wiki.debian.org/FreedomBox/Features). FreedomBox is sub-project of Debian, is fully free software and follows Debian's Free Software Guidelines (DFSG).

Please add FreedomBox to the Raspberry Pi Imager to make is easy for Raspberry Pi owners to find and setup FreedomBox. This is preferably done in a new "Home Server" category in the menu (or the existing "Other specific-purpose OS" otherwise) as follows:

```
{
    "name": "Home Server",
    "description": "Servers at home for privacy and data ownership",
    "icon": "icons/cat_home_server.png",
    "subitems": [
        {
	    "name": "FreedomBox",
            "description": "A home server for privacy and data ownership (a Debian project)",
            "icon": "https://ftp.freedombox.org/pub/freedombox/hardware/raspberry64/icon.png",
            "subitems_url": "https://ftp.freedombox.org/pub/freedombox/hardware/raspberry64/rpi-imager.json"
	}
    ]
},
```

The OS list file is in URL above is built by FreedomBox CI pipeline for Raspberry Pi images. The "Testing" image entry is updated weekly.

The following tests have been performed successfully:

- Run ./rpi-imager --repo ./os_list_imagingutility_v3-with-freedombox.json . Ensure that 'Home Server' category shows up with supplied icon (test image), name and description. Browsing 'Home Server' category shows entry for 'FreedomBox' with expected icon, name and description. Browsing the 'FreedomBox' entry shows two available images for stable and testing. Icon, name, description, release date and download size shows up correctly for each of the images.

- For each of the images, writing an SD card with the Imager finishes successfully. SD card boots successfully both on Raspberry Pi 3B+ and Raspberry 4B. FreedomBox interface is available and basic operations such as first setup and app installation can be completed.

- When build of Testing image is triggered on FreedomBox CI pipeline, the oslist JSON file needed by Imager is successfully updated on the download server. Writing the generated image succeeds.

**Comment by tdewey-rpi** [comment]
Please fill out the form to request an addition to the OS list at https://forms.gle/cbsU27aLLVaxUXbw8.
