### ISSUE TITLE
Error creating firstrun.sh on FAT partition on Raspberry PI OS Lite (64-bit)

### ISSUE THREAD

**Issue by darkoverlordofdata** [raspberrypi/rpi-imager#412]
I installed the .deb at https://github.com/raspberrypi/rpi-imager/releases/tag/v1.7.2. But when I run it the title bar says Raspberry PI Imager v1.71, so I'm not sure which version it is.
I'm using the Advanced options to preset the user name, wifi, and locale. It finishes writing, it gets the error popup at the end of verifying.
My OS is KDE Neon 5.24, a debian based distro.

**Comment by maxnet** [comment]
>But when I run it the title bar says Raspberry PI Imager v1.71, so I'm not sure which version it is.

Try "sudo snap remove rpi-imager"

**Comment by tdewey-rpi** [comment]
Closing as stale, no feedback since '22.
