### ISSUE TITLE
[OS Request] Add Manjaro ARM

### ISSUE THREAD

**Issue by Strit** [raspberrypi/rpi-imager#42]
I don't see a list anywhere we can make pull requests to, so I am just making this request, as it seems to be the only way to do it.

We (Manjaro ARM) would like to be represented on the list of possible OS's to be installed via this tool.

Our current images can always be found at OSDN:
https://osdn.net/projects/manjaro-arm/storage/rpi4/

Currently our supported editions are KDE Plasma and XFCE editions.

**Comment by lurch** [comment]
@Strit Have a look at the comments in #21 

@maxnet Maybe it's worth adding a common label to all these similar requests?
#9 #11 #21 #42 ?
