### ISSUE TITLE
Add support for custom additions to config.txt and cmdline.txt

### ISSUE THREAD

**Issue by Jai-JAP** [raspberrypi/rpi-imager#423]
Add support for adding custom additions to config.txt and cmdline.txt in advanced options. I guess this is already used internally by the imager for setting up overscan etc... But I want to add some custom args to cmdline.txt and config.txt

**Comment by tdewey-rpi** [comment]
Feature request rejected.

As I've stated elsewhere - this function would fail the visibility and debuggability requirements of any feature in Raspberry Pi Imager - it would allow malicious users to present valid-looking instructions that could cause people to have invalid set-ups or introduce other problems that would be non-trivial to debug for a new user.
