### ISSUE TITLE
Download images behind a corporate firewall not working

### ISSUE THREAD

**Issue by amamabel** [raspberrypi/rpi-imager#433]
On Windows the Pi Imager can't download new images if the PC is behind a corporate firewall. It look like that the Imager does not use the certificate store of Windows.

![image](https://user-images.githubusercontent.com/33116245/166886128-c0b21397-9edd-4de7-ad6e-f2df0b5a7edd.png)

**Comment by maxnet** [comment]
It do should use the Windows certificate store. The schannel mentioned in the message is the Windows SSL library.

Your message is not about an unknown certificate, but about it unable to check if the certificate used is revoked.
Apparently the certificate used mentions a Certificate Revocation List server that should be consulted to double-check if the certificate has not been revoked, but your firewall has been misconfigured to block access to said server.

**Comment by lurch** [comment]
Do you see that error as soon as Imager starts, or only when you try to select an OS?

**Comment by maxnet** [comment]
>Do you see that error as soon as Imager starts, or only when you try to select an OS?

Can only occur during Image download.
(Image list download occurs through Qt/qml and that does a bad job checking certificates, but libcurl that is used for image downloads does do it properly)


In the case of downloads.raspberrypi.org the server that normally would be contacted to check if SSL certificate is still valid is: ocsp.sectigo.com
But if behind a corporate firewall that likes to "monitor" employee traffic, the certificate seen by Imager can be provided by the security software instead, and then whatever revocation list server is mentioned in that certificate will be consulted instead.

**Comment by amamabel** [comment]
> It do should use the Windows certificate store. The schannel mentioned in the message is the Windows SSL library.
> 
> Your message is not about an unknown certificate, but about it unable to check if the certificate used is revoked. Apparently the certificate used mentions a Certificate Revocation List server that should be consulted to double-check if the certificate has not been revoked, but your firewall has been misconfigured to block access to said server.

If i try to open the mentioned IP in the browser i got a message from our firewall that the IP is blocked. On a second try with the Imager the error message contains another IP. Unfortunately the downloads.raspberrypi.org host is working in my browser, I think our firewall has some problems with the load balancer of downloads.raspberrypi.org. I will redirect the issue to our firewall admin.

Thanks for the quick help :-)

**Comment by DeadRabbits307** [comment]
As a workaround for a short term solution: Download manually the image  [here](https://www.raspberrypi.com/software/operating-systems/) and choose as OS an own image located on your local storage

**Comment by markusschaber** [comment]
> As a workaround for a short term solution: Download manually the image [here](https://www.raspberrypi.com/software/operating-systems/) and choose as OS an own image located on your local storage

It works, but some extended settings (like preconfiguring host name and ssh certificate) won't apply this way, it seems.

**Comment by WhiteChamp** [comment]
> As a workaround for a short term solution: Download manually the image [here](https://www.raspberrypi.com/software/operating-systems/) and choose as OS an own image located on your local storage

how to flash this on sd card?

**Comment by maxnet** [comment]
>It works, but some extended settings (like preconfiguring host name and ssh certificate) won't apply this way, it seems.

Using which version of Imager, and which operating system image?
Need at least Imager v1.7.3 to properly customize RPI OS bookworm.

**Comment by markusschaber** [comment]
@tdewey-rpi The problem is that the affected users (especially in corporate environments) cannot fix it on their side. The correct fix would be for rpi-imager to honor the system certificate store for trusted root certificates.

**Comment by tdewey-rpi** [comment]
@markusschaber I got a notification for a comment that appears to have disappeared into the ether, so I'm going to inline it here:

`@tdewey-rpi The problem is that the affected users (especially in corporate environments) cannot fix it on their side. The correct fix would be for rpi-imager to honor the system certificate store for trusted root certificates.`

That is indeed a step `rpi-imager` could take, and one that it has took with 1.9.0.

Keeping this one closed.

**Comment by amamabel** [comment]
@tdewey-rpi nothing changed for me with 1.9.0
![image](https://github.com/user-attachments/assets/0aba52b2-323c-4e4a-937d-98c4947d2561)

**Comment by tdewey-rpi** [comment]
> @tdewey-rpi nothing changed for me with 1.9.0 ![image](https://private-user-images.githubusercontent.com/33116245/368965797-0aba52b2-323c-4e4a-937d-98c4947d2561.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NDg5OTIsIm5iZiI6MTcyNjc0ODY5MiwicGF0aCI6Ii8zMzExNjI0NS8zNjg5NjU3OTctMGFiYTUyYjItMzIzYy00ZTRhLTkzN2QtOThjNDk0N2QyNTYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDEyMjQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhYjM5Njk2MTdhNWExYWU5Y2RjYWYzNzBlNjU1Y2QyZjc0ODk4NTA0NDMxMDNjYmE0NjUxMzlhY2VlM2JkZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.59acMTfIfnX0nhYNNbZ6X6pxfrzSDkGi3ae2rkJkhyY)

Please raise a new issue.
