### ISSUE TITLE
I'd like to use English instead of the language of the OS

### ISSUE THREAD

**Issue by Griiid** [raspberrypi/rpi-imager#435]
1. English is friendly for most developers, I hope we can have an setting to choose English or the language of the OS.
2. I'm using zh-TW language, but I'm not sure what file name should I use to add an i18n PR for the language.

**Comment by maxnet** [comment]
>English is friendly for most developers, I hope we can have an setting to choose English or the language of the OS.

Try CTRL+SHIFT+L

>I'm using zh-TW language, but I'm not sure what file name should I use to add an i18n PR for the language.

Suspect rpi-imager_zh_TW.ts
But try it first.

**Comment by Griiid** [comment]
Great, Ctrl+Shift+L works!
I'll try to translate, thank you.

**Comment by JereckNET** [comment]
Every time I relaunch Imager, the interface is back to the initial language.
Looks like the choice is not persistent.

Is it a bug or a feature ?

**Comment by lurch** [comment]
> Every time I relaunch Imager, the interface is back to the initial language.
> Looks like the choice is not persistent.

That's expected, the Ctrl+Shift+L option only makes a temporary change. If you want to always run RPi Imager with a different language, you can run it from the command line with e.g. `LANG=fr rpi-imager`
