### ISSUE TITLE
Don't download cache if it leaves very little space left

### ISSUE THREAD

**Issue by mobluse** [raspberrypi/rpi-imager#44]
I think the cache should not be downloaded if you have very little space left. After the cache was downloaded I had only 4 MB left. It might be difficult to reboot after that.

**Comment by maxnet** [comment]
On which operating system?

Were you doing anything else while it was writing (e.g. downloading something else)?
It is supposed to check available disk space at the start of the write, and should only cache if there is 5 GB + size-of-image disk space available.

**Comment by mobluse** [comment]
It was on Raspbian Buster on Raspberry Pi 4B. No, I was not downloading anything else. It seems this 5 GB + size-of-image check doesn't work.

**Comment by Botspot** [comment]
Does anyone know where this tool stores its cache file?

**Comment by maxnet** [comment]
Differs by OS.
Typically somewhere under c:\users\<your user name>\AppData\Local or ~/.cache or ~/Library/Caches

**Comment by qqq89513** [comment]
On my win-10, 
1. Hitt `win` + `R`
2. Type `%appdata%\..\local\Raspberry Pi\Imager\cache`
3. You'll see what you need

**Comment by Danrancan** [comment]
> Differs by OS. Typically somewhere under c:\users\your-username\AppData\Local or ~/.cache or ~/Library/Caches
> 
> AppData folder -like most other system folders- is hidden by default in Windows explorer.

Where are they downloaded on the MacOS version of the app?

**Comment by maxnet** [comment]
> > Differs by OS. Typically somewhere under c:\users\your-username\AppData\Local or ~/.cache or ~/Library/Caches
> > 
> > AppData folder -like most other system folders- is hidden by default in Windows explorer.
> 
> Where are they downloaded on the MacOS version of the app?

Did you check the ~/Library/Caches mentioned?

**Comment by Danrancan** [comment]
> > > Differs by OS. Typically somewhere under c:\users\your-username\AppData\Local or ~/.cache or ~/Library/Caches
> > > AppData folder -like most other system folders- is hidden by default in Windows explorer.
> > 
> > 
> > Where are they downloaded on the MacOS version of the app?
> 
> Did you check the ~/Library/Caches mentioned?

Yes, I couldn't seem to find them there.

**Comment by maxnet** [comment]
>>Did you check the ~/Library/Caches mentioned?

>Yes, I couldn't seem to find them there.

Don't have a "Raspberry Pi/Imager" folder there either?
lastdownload.cache itself may or may not exists, as caching do is disabled automatically when you are low on disk space. But the folder do should exists.

![Screenshot 2023-01-10 at 13 22 57](https://user-images.githubusercontent.com/1123701/211552220-4e11aee5-4a49-4531-afd8-15e520e99279.png)

![Screenshot 2023-01-10 at 13 23 23](https://user-images.githubusercontent.com/1123701/211552237-31f1c478-76a6-4348-8024-0644315704ab.png)

![Screenshot 2023-01-10 at 13 23 42](https://user-images.githubusercontent.com/1123701/211552257-456b8527-7c3b-4764-9496-7c3287005ce1.png)

![Screenshot 2023-01-10 at 13 23 54](https://user-images.githubusercontent.com/1123701/211552268-737b4769-5537-43dd-93a7-f73f7fb478ec.png)

**Comment by ThePythonDev** [comment]
What is the path for Ubuntu Linux?

**Comment by lurch** [comment]
> What is the path for Ubuntu Linux?

Try looking in `~/.cache/Raspberry\ Pi/Imager/`
