### ISSUE TITLE
Feature request - backup utility

### ISSUE THREAD

**Issue by Chick92** [raspberrypi/rpi-imager#440]
Great piece of software!

It would be nice to have a backup utility added. It's not too hard to use dd, but it would just make things a bit easier, especially for new folks.

Cheers!

**Comment by Chick92** [comment]
Still nothing on this?

**Comment by ghollingworth** [comment]
I think we’ve responded in other issues asking for the same functionality that this isn’t something we’re interested in adding to imager

**Comment by Chick92** [comment]
Yeah i've just seen. The underlying problem seems to only relate to windows users though....
