### ISSUE TITLE
It should be possible to see estimated time left

### ISSUE THREAD

**Issue by mobluse** [raspberrypi/rpi-imager#45]
It should be possible to see estimated time left. Then you know when you can return to use the SD card or switch it for the next to be prepared.

**Comment by ghollingworth** [comment]
Estimations of time are very poor for programming SD cards, the SD card speed changes during programming (due to it switching through different types of flash on some cards).

**Comment by lurch** [comment]
...and if doing the "download while writing" thing, I guess the user's internet download speed might be variable too?

**Comment by mobluse** [comment]
The estimated time left would be updated during the download. Bittorrent clients (e.g. Transmission) have this feature and there the speed also varies a lot.
