### ISSUE TITLE
"Advanced options" inaccessible after launching Imager by file association

### ISSUE THREAD

**Issue by kawadakk** [raspberrypi/rpi-imager#451]
We are building a custom OS image that is based on [pi-gen](https://github.com/RPi-Distro/pi-gen). During the testing, we found that the "advanced options" button does not show up after launching Imager by double-clicking an image file. It does though when you launch Imager manually and then choose the image file.

**Comment by lurch** [comment]
Have you got both an old and new version of RPi Imager installed? Maybe launching Imager manually launches the new version, but double-clicking on an image file launches the old version?

**Comment by kawadakk** [comment]
No, the title bar says v1.7.2 in both cases.

**Comment by kawadakk** [comment]
I just tested and it seems this issue can be reproduced with [an official image](https://www.raspberrypi.com/software/operating-systems/) (e.g., https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2022-04-07/2022-04-04-raspios-bullseye-armhf-lite.img.xz), too.

**Comment by lurch** [comment]
Oh yes, there's an `init_format` setting in the http://downloads.raspberrypi.org/os_list_imagingutility_v3.json file read by RPi Imager to determine if the advanced options should be shown, see https://github.com/raspberrypi/rpi-imager/blob/qml/debian/changelog#L20
