### ISSUE TITLE
Feature Request: Multiple WiFi Networks

### ISSUE THREAD

**Issue by makermelissa** [raspberrypi/rpi-imager#452]
I know the Raspberry Pi OS supports multiple WiFi networks by adding more entries to the wpa_supplicant.conf file. It would be cool if multiple networks could be set in the imager and then they are added at imaging time.

**Comment by lurch** [comment]
I'm only guessing (I don't work on this project myself, but I try to be helpful in the issues), but this sounds like such a niche use-case that it'll never get added to RPi Imager? :man_shrugging:

**Comment by tdewey-rpi** [comment]
Rejecting feature request.

While I would _love_ to have this feature for myself, I don't believe it's going to be common-enough of a use case for the typical Raspberry Pi Imager user that we'll explore it in the short term. Never say never, though.

Thanks for the submission, @makermelissa, and I'm happy to review and provide feedback on a PR if you submit one.

**Comment by makermelissa** [comment]
Fair enough. I had kind of forgot about this.
