### ISSUE TITLE
No more option to suppress first run wizard

### ISSUE THREAD

**Issue by harrislapiroff** [raspberrypi/rpi-imager#456]
I noticed this in the release notes:

> Advanced options: remove first run wizard suppression option

Why was this change made, out of curiosity? I would really love to have that option so I don't have to plug a keyboard and mouse in every time I flash my pi.

**Comment by maxnet** [comment]
It is now automatically skipped if you set username/password.

**Comment by lurch** [comment]
...as mentioned at https://www.raspberrypi.com/documentation/computers/getting-started.html#advanced-options
