### ISSUE TITLE
An alarm should sound when it finishes

### ISSUE THREAD

**Issue by mobluse** [raspberrypi/rpi-imager#46]
An alarm should sound when it finishes. This way you could do other things and still switch SD card or use it as soon as it is finished.

**Comment by lurch** [comment]
I guess that would be useful for some people, but other people might find it annoying - so there would probably need to be an option to turn on or off the alarm?

I believe one of the design goals of Raspberry Pi Imager was to have a simple easy-to-use GUI _without_ any options? :man_shrugging:

**Comment by ghollingworth** [comment]
One would assume we can do some kind of OS specific notification which the user can get rid of in their notification settings...

**Comment by pb66** [comment]
I agree a ping or something would be useful, we don't all sit and watch the progress bar.

Perhaps a hidden command line option could be added as suggested in issue #144 for a custom desktop shortcat to offer other options to be set?
