### ISSUE TITLE
Is there a process to include another distribution into RPI imager?

### ISSUE THREAD

**Issue by mgrouch** [raspberrypi/rpi-imager#461]
Let's say I've developed another distribution for pi. Can it be included into default rpi-imager set of distributions?

I'm referring to https://github.com/bareboat-necessities/lysmarine_gen

Thanks,
--MG

**Comment by lurch** [comment]
See e.g. https://github.com/raspberrypi/rpi-imager/issues?q=is%3Aissue+label%3A%22OS+request%22 but note that you need to host the image and also a suitable JSON file.

**Comment by mgrouch** [comment]
Thanks
