### ISSUE TITLE
[OS Request] Bareboat Necessities OS

### ISSUE THREAD

**Issue by mgrouch** [raspberrypi/rpi-imager#462]
Hello,

I'm maintainer of Bareboat Necessities OS. Can you, please, add it under "Other specific-purpose OS"?

https://raw.githubusercontent.com/bareboat-necessities/my-bareboat/master/rpi-imager/rpi-imager-bbn.json

```
// Snippet to include Bareboat Necessities OS Image in Raspberry Pi Imager under
// "Other specific-purpose OS"

{
  "name": "Bareboat Necessities Open-Source Marine Linux OS",
  "description": "Official Raspberry Pi4/400 Image for Bareboat Necessities Open-Source Marine Linux OS.",
  "icon": "https://raw.githubusercontent.com/bareboat-necessities/my-bareboat/master/bareboat-necessities-logo.svg",
  "subitems_url": "https://raw.githubusercontent.com/bareboat-necessities/my-bareboat/master/rpi-imager/rpi-imager-bbn.json"
},

```

Thanks,
--MG

**Comment by ghollingworth** [comment]
Is that size correct?  11GBytes?

**Comment by mgrouch** [comment]
Yes

2.8 in xz. I test all releases with rpi-imager. 
11 in .img

**Comment by tdewey-rpi** [comment]
Please fill out the form to request an addition to the OS list at https://forms.gle/cbsU27aLLVaxUXbw8.
