### ISSUE TITLE
Compress images

### ISSUE THREAD

**Issue by symbios24** [raspberrypi/rpi-imager#467]
Hello

Can you add an option to compress selected/custom images to squashfs format(berryboot) ??

And or to create a multiboot sd card hdd installation (installs berryboot) with the given selected image and converts the image to squashfs after berryboot is installed.

Im probably asking too much
Berryboot is very famous an im wonder why is not supported anymore last version is over a year old,a newer kernel/firmware will help a lot with recent bullseye Oses

Thank you

**Comment by maxnet** [comment]
>Can you add an option to compress selected/custom images to squashfs format(berryboot) ??

Negative.
Cannot read ext4 file systems on Windows/OSX without a lot of effort.

**Comment by symbios24** [comment]
No problem
At least when you have time can you update berryboot kernel/firmware to work correct/better in newer raspbian bullseye operating systems ??

**Comment by symbios24** [comment]
Or create a berryboot automatic installer sh script
So people wont bother you anymore and do it themselves.i know you have more important things than this
Thanks in advance
