### ISSUE TITLE
Error running authopen to gain access to disk device '/dev/rdisk2' on macOS

### ISSUE THREAD

**Issue by seguri** [raspberrypi/rpi-imager#469]
I get this error on macOS 11.6.7, imager 1.7.2
Imager has full disk access.
I tried two different card readers. Unfortunately I have no other uSD cards to try.

<img width="680" alt="Screenshot 2022-08-11 at 15 48 13" src="https://user-images.githubusercontent.com/2405157/184149532-13bfb2b0-ab37-417c-a2c4-8c31c263ffa7.png">

<img width="668" alt="Screenshot 2022-08-11 at 15 48 15" src="https://user-images.githubusercontent.com/2405157/184149564-bc432337-e078-40c7-a033-b01e5a72dcf0.png">

**Comment by maxnet** [comment]
Strange.
If you scroll down the list (so you can see what other entries there are below Google chrome), is there perhaps a second "Raspberry Pi Imager" entry listed there?

As it normally shows up as just "Raspberry Pi Imager" in the list, without the ".app" your entry has:

<img width="684" alt="Screenshot 2022-08-11 at 16 06 46" src="https://user-images.githubusercontent.com/1123701/184153241-53b9174f-2ee8-4196-817e-202ba5782e27.png">

**Comment by seguri** [comment]
Nope, no second entry in any list...

**Comment by maxnet** [comment]
Did it work at any point before? E.g. before an OS X update?
Any (corporate) security software installed?

Can also try removing the existing entries with "-".
If there are no longer entries at all for an app (not any entries for the program with unchecked boxes either), OS X should prompt for permission again when you use Imager.

**Comment by seguri** [comment]
A previous version of the imager was working, unfortunately I don't know which one.
I have corporate security software installed but that hasn't changed, AFAIK.
I removed all entries, the imager asked access for detachable volumes, I granted it, and it failed as before.

**Comment by maxnet** [comment]
If you start a terminal and type: "/usr/libexec/authopen /dev/rdisk2 |hexdump -n 100" it also denies access instead of giving a hexdump?

"diskutil list physical" does show a normal partition layout and returns to shell, and it does not hang while executing?

**Comment by seguri** [comment]
`authopen` requires sudo permissions, and hangs.
`diskutil` shows the following, and hangs.
```
/dev/disk2 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *8.1 GB     disk2
   1:             Windows_FAT_32 boot                    268.4 MB   disk2s1
   2:                      Linux                         7.8 GB     disk2s2
```
tomorrow I'll get a new uSD delivered, and I'll repeat all the tests.

**Comment by maxnet** [comment]
>not sure if diskutil in both tests is really hanging, but what could it be waiting?

No idea, because it always completed instantly for me.
But there did was another user that reported it hanging for an hour, that is why I was curious if it may be related to the issue you are seeing.

https://github.com/raspberrypi/rpi-imager/issues/270#issuecomment-999326993
