### ISSUE TITLE
Show warning before quitting

### ISSUE THREAD

**Issue by dtchanpura** [raspberrypi/rpi-imager#47]
I accidentally closed the window and I had to write the whole thing again. It would be great to have a pop-up message to warn the user before quitting.

**Comment by andrum99** [comment]
Similarly, a confirmation on the 'cancel write' and 'cancel verify' buttons would be useful.

**Comment by lurch** [comment]
We could add a little animated paper-clip? "It looks like you're trying to flash an SD-card..." :rofl: :rofl:

**Comment by andrum99** [comment]
> We could add a little animated paper-clip? "It looks like you're trying to flash an SD-card..." 🤣 🤣

https://www.youtube.com/watch?v=EpWbTogEEhg
