### ISSUE TITLE
Allow Installing openHAB

### ISSUE THREAD

**Issue by Larsen-Locke** [raspberrypi/rpi-imager#472]
It would be great if [openHAB](https://www.openhab.org/) was integrated into Raspberry Imager as an option.
openHAB is one of the most successful and popular non-profit home automation platforms, with a great community and support for more than [200 different technologies and systems](https://www.openhab.org/addons/) and thousands of devices. Furthermore the Raspberry Pi is probably the most common hardware to operate an openHAB server.
I think and hope we did our homework:
- The json-file is available here:
https://github.com/openhab/openhabian/releases/latest/download/rpi-imager-openhab.json
The file is automatically updated with each new release. You can check the procedure [here](https://github.com/openhab/openhabian/pull/1708).
- The snippet for the home automation section in rpi-imager is here:
```
                        { 
                            "name": "openHAB", 
                            "description": "A vendor and technology agnostic open source automation software for your home.", 
                            "icon": "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB2aWV3Qm94PSIwIDAgMzIgMzIiPgoJPGNpcmNsZSBjeD0iMTYiIGN5PSIxNiIgcj0iMTYiIGZpbGw9IiNmZmYiLz4KCTxwYXRoIGZpbGw9IiNlNjRhMTkiIGQ9Im01LjI0MiAyMS4xMzMgOS4zOS05LjM5OEwxNiAxMC4zNjhsMS4zNjcgMS4zNjcgNi45MzMgNi45MzMtLjAxLjAzNS0uMTM3LjQwMi0uMTU2LjM5NC0uMTc0LjM4My0uMTkyLjM3NC0uMTc1LjMwNEwxNiAxMy4xMDMgNi4yNCAyMi44N2MtLjM3Ny0uNTUzLS43MjUtMS4xMjMtLjk5OC0xLjczOHoiLz4KCTxwYXRoIGZpbGw9IiM0NzQ3NDciIGQ9Ik0xNiA0YzYuNjEgMCAxMiA1LjM5IDEyIDEycy01LjM5IDEyLTEyIDEyYy0zLjYxIDAtNi44NTYtMS42MS05LjA1OS00LjE0N2wuNDI0LS40MjUuMzA4LS4zMDguMzA4LS4zMS4zMDktLjMwNy4wMTMtLjAxM0ExMC4wNTcgMTAuMDU3IDAgMCAwIDE2IDI2LjA3N2M1LjU1IDAgMTAuMDc4LTQuNTI2IDEwLjA3OC0xMC4wNzdTMjEuNTUgNS45MjIgMTYgNS45MjJDMTAuNDQ5IDUuOTIyIDUuOTIyIDEwLjQ1IDUuOTIyIDE2YzAgLjc0Ny4wODMgMS40NzYuMjM5IDIuMTc4bC0uNjY4LjY3LS44OTMuODkzQTExLjkyMiAxMS45MjIgMCAwIDEgNCAxNkM0IDkuMzkgOS4zOSA0IDE2IDR6Ii8+Cjwvc3ZnPgo=", 
                            "subitems_url": "https://github.com/openhab/openhabian/releases/latest/download/rpi-imager-openhab.json", 
                            "website": "https://www.openhab.org" 
                        },
```

The icon is integrated as an svg. I hope this is ok for you.
I checked locally with the --repo option:

<img width="341" alt="image" src="https://user-images.githubusercontent.com/78228200/184802515-d9543dcf-1946-4da3-b597-f63a7589b9c6.png">

<img width="341" alt="image" src="https://user-images.githubusercontent.com/78228200/184802550-b9b90ac8-6653-47b1-8150-8e6bbb19d6bb.png">

Please tell me if this is sufficient or anything has to be changed or added.

**Comment by XECDesign** [comment]
That all looks good, thanks!

Added
