### ISSUE TITLE
Underscores are allowed in Raspbian hostnames, but they cause bugs in the actual OS

### ISSUE THREAD

**Issue by manyet1k** [raspberrypi/rpi-imager#474]
![image](https://user-images.githubusercontent.com/65016459/185441945-4d7ee7d6-08a6-4a59-a5b7-2e9ffdad1d8e.png)
In this box, the user can add an underscore '_' to their hostname, but this causes network issues. I believe that _ is not a valid character for a hostname. The program shouldn't let the user save the settings if there is an _, or any other illegal characters, in the textbox.

**Comment by lurch** [comment]
Presumably this is a problem that @spl237 has already had to solve in raspi-config / rc_gui ?

**Comment by spl237** [comment]
One for whoever maintains the imager tool - Floris?

**Comment by andrum99** [comment]
Per the warning in `raspi-config` when you go to change the hostname, underscores in hostnames are not valid. Assuming that is correct, then imager should prevent underscores in hostnames.

**Comment by maxnet** [comment]
>Per the warning in raspi-config when you go to change the hostname, underscores in hostnames are not valid. Assuming that is 
>correct, then imager should prevent underscores in hostnames.

Yes, and probably also the other restrictions on DNS host name per https://www.ietf.org/rfc/rfc1035.txt 
Like 63 character limit for a host name component (label).
