### ISSUE TITLE
Add Repetier-Server image option

### ISSUE THREAD

**Issue by repetier** [raspberrypi/rpi-imager#475]
Repetier-Server is a 3d printer host software similar to Octoprint and Mainsail. It would be great, if you can add our pi image to the 
Other specific purpose OS->3D printing
list. We host it on our own servers and I have already added a json to our server to be included as submenu.

Not sure how you want/need the entry for the 3d printer submenu. When testing stand alone I used this and it worked:
```
{
    "os_list": [
    {
      "name": "Repetier-Server",
      "description": "Multiple 3d printer management solution for Raspberry Pi. ",
      "website": "https://www.repetier-server.com/download-images/",
      "icon": "https://download4.repetier.com/files/server/images/repetierserver40.png",
      "subitems_url": "https://download4.repetier.com/files/server/images/Repetier-Server.json"       
    }
    ]
}
```

Guess you just need to add the os_list entry in your existing list.

If you need anything else or require changes, please let me know.

**Comment by lurch** [comment]
Please fill out the OS addition request form at https://forms.gle/35ESMTmyST4kHAdT7
