### ISSUE TITLE
Image URL outdated for Ubuntu Server 20.04

### ISSUE THREAD

**Issue by ohmdelta** [raspberrypi/rpi-imager#478]
Image URL http://cdimage.ubuntu.com/releases/focal/release/ubuntu-20.04.4-preinstalled-server-arm64+raspi.img.xz no longer exists - should be http://cdimage.ubuntu.com/releases/focal/release/ubuntu-20.04.5-preinstalled-server-arm64+raspi.img.xz

**Comment by lurch** [comment]
See https://github.com/raspberrypi/rpi-imager/issues/405#issuecomment-1234512867
