### ISSUE TITLE
[Feature Request] macOS arm64 Support

### ISSUE THREAD

**Issue by robd003** [raspberrypi/rpi-imager#487]
I noticed that rpi-imager doesn't support Apple SIlicon natively. Considering that we're almost 3 years since the launch of Apple Silicon could we get a build available for it?

My office has replaced all of the old Intel Macs with new Apple Silicon Macs this year.

Having both a x86_64 build (for legacy systems) and an arm64 build would be fantastic.

**Comment by lurch** [comment]
See #353

**Comment by ghollingworth** [comment]
Currently, the downloads from M1 Macs are only 0.1% of the total downloads, this is not enough to warrant including a new build.  You can still use the x86 version with Rosetta anyway

**Comment by infinitepower18** [comment]
Are you still going to stick to your stance of not supporting Apple Silicon when Apple eventually removes Rosetta, just like they did with the PowerPC transition?

**Comment by ghollingworth** [comment]
The original Rosetta sounds like it lasted for seven to eight years...  By then I'm sure the platform will have a lot more users, but at the moment 0.1% is not enough.

**Comment by asyba** [comment]
> Currently, the downloads from M1 Macs are only 0.1% of the total downloads, this is not enough to warrant including a new build. You can still use the x86 version with Rosetta anyway

because ppl first check if Raspberry Pi Imager is compatible with M1 mac on google and when they found out that is not, they don't event ry to download  the app, so measuring 0.1% downloads is not a good tool ... lol
