### ISSUE TITLE
Please allow "init_format" to be specified in "Advanced Settings" when "Use Custom" OS image is selected.

### ISSUE THREAD

**Issue by JinShil** [raspberrypi/rpi-imager#494]
I am using a custom OS image based on Raspberry Pi OS, with just a few minor changes.  I flash Raspberry Pi devices with this image using the "Use Custom" option.  I need the system to boot and run the `firstrun` script just like the original Raspberry Pi OS images, but the imager only creates the `user-data` file for cloud-init instead of the `firstrun` script.

According to https://github.com/raspberrypi/rpi-imager/blob/957c78f8a3187ec788ac737de87eded508e7c9ef/doc/json-schema/os-list-schema.json#L295 it seems this is due to the fact that the `init_format` is not `systemd`.  Looking at https://github.com/raspberrypi/rpi-imager/blob/6861a2aa1637a1c3b2741a4c92b9f5c8f598f6ab/src/main.qml#L509 I can see that `init_format` is blank, which I believe is causing the issue.  I need it to be `systemd`

Since I suppose custom OS images could require either `systemd` or `cloud-init`, I think the user should be allowed to specify the `init_format` in the "Advanced Settings", but currently, such an option does not exist.  Could it be added?

**Comment by maxnet** [comment]
If it is not an image from the repository, it will use heuristics to guess what init format should be used, which favors cloud-init if in doubt.


Is it your own custom OS you are writing, or a third party .img?

If your own, you can trick Imager into thinking it's a RPI OS based OS for which systemd method should be used by creating a file called issue.txt on the FAT partition inside the image, and mentioning the word "pi-gen" in it.

**Comment by JinShil** [comment]
> If your own, you can trick Imager into thinking it's a RPI OS based OS for which systemd method should be used by creating a file called issue.txt on the FAT partition inside the image, and mentioning the word "pi-gen" in it.

Thank you.  I tried that.  It works on Linux but not on Windows.  I bet this is related to https://github.com/raspberrypi/rpi-imager/issues/445

**Comment by maxnet** [comment]
>It works in Linux but not in Windows. I bet this is related to https://github.com/raspberrypi/rpi-imager/issues/445

M1Screw mentioned there he had an issue when using one SD card reader, but not with another SD card reader.

Are you using the exact same external USB SD card readers on both Linux and Windows?

**Comment by JinShil** [comment]
> Are you using the exact same external USB SD card readers on both Linux and Windows?

Yes, I'm using a the same USB SD card reader for both Linux and Windows.

**Comment by JinShil** [comment]
I've spend the day trying to create a reproduction procedure for this and I'm getting inconsistent results.  Sometimes I can get the fristboot.sh to be created on Windows, and sometimes I can't.  I'm closing this until I can determine the issue with more certainty.

**Comment by lurch** [comment]
Might be worth trying a different SD card-reader on Windows, if you haven't already?

**Comment by maxnet** [comment]
>I've spend the day trying to create a reproduction procedure for this and I'm getting inconsistent results. Sometimes I can get the fristboot.sh to be created on Windows, and sometimes I can't.

Is it also reproducible at all, if you uncheck "eject media when finished" in Imager's advanced settings, and look at the FAT partition right after writing, without removing/re-inserting card?

**Comment by JinShil** [comment]
> Is it also reproducible at all, if you uncheck "eject media when finished" in Imager's advanced settings

Yes, I've had the "eject media when finished" option unchecked in all of my testing since the very beginning.
