### ISSUE TITLE
Raspberry pi  3b failed to boot with advanced settings.

### ISSUE THREAD

**Issue by flynnwang** [raspberrypi/rpi-imager#498]
The new installation failed to boot when using the raspberry pi imager to install a new version of raspberry OS (bullseye) with advanced settings (hostname, username/password, WiFi SSID/password, ssh, language). After reinstalling the pi imager and installing the raspberry OS with no advanced settings, the issue was solved. 

* raspberry pi: 3b
* pi imager: v1.7.3
* pi imager is running on: macOS Monterey, Apple M1 Pro
* raspberry OS: bullseye (both lite and desktop)

![20221030-173724](https://user-images.githubusercontent.com/1442332/198872031-5800f7d4-9052-498f-8ee7-b2bcfd229091.jpeg)

**Comment by maxnet** [comment]
Do you have a wifi SSID with an ' in it?

**Comment by flynnwang** [comment]
> SSID

Yes, also set the Wifi SSID and its password.

**Comment by maxnet** [comment]
>Yes, also set the Wifi SSID and its password.

What does your SSID look like?

Only normal characters (ABCD1234) or also special characters (like single quotes ' )?

**Comment by flynnwang** [comment]
> > Yes, also set the Wifi SSID and its password.
> 
> What does your SSID look like?
> 
> Only normal characters (ABCD1234) or also special characters (like single quotes ' )?

Mine is like: "Wang's WiFi"

**Comment by maxnet** [comment]
Duplicate of #499
(Fixed in git, but not yet in release)

**Comment by flynnwang** [comment]
Good to know :)
