### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by roontoon** [raspberrypi/rpi-imager#500]
I would love to see a SD cloning feature in RPI-Imager. Thanks

**Comment by lurch** [comment]
There's the "SD card copier" in Raspberry Pi OS, which _might_ do what you want? https://www.raspberrypi.com/news/another-update-raspbian/

**Comment by roontoon** [comment]
Needs to run on a Mac. But it would still be a great feature for the app. Cheers.

**Comment by tdewey-rpi** [comment]
I'm sorry, roontoon, but we don't have plans to introduce a direct SD card copying feature. If you're looking to image multiple cards for Raspberry Pi devices, you could issue multiple writes via the Imager.

Closing, as this isn't something we're looking at.
