### ISSUE TITLE
Enable Network Manager 

### ISSUE THREAD

**Issue by CharlesGodwin** [raspberrypi/rpi-imager#504]
Can you add an option to enable Network Manager instead of dhcpd?

Thanks

**Comment by maxnet** [comment]
Not sure if there is much demand for that.

Do you have a special network environment, in which dhcpcd would not work at all?

**Comment by ghollingworth** [comment]
Plus the next release of the image network manager will become default anyway

**Comment by CharlesGodwin** [comment]
@maxnet I was looking to the future and wanted to be able to jump start. But, since @ghollingworth says it's in the next iteration of images, then the future is here.

I'm closing the issue.
Thanks for the feedback.
