### ISSUE TITLE
Unable to customize. File 'F:/config.txt' does not exist

### ISSUE THREAD

**Issue by Zilverdael80** [raspberrypi/rpi-imager#506]
Trying to create a SD card to boot USB. 
Using version 1.7.3
Writing and Verifying goes with no issue it seems, 
![1](https://user-images.githubusercontent.com/116879022/203067367-441d8be8-b638-49e6-9746-e8f22a8d010d.jpg)

Windows re-mounts the SD card as drive F: 
Imagers fails out, Unable to customize. File 'F:/config.txt' does not exist
![Clipboard04](https://user-images.githubusercontent.com/116879022/203067464-2af69e21-1da3-48ab-9f70-fefd0fc1801a.jpg)

File indeed is not on the drive, also not after re-mounting the drive in windows. 

I dont know what should be in this file, so basically i'm stuck now as i want to boot from USB and not SD.

**Comment by maxnet** [comment]
Not sure why it is trying to apply advanced settings to the EEPROM image, which does not support that.

Did you write any other images before the EEPROM image in the same session?
If so, does it work better if you close Imager, and start it again, and write only the EEPROM image?

**Comment by Zilverdael80** [comment]
That indeed fixed the issue, 
i wrote a home assistant OS image to USB drive and then started the SD write to boot from USB. 
Restarting the imager 'fixed' the issue

**Comment by foghcz** [comment]
I'm having the same issue on MacOS

**Comment by DanGlChris** [comment]
Yesterday, I had the same problem with different os files that I'd tried to boot on a sd card for a raspberry pi. 
I've solved it today just by unchecking all parameter here. And It works!!!


![image](https://user-images.githubusercontent.com/49105704/227713893-65d8b927-2343-43d3-b35f-3d617b81a84d.png)

**Comment by maxnet** [comment]
>Yesterday, I had the same problem with different os files that I'd tried to boot on a sd card for a raspberry pi.
>I've solved it today just by unchecking all parameter here. And It works!!!

If you do not customize any setting, it indeed has no need to alter the files on the FAT partition.
Alternatively, you may want to try a newer Imager version. 1.7.2 is old.
