### ISSUE TITLE
Build for MAGEIA LINUX

### ISSUE THREAD

**Issue by iamjlm** [raspberrypi/rpi-imager#522]
Please be informed that I compiled & tested successfully rpi-imager for MAGEIA 8:

Get dependencies:
---------------------------

urpmi git gcc gcc-c++ make cmake libarchive-devel libcurl-devel openssl-devel qtbase5-common-devel lib64qt5help-devel lib64qt5core-devel lib64qt5svg-devel lib64qt5quick-devel lib64qt5help-devel libqt5concurrent-devel

Get the sources:
------------------------
identical to FEDORA

Building:
---------

Small change: use "su" + root password, instead of "sudo"

cd rpi-imager
mkdir -p build
cd build
cmake ../src
make
su
	make install

Feel free to add this to the read.me file.

**Comment by tdewey-rpi** [comment]
Thanks for the note. I'm not looking to expand the readme to further development operating systems at this time, but I'm very glad to hear it worked for you.
