### ISSUE TITLE
Error downloading OS list from Internet

### ISSUE THREAD

**Issue by krish7129** [raspberrypi/rpi-imager#526]
Getting the above error when trying to download Ubuntu os on Raspberr Pi Imager v1.7.3. Tried this on 2 different pcs and same issue
![image](https://user-images.githubusercontent.com/17689892/209442677-2b671438-0f2f-4d01-ac4d-61f15c277d97.png)

**Comment by maxnet** [comment]
@waveform80 


Seems changelogs.ubuntu.com that hosts Ubuntu's list of Imager images is pretty much down:


503 Service Unavailable

No server is available to handle this request.

**Comment by lurch** [comment]
changelogs.ubuntu.com seems to be back up again? (26th December 2022)
Would you like to re-test @krish7129 ?
