### ISSUE TITLE
Feature Request: expose 'DRIVELIST_FILTER_SYSTEM_DRIVES' as a cmake var

### ISSUE THREAD

**Issue by MrSmoer** [raspberrypi/rpi-imager#534]
I personally use rpi-imager with `DRIVELIST_FILTER_SYSTEM_DRIVES` in config.h set to false, because I need to write to SATA drives, so I was wondering whether it would be beneficial to expose it as a cmake arg.

I already created a [commit in my fork](https://github.com/MrSmoer/rpi-imager/commit/4074bcab2fd007b1845ae0d0b97578d08c22410c), should I open a PR? 

What do you think?
Thank you, have a nice day!

**Comment by tdewey-rpi** [comment]
Hi @MrSmoer,

Please open a PR. I'd be happy to accept this change, provided it operates in the existing mode by default.

**Comment by tdewey-rpi** [comment]
Holding this issue open to tie to the PR.
