### ISSUE TITLE
Imager offers Time Machine backup disk

### ISSUE THREAD

**Issue by teschlg** [raspberrypi/rpi-imager#54]
Not sure this is a bug, but the Imager will offer my Time Machine backup disk as an SD Card available for writing the image (with a niche SD card icon next to it). Maybe it could save some troubles if the tool would detect this. Anyway, thanks for the nice tool!

**Comment by lurch** [comment]
Duplicate of #43 ?

**Comment by teschlg** [comment]
Indeed.
