### ISSUE TITLE
SD Card Unable To Be Read After Verifying

### ISSUE THREAD

**Issue by TAM-Monke** [raspberrypi/rpi-imager#544]
So I have a 2019 MacBook Pro On macOS 13.2 Ventura. I have been trying to flash Debian onto my sd card but after it verifies the imager says completed but my computer says cannot read volume. Please help.

**Comment by maxnet** [comment]
>I have been trying to flash Debian onto my sd card but after it verifies the imager says completed but my computer says cannot read volume. 

Please be very specific about what image you are using, where that image came from, and what the exact wording of the  error message you got is.

With "Debian" do you mean that you selected "Raspberry Pi OS (32-bit)" from our repository?

Or do you mean: you went to the Debian website, downloaded some image file there, selected "Use custom image" in Imager, and got the following error message after write:

![Screenshot 2023-01-26 at 18 18 42](https://user-images.githubusercontent.com/1123701/214907026-e740ac77-f428-44a8-88ad-9d3bbe32e167.png)

That should NOT happen if the image you are trying to write is meant for the Raspberry Pi.
As those always have at least a FAT partition, and OS X do can read FAT partitions.
But it do can happen if you accidentally are trying to use an image that is NOT for the Raspberry Pi, but for normal Intel computers.
It is possible that those images only have partitions that use file formats like ext4 that OS X does not understand, and that do can trigger the message from the screenshot.

**Comment by TAM-Monke** [comment]
I used the armhf iso file from here https://www.debian.org/distrib/netinst

**Comment by TAM-Monke** [comment]
I got the same error in that picture. I tried it with Imager 1.7.3 and then 1.6.1 and it still didn’t work?

**Comment by TAM-Monke** [comment]
> I got the same error in that picture. I tried it with Imager 1.7.3 and then 1.6.1 and it still didn’t work?

Oops I meant to put a .

**Comment by maxnet** [comment]
>I used the armhf iso file from here https://www.debian.org/distrib/netinst

On a Raspberry Pi or on a competing board?

Think that is for other ARM boards than the Raspberry Pi...
Upstream Debian has a history of refusing to bundle propitiatory firmware files with their official releases, and the Pi does need those to boot...

Try a semi-official Pi specific release from: https://raspi.debian.net/tested-images/ instead.

**Comment by TAM-Monke** [comment]
Ok I’ll try that

**Comment by TAM-Monke** [comment]
> 

This might sound stupid but will something for 1b work on 1b+

**Comment by maxnet** [comment]
>This might sound stupid but will something for 1b work on 1b+

Would expect their "family 1" images to work on Pi zero, 1b, 1b+.
But have NOT tried it.

**Comment by TAM-Monke** [comment]
> > This might sound stupid but will something for 1b work on 1b+
> 
> Would expect their "family 1" images to work on Pi zero, 1b, 1b+. But have NOT tried it.

Thanks

**Comment by TAM-Monke** [comment]
Is it normal to go faster and slower as it writes

**Comment by TAM-Monke** [comment]
> Is it normal to go faster and slower as it writes

*For It

**Comment by maxnet** [comment]
>Is it normal to go faster and slower as it writes

With custom .xz images, yes.
Related to #480

**Comment by TAM-Monke** [comment]
> > Is it normal to go faster and slower as it writes
> 
> With custom .xz images, yes. Related to #480

alright it's soon gonna be verifying

**Comment by TAM-Monke** [comment]
it's now just hanging on writing 99%

**Comment by TAM-Monke** [comment]
or not

**Comment by TAM-Monke** [comment]
moment of truth

**Comment by TAM-Monke** [comment]
will it work

**Comment by TAM-Monke** [comment]
IT WORKED!!!! Thanks so much!!
