### ISSUE TITLE
How to get an OS listed in the RPi Imaging program

### ISSUE THREAD

**Issue by Poporacer** [raspberrypi/rpi-imager#545]
I could not find any documentation on how to include an OS into the RPi Imager program?
What is required and what is the process?

**Comment by XECDesign** [comment]
If you're the developer of the distro, you'd need to open an issue.

https://github.com/raspberrypi/rpi-imager/issues?q=label%3A"OS+request"

Include the json file snippet you would like included in https://downloads.raspberrypi.org/os_list_imagingutility_v3.json

The `subitems_url` field needs to point to an official server.

The distro needs to differentiate itself from what's already offered. For example, it can't be "Raspberry Pi OS, but I've installed some stuff I like".

**Comment by macmpi** [comment]
Is there some sort of baseline how-to doc for repo maintainers to describe the various requirements & settings options to craft necessary image and .json files?
- is image format mandatory, which form (i.e, is a simple directory archive also ok with rpi-imager creating FAT partition on its own)?
- which .json keywords are mandatory/optional
- what does init-format option does; which are acceptable values
- ...

Maybe a recommendation (enforcement?) [to not label boot partition as `boot`](https://github.com/RPi-Distro/pi-gen/issues/669) could take place in-there too :wink:

Thanks for consideration.

**Comment by tdewey-rpi** [comment]
Please fill out the form to request an addition to the OS list at https://forms.gle/cbsU27aLLVaxUXbw8.
