### ISSUE TITLE
Error writing to storage on Rpi imager v1.7.4 [Solved]

### ISSUE THREAD

**Issue by Jasoniver** [raspberrypi/rpi-imager#570]
Error writing to storage on Rpi imager v1.7.4, trying to install Mainsail from the drop downlist, it gets to 87% and then give the error writing to storage as seen below

[Solved] Turns out it was my SD Card reader that didnt like my usb 3.1 port, bought a new reader and working fine now

![image](https://user-images.githubusercontent.com/100423274/227621663-ee3627a1-66e7-4782-a1d9-1c2e1ed5b3fd.png)
![Screenshot 2023-03-24 213020](https://user-images.githubusercontent.com/100423274/227622088-c58a975f-da7e-4239-b57b-93433fe5fe67.png)

**Comment by maxnet** [comment]
Tried a different SD card reader + card?

**Comment by Jasoniver** [comment]
i have tried a different SD card but dont have another sd card reader
might go buy a reader tomorrow any suggestions?

i have read on some old posts about using a usb2.0 port works, any comments on that?

**Comment by maxnet** [comment]
If the card reader has buggy firmware that does not get along with USB 3, a port that only support 2 may help.

If you get another reader, I do would get an USB 3 reader, though.
Not because the transfer speed makes much difference, but because the USB 3 readers tend to have newer chipsets inside.

**Comment by Jasoniver** [comment]
Turns out it was my SD Card reader that didnt like my usb 3.1 port, bought a new reader and working fine now
