### ISSUE TITLE
RPI imager ssh and password linked, when they should be

### ISSUE THREAD

**Issue by dave-watts** [raspberrypi/rpi-imager#576]
To enable a kiosk application the raspberry should not ask for a password on startup. However this does not mean that it should not  have a ssh setup with a username/password if required, they are not mutually exclusive. But in the imager, choosing the ssh option in the settings dialog also enables the password option, which causes it to prompt for a password on startup. 

I realize this is possible to do on the pi itself, but I think the imager should take care of it in its options. 

Cheers

Dave

**Comment by ghollingworth** [comment]
The Raspberry Pi OS is not for a kiosk application.  If you want to do that, I'd suggest using something like FullPageOS

**Comment by dave-watts** [comment]
The great thing about the raspberry pi is that it can be used for whatever you want to use it for. 
There are no rules like "The Raspberry Pi OS is not for a kiosk application".

**Comment by maxnet** [comment]
>But in the imager, choosing the ssh option in the settings dialog also enables the password option, which causes it to 
>prompt for a password on startup.

RPI OS will nag you to set a password on first boot if you have NOT set a password in Imager.
That is unrelated to whether or not you have selected the SSH option.
