### ISSUE TITLE
Move Raspberry Pi OS (64-bit) to main page

### ISSUE THREAD

**Issue by theofficialgman** [raspberrypi/rpi-imager#577]
Raspberry Pi OS (32-bit) is still the recommended image and it has the most downloads according to your download statistics.

Raspberry Pi OS (64-bit) is the second most downloaded image and users have to search through the "other" category in order to even find it (by expanding the page/scrolling). This should be changed so that it is found on the main page alongside the 32-bit image or replace the 32-bit image on the main page.

![image](https://user-images.githubusercontent.com/28281419/231562887-b1400b48-e86e-43fa-a61e-fe74086c4f3f.png)
![image2](https://user-images.githubusercontent.com/28281419/231562899-21020952-5fa0-4480-b176-572fc057b107.png)

**Comment by 0lzi** [comment]
https://downloads.raspberrypi.org/os_list_imagingutility_v3.json

This is where the change would need to be made looking at the [src/config.h](https://github.com/raspberrypi/rpi-imager/blob/qml/src/config.h)

**Comment by colinwang1703** [comment]
> https://downloads.raspberrypi.org/os_list_imagingutility_v3.json
> 
> This is where the change would need to be made looking at the [src/config.h](https://github.com/raspberrypi/rpi-imager/blob/qml/src/config.h)

But it's still better to default.

**Comment by 0lzi** [comment]
> > https://downloads.raspberrypi.org/os_list_imagingutility_v3.json
> > This is where the change would need to be made looking at the [src/config.h](https://github.com/raspberrypi/rpi-imager/blob/qml/src/config.h)
> 
> But it's still better to default.

Agreed, 64bit should be the default

**Comment by ghollingworth** [comment]
Sorry, wrong button, but as I say this is 'in the works'

**Comment by theofficialgman** [comment]
I don't see why its taking months to do.
You could have put it on the main page right below the recommended in two mintues with a tiny change to the json (or update more likely your CI that updates the json automatically).

It is criminal for it to be hidden away in the "other" category.

**Comment by theofficialgman** [comment]
hoping this can be changed as soon as possible now that bookworm has released.

we would not want the majority of users to install a 32bit image again in their Pi4 and Pi5 when a 64bit image is objectively better for these systems when configured with enough ram (4GB+) to take advantage of 64bit's extended ram address space.

**Comment by lurch** [comment]
It's in the works, see #645

**Comment by tdewey-rpi** [comment]
Bookworm 64bit is now shown at the top of the hierarchy for platforms that can run it. 

![Screenshot 2023-10-19 213451](https://github.com/raspberrypi/rpi-imager/assets/146750643/c52aeb86-418e-4ec6-a8ad-9a7f4844db5d)

**Comment by theofficialgman** [comment]
@tdewey-rpi I'll give you the benefit of the doubt that these issues were not intended and did not happen in testing but right now pretty much everything is very broken https://github.com/raspberrypi/rpi-imager/issues/577
