### ISSUE TITLE
Will rpi-imager save the firmware written to the sd card?

### ISSUE THREAD

**Issue by Kay-Anonymous** [raspberrypi/rpi-imager#579]
Hello, gurus.
Will rpi-imager save the firmware written to the sd card?
If yes, where are these images stored?

**Comment by Kay-Anonymous** [comment]
I installed version 1.7.3 on ubuntu20.04, and I did not find the lastdownload.cache file. But it looks like there is plenty of disk space

**Comment by maxnet** [comment]
Does exists for me under (K)Ubuntu:

```
max@lynx:~$ ls -l ~/.cache/Raspberry\ Pi/Imager/lastdownload.cache 
-rw-rw-r-- 1 max max 795265696 Apr  9 18:35 '/home/max/.cache/Raspberry Pi/Imager/lastdownload.cache'
```

**Comment by Kay-Anonymous** [comment]
Well, maybe my previous writes are not cached, I will download a copy directly, thank you ～
```bash
$ ll ~/.cache/Raspberry\ Pi/Imager/
oslistcache0/ oslistcache1/ qmlcache/  
```
