### ISSUE TITLE
Latest release not linked on main web page

### ISSUE THREAD

**Issue by dsl101** [raspberrypi/rpi-imager#580]
I know this isn't necessarily an issue with the imager itself, but for ages I was stuck because the download link [here](https://www.raspberrypi.com/software/) which is `https://downloads.raspberrypi.org/imager/imager_latest.exe` is pointing to version 1.6.2, which is missing some significant functionality (like the customisation options). Eventually I found this repo and the releases, and got 1.7.4.

Note the other platform links are also outdated—1.7 for MacOS and 1.6.1 for Ubuntu.

**Comment by XECDesign** [comment]
Many thanks for spotting and reporting this. Looks like the script that generates the redirects doesn't sort the files properly.

I've fixed the links manually for now and will take a look at making sure they get generated properly next time.

**Comment by XECDesign** [comment]
Should be sorted so that it doesn't happen again.
