### ISSUE TITLE
v1.7.4: Wifi settings & Locale not configured properly when network name contains '$'

### ISSUE THREAD

**Issue by rrrus** [raspberrypi/rpi-imager#581]
WiFi network name containing `$` does not get configured properly.  The `$` symbol is mis-interpreted as a variable name prefix in `firstrun.sh`.  Network name `$240` ends up as `40` in wpa_supplicant.conf.

**Comment by lurch** [comment]
I guess this is _vaguely_ similar to #486

**Comment by maxnet** [comment]
>I guess this is vaguely similar to #486

Not sure if it is a problem in Imager code this time.

Note that we enclose the parameters by single quotes in escapeshellarg().
And shells do not typically do anything with $ in that case.

```
$ echo '$240'
$240
```

May be a problem in RPI OS' scripts.

**Comment by cillian64** [comment]
I've just tested with imager 1.8.0 and Pi-OS bookworm and this works fine, happily connected to a wifi network with a `$` in the SSID.

**Comment by rrrus** [comment]
Thank you!
