### ISSUE TITLE
Apple Silicon (M1/M2) - Testing Plan?

### ISSUE THREAD

**Issue by yaakov-h** [raspberrypi/rpi-imager#582]
The Intel build of the imager is horrendously slow at writing to the SD card on arm64 macOS.

The Universal build of the imager runs at normal speed, but is not officially released.

The release notes state:

>  is an universal build for both Intel and Apple M1/M2 architectures. It requires at least OS X 10.14 and has only been tested on Intel and M2 Mac Mini. **This software has currently NOT been tested on M1 hardware, nor on Macbooks, and will not be officially released, until this is the case.** Use at your own risk.

What does it take to officially test this and release this version of the software?

I have run this on both my M1 MacBook Pro and M2Pro MacBook Pro and had absolutely no issues with it.

**Comment by tdewey-rpi** [comment]
Release v1.8.1 should address your concerns. Closing.
