### ISSUE TITLE
Unsupported ZIP Extraction Error

### ISSUE THREAD

**Issue by Gramaz** [raspberrypi/rpi-imager#586]
On 1.7.4.1, I cannot extract officially downloaded image files or use the "custom" file either - every time it results in an error in extracting.

**Comment by maxnet** [comment]
What operating system are you running Imager on?

The libarchive version that handles uncompression did get updated on  1.7.4.1 if using Windows or MacOS.
(On Linux we use the libarchive that comes with your Linux distribution, so version used may vary).
None of the alpha testers reported this problem, though.

And what exact image file are you using?
(You mention .zip and the official images. But the recent RPI OS images are .xz, not .zip.)

**Comment by maxnet** [comment]
>Same issue here.

While writing which OS image?

**Comment by maxnet** [comment]
Can you test if this build solves the problem?

[imager-1.7.5-zipfix.exe](https://www.maxnet.eu/tmp/175-zipfix/imager-1.7.5.exe)

**Comment by ray1025** [comment]
> Can you test if this build solves the problem?
> 
> [imager-1.7.5-zipfix.exe](https://www.maxnet.eu/tmp/175-zipfix/imager-1.7.5.exe)

Yes,it's solves the problem.

**Comment by digitalsleuth** [comment]
Same issue here, the 1.7.5 zipfix resolved the issue for me as well.

**Comment by maxnet** [comment]
Fixed in 1.7.5

**Comment by FreeDMR-Digital-Network** [comment]
for me the 1.7.5 does not work, still zip error (Win7, zip, error: 9 deflation 64bit

**Comment by FreeDMR-Digital-Network** [comment]
for me the 1.7.5 does not work, still zip error (Win7, zip, error: 9 deflation 64bit

**Comment by maxnet** [comment]
> for me the 1.7.5 does not work, still zip error (Win7, zip, error: 9 deflation 64bit

Proprietary zip flavors are indeed not supported.

https://www.zlib.net/zlib_faq.html#faq40
