### ISSUE TITLE
Live-ISO containing rpi-imager ?

### ISSUE THREAD

**Issue by alexbenisch** [raspberrypi/rpi-imager#590]
I installed home assistant on a x86-64 device. The practice is to start an Ubuntu live iso, install balena-etcher, flash the haos img to the M2 SSD and boot. I tried Rpi-imager but lost patience with dependency errors. Now it boots from SSD into hassio. 

My question:
Is there a Live-ISO containing rpi-imager or is there a ppa to add containing all the dependencies?
Or what do you think about an integration into ventoy as a plugin.

**Comment by ghollingworth** [comment]
You'd have to ask the Ubuntu devs about that...
