### ISSUE TITLE
Off Topic

### ISSUE THREAD

**Issue by actraiser30** [raspberrypi/rpi-imager#599]
Hello Maxnet i hope you dont mind posting here this

i was wondering if you can give me your berryboot github page in case that project is abandoned or you dont have time for this etc.

I dont know for sure how to do commits and other stuff but im willing to learn, i have made a partial berryboot update,i updated everything except the kernel its not possible since the build fails every time.

im very interesting about improving berryboot and the project in general has many potential 

thanks in advance

**Comment by maxnet** [comment]
>i was wondering if you can give me your berryboot github page

No, sorry.


And Berryboot has nothing to do with Imager.
So closing this.

**Comment by actraiser30** [comment]
> > i was wondering if you can give me your berryboot github page
> 
> No, sorry.
> 
> And Berryboot has nothing to do with Imager. So closing this.

i know it has nothing to do i just did not know if you will see it if i post in berryboot,at least can you tell me if you will update the berryboot code/instructions etc so the build wont fail anymore?

thanks
