### ISSUE TITLE
Doesn't redraw if window moved

### ISSUE THREAD

**Issue by kaihendry** [raspberrypi/rpi-imager#60]
<img src="https://s.natalian.org/2020-05-08/1588896122_2560x1440.png">

I'm using Arch btw with the current package of https://aur.archlinux.org/packages/rpi-imager/

**Comment by lurch** [comment]
Are you using a non-standard window-manager?

**Comment by kaihendry** [comment]
https://en.wikipedia.org/wiki/Dwm ... the standard tiling one

**Comment by lurch** [comment]
I've never used a tiling wm myself, but perhaps the GUI used by RPi Imager isn't "compatible" with tiling window managers? :man_shrugging: 
(I should also clarify that I'm not the RPi Imager developer, so I apologise for any incorrect comments / guesses!)

**Comment by tdewey-rpi** [comment]
Closing as stale. Please raise a new issue if you see this wiht the current release.
