### ISSUE TITLE
Error during verification for fedora server 38.

### ISSUE THREAD

**Issue by LOLwierd** [raspberrypi/rpi-imager#602]
Constantly getting MBR invalid signature error during verification while writing Fedora server 38 to my SD card.

Using RPI Imager v1.7.5 on Windows 10.

**Comment by johnyc90** [comment]
I'm having exactly the same error creating an image using RPI-Imager v1.7.5 on Fedora 38. Not sure the error comes from rpi-imager or the fedora image.

**Comment by maxnet** [comment]
Please be very specific about the image you are using.
You do are using their aarch64 *RAW* image, and not the ISO (which is NOT for the Pi, but for other ARM devices)?

**Comment by johnyc90** [comment]
@maxnet you're absolutely right... I've used the iso. Downloading the raw image right now.

**Comment by johnyc90** [comment]
Worked for me! thanks @maxnet

**Comment by maxnet** [comment]
Good to hear, it works now.

I am using the topic starter (@LOLwierd) had the same problem, and am closing this.
If not, just re-open.
