### ISSUE TITLE
Feature request: arm/arm64/aarch64 linux packages (.debs)

### ISSUE THREAD

**Issue by docgalaxyblock** [raspberrypi/rpi-imager#604]
Hello guys,
I am currently switching to a RK3588 based desktop and would love to see arm and aarch64 .debs in future releases.
I could not find an existing issue regarding this topic

*My current workaround is to wget the latest debs from the [pi repo](https://archive.raspberrypi.org/debian/pool/main/r/rpi-imager)*

<br>

EDIT:
<br>
## The TL;DR Solution:

If you want arm/arm64/aarch64 debs download them from https://archive.raspberrypi.org/debian/pool/main/r/rpi-imager
(only officially support on the official PiOS)

**Comment by ghollingworth** [comment]
Methinks you've solved your own issue...  What more do you think you need other than the latest debs?

**Comment by docgalaxyblock** [comment]
Nopr
I asked to include arm debs in future releases (in the releases section).

**Comment by ghollingworth** [comment]
That's not where they are built and released from, they are released from the Raspberry Pi repository.  Which is why that is the canonical place to download it from.

**Comment by docgalaxyblock** [comment]
Ok so on every release maxnet grabs the .debs from the pi repo and releases them at github? - Why not just copying the other debs in the future too.

Is `wget` them out of the pi repo now the recommend way of getting the debs?
*If so I will edit this issue that others can find it and then follow the link*



Sidequestion: How about Windows arm versions?
Would a user need to compile the qt tools (since no arm builds are available) and then build rpi-imager?

**Comment by ghollingworth** [comment]
No @maxnet does not create the .deb, that is done by the Raspberry Pi team once @maxnet has released a new version. 

There is currently no Windows ARM version of Imager, although I would assume the x86 version will run through some emulation-type capability of that operating system.

It should be understood that this application was specifically developed to give our customers an easier time locating, downloading and installing the operating system for Raspberry Pi products.  We have therefore only supported the majority operating systems, (MacOS and Windows).  It also supports running it from network install (power off your Pi 4, plug in a keyboard, Ethernet and power it back on...  Follow the prompts and insert your media (SD card, USB, NVME) when asked...

Gordon (CTO Software, Raspberry Pi Trading Limited)

**Comment by docgalaxyblock** [comment]
I think you have misunderstood what I mean a bit. I try it again and this is hopufully the last questions.

- OK @maxnet releases a new version (does this happens here at github or internally at Raspberry Pi?)
- Then the Pi team builds everything

And now the question: every github-release has assets attached to it. When and who attaches them?
If they are attached after the Pi team has build everything would it be possible to include the arm64 builds in the github-release-attachments.
This is what I tried to ask by creating this issue.

Thanks for your time Gordon
DocGalaxyBlock

**Comment by ghollingworth** [comment]
Agree it's unclear, this is the process:

I ask Maxnet to make changes (he's a contractor, he is not an employee)
Maxnet makes those changes and builds the releases you see in this GitHub release, including Windows, MacOS, the universal MacOS build, and the AMD64 deb build.

Then from these sources, @XECDesign (who is a Raspberry Pi employee and supports our distribution) builds the Raspberry Pi OS .deb file which is then distributed through archive.raspberrypi.org/debian/

Some other random people also build things like Flatpaks, etc. but they are not the responsibility of Raspberry Pi or maxnet

So, archive.raspberrypi.org/debian is the canonical, one-true-place to get the Raspberry Pi OS build of the .deb file.  We do not guarantee that this deb file will work on any other distribution.

Gordon

**Comment by lurch** [comment]
I believe that the files that Maxnet builds are also then copied to https://downloads.raspberrypi.org/imager/ (possibly by XECDesign) for use by the download-links on the https://www.raspberrypi.com/software/ page.

**Comment by docgalaxyblock** [comment]
Right the checksums of the win binary and the x86 dmg are the same, just the x86 deb differs.

Now another (offissue) question: It looks like the universal-dmg does not get copied over to https://downloads.raspberrypi.org/imager/ ?
That means M series Apple owners that download the rpi-imager on the website instead of the github releases are forced to use rosetta 2.
I see that the universal build requires at least OS X 10.14, on the intel only build I do not know the min OS requirement...
Are there maybe plans to add the universal build as an additional download to the website?

**Comment by lurch** [comment]
> Now another (offissue) question

There are other issues discussing Apple-silicon builds... https://github.com/raspberrypi/rpi-imager/issues?q=is%3Aissue+is%3Aopen+silicon

**Comment by docgalaxyblock** [comment]
Ok read through all of them (also closed ones) and it is a "scale balancing" problem imo.

But the latest release has no warning regarding the universal build anymore
> *( ... and has only been tested on Intel and M2 Mac Mini. This software has currently NOT been tested on M1 hardware, nor on Macbooks, and will not be officially released, until this is the case. Use at your own risk.)*
