### ISSUE TITLE
Question: Can I export/import the Advanced options?

### ISSUE THREAD

**Issue by samuelT2** [raspberrypi/rpi-imager#605]
Hi there

The imager is a great piece of software which I use several times a month. And since you brought the Advanced options, it's even easier to setup WLAN/SSH etc.

Is there a way to export the Advanced options saved to a file? Perhaps from the registry or somewhere?

I'm using the latest verson on Windows 10.

Thank you very much for your support!

**Comment by MrSmoer** [comment]
I guess so, yes.
The imager uses Qt's QSettings to store the settings and according to the [documentation](https://doc.qt.io/qt-5/qsettings.html#locations-where-application-settings-are-stored) the default for their example is "HKEY_CURRENT_USER\Software\MySoft\Star Runner", for the Imager I found the settings at
`HKEY_CURRENT_USER\Software\Raspberry Pi\Imager`
and especially the advanced settings you were looking for at
`HKEY_CURRENT_USER\Software\Raspberry Pi\Imager\imagecustomization`

**Comment by samuelT2** [comment]
Excellent, that worked. Thank you for your help!
