### ISSUE TITLE
Windows: Not going to use this virus-style program

### ISSUE THREAD

**Issue by bmaehr** [raspberrypi/rpi-imager#61]
I'm not going to do anything with a program (especially a program doing something with drives/hard disks), that first requests administrator rights and in the next step only offers an "Install" button and telling me nebulously somthing about installing and upgrading system components. 

Why does an imager need some kind of installation? Why is it not enough to unzip a zip archive if not an exe without installation is enough?

I definitifly want to know what kind of things a program, that I'm going to use mostlikly once, is going to install on my system and I think I would refuse the installation of some frameworks (perhaps Qt or similar) in most cases.

**Comment by ghollingworth** [comment]
You realise you're asking this in the gitub repository that contains the whole code inside that installer?  Go and have a look if you don't trust us.

**Comment by calston** [comment]
As a better answer any disk imaging tool requires access to the underlying disk hardware to do its job. As such administrative access is required, unfortunately Windows doesn’t provide granular permissions to different system calls

**Comment by maxnet** [comment]
Think the reported is not worried about the admin access, but the standard text from the NSIS installer that system components may be updated.
While that is not actually the case.
