### ISSUE TITLE
Add .bin files to the listing

### ISSUE THREAD

**Issue by Awire9966** [raspberrypi/rpi-imager#611]
Some OSes (Like ChromeOS Flex) come on .bin files that work with the imager, but arent part of the default file browser.

**Comment by tdewey-rpi** [comment]
@Awire9966 If you're aware of a contact point for the OS you'd like to be added to the OS selector, please ask them to get in touch / raise an issue here. They'd need to provide a JSON listing, or negotiate to host their own sublist JSON.

Unfortunately, however, I don't have the bandwidth to chase down new images, so I'm going to mark this as closed.

**Comment by tdewey-rpi** [comment]
Re-reading, @Awire9966, is your request specifically to be able to select .bin files in the custom flashing option?

**Comment by Awire9966** [comment]
> Re-reading, @Awire9966, is your request specifically to be able to select .bin files in the custom flashing option?

My hope is to select bin files from the file explorer window that pops up. Add the bin files to the regex expression.

**Comment by lurch** [comment]
Is a `.bin` file always a raw uncompressed disk-image file, the same as a `.img` file?
