### ISSUE TITLE
Cannot install Raspberry Pi Imager 1.7.5 - Error opening file for writing

### ISSUE THREAD

**Issue by MarcTremblay1981** [raspberrypi/rpi-imager#616]
I had 1.7.2 before and it installed correctly, but I made the mistake to try to update to 1.7.5 and I cannot install it.

![dassdasda](https://github.com/raspberrypi/rpi-imager/assets/123704222/f581c990-d6ac-403d-a1df-e7772751cc5b)

**Comment by maxnet** [comment]
Close the Raspberry Pi Imager 1.7.2 window that is still running first, then press retry.
If you are unable to close it for some reason, the easiest workaround is rebooting your system.

**Comment by MarcTremblay1981** [comment]
There wasn't any.  I also looked in the Task Manager and there was no running rpi-imager.exe process either.
