### ISSUE TITLE
Support Drag&Drop for custom images

### ISSUE THREAD

**Issue by disq** [raspberrypi/rpi-imager#620]
Instead of going through "Choose OS" and then multiple steps down on the menu, just allow a file drag/drop into the main window (or the Choose OS window... but main window would be ideal) for a better UX.

**Comment by marcone** [comment]
I second this. Since I can use the "open with..." right-click menu to send a zip or other file to rpi-imager, I should also be able to drag and drop that same file onto the rpi-imager window.
