### ISSUE TITLE
allow writing to ssd devices

### ISSUE THREAD

**Issue by cpankonien** [raspberrypi/rpi-imager#623]
It would be great to be able to use rpi-imager to write to solid state drives. I currently use balena-etcher but it locks up at times with no error messages. (More of a feature request but I don't see an option for that, so feel free to delete if this is not in the right place.)

**Comment by tarneaux** [comment]
See https://github.com/raspberrypi/rpi-imager/issues/623 which is basically the same feature requedt with a different context.

**Comment by cpankonien** [comment]
oh man, problem solved! didn't even know there was a cli version, thanks!

**Comment by tdewey-rpi** [comment]
Closing, as this is a duplicate.
