### ISSUE TITLE
Scroll bar should be visible 100% of the time

### ISSUE THREAD

**Issue by Botspot** [raspberrypi/rpi-imager#63]
Some users are not noticing that the list of operating systems is longer than the height of the window.
Yes there is a scroll bar, but it's invisible until you (1) start scrolling, or (2) happen to know there is a scroll bar there and move your mouse over it.
![rpi-imager-scrollbar](https://user-images.githubusercontent.com/54716352/81981582-1da3f800-95f6-11ea-98e5-312ef423f2ef.gif)

There's at least one documented instance of this confusing a user: https://www.raspberrypi.org/forums/viewtopic.php?p=1660762#p1660762

**Comment by lurch** [comment]
Very similar to #32
