### ISSUE TITLE
Update Home Assistant main entry to use new logo

### ISSUE THREAD

**Issue by agners** [raspberrypi/rpi-imager#647]
Home Assistant recently became a new logo (see [this blog post](https://www.home-assistant.io/blog/2023/09/17/a-refreshed-logo-for-home-assistant/)). Subitem json got updated yesterday (see https://github.com/home-assistant/version/pull/325). However, the main entry needs an update as well. So the new entry should use the following image URL:

```
"icon": "https://version.home-assistant.io/brand/logo.png",
```

**Comment by maxnet** [comment]
Changing OS repo files is not my department. But do am curious why a new logo needs a new URL, when your old icon URL is already rpi-specific?

**Comment by lurch** [comment]
ping @XECDesign

**Comment by agners** [comment]
> Changing OS repo files is not my department. But do am curious why a new logo needs a new URL, when your old icon URL is already rpi-specific?

Honestly, I forgot that we use that URL here separately :see_no_evil: 

But I'd prefer to change the URL here now that the URL already got changed on our end.

**Comment by XECDesign** [comment]
Done

**Comment by agners** [comment]
Thanks, LGTM!
