### ISSUE TITLE
Advanced options selection doesn't work in text box

### ISSUE THREAD

**Issue by ghollingworth** [raspberrypi/rpi-imager#650]
Not sure why, but if you double-click on one of the text entries it doesn't select the text.

For example, open the advanced options, click the "Set hostname" tickbox and then double-click "raspberrypi" that should select the whole word but doesn't.  Also click and drag doesn't work.

**Comment by maxnet** [comment]
Do are running a build more recent than: https://github.com/raspberrypi/rpi-imager/commit/ce549cadb231614ffc544e538c5e873b75217bb6 ?

Having "selectByMouse: true" on the fields is important.

**Comment by tdewey-rpi** [comment]
@ghollingworth This should be addressed in the next release, which is pending on #645 and the associated translation changes.

**Comment by tdewey-rpi** [comment]
Resolved in v1.8.1. Try it out!
