### ISSUE TITLE
[Question] Pi OS Bookworm Wi-Fi Configuration

### ISSUE THREAD

**Issue by bennymeg** [raspberrypi/rpi-imager#656]
Since that Pi OS 5 (Bookworm) is now using NetworkManger by default, does it mean we lost support for Wi-Fi configuration on the image, or this is still supported by the rpi-imager?

**Comment by ghollingworth** [comment]
Yes it works fine

**Comment by bennymeg** [comment]
Thanks.
Out of interest, do you mind explaining how it's done? Can it be configured b writing a file to the /boot directory like before?
