### ISSUE TITLE
[request] Noobs in list

### ISSUE THREAD

**Issue by ale-rinaldi** [raspberrypi/rpi-imager#67]
Hello,

I just tried RPI Imager and I loved how it's fast to write and also to verify the SD card! The fact that it flashes why it downloads it really awesome, congratulations!

I wonder if it could make sense to have Noobs in the list of flashable images, in case one wants to flash it on a bunch of SD cards and decide later which image to actually use on each one.

Thanks

**Comment by ghollingworth** [comment]
Just download the image and hit custom

**Comment by ale-rinaldi** [comment]
Well yes, I got that. I think it could be useful to have it listed with the other images, but I'll take it as a no.

Thanks

**Comment by lurch** [comment]
Problem is that NOOBS isn't a "raw disk mage" in the same format that Raspberry Pi OS (etc.) is. With Raspberry Pi OS, you just write the raw image directly to the SD card (and the image contains the partitions, filesystems, etc.); with NOOBS you have to format the card as FAT32 first, and then copy the files from inside the NOOBS zipfile onto the FAT32 filesystem.

**Comment by ale-rinaldi** [comment]
Ok, that totally makes sense. Thanks for your clarification!

**Comment by guysoft** [comment]
It seems now that if you install the noobs zip file the imager formats the disk and installs it accordingly.

**Comment by lurch** [comment]
See also the comment here: https://github.com/raspberrypi/noobs/issues/610#issuecomment-729041932
