### ISSUE TITLE
Embedded imager kernel panic

### ISSUE THREAD

**Issue by cillian64** [raspberrypi/rpi-imager#671]
Steps to reproduce:
- Build the embedded imager from latest commit on `qml` which is `f28b9d0`
- Copy the files to a FAT-formatted USB drive
- Boot imager from the USB drive on a Pi 4
- Then insert a microSD card
- In embedded imager:
  - Select an OS
  - Select the microSD card to image to
  - Click Next
  - Click Edit Settings

The result is a kernel panic `Attempted to kill init!`

**Comment by maxnet** [comment]
Apply this patch manually to Imager source: https://github.com/raspberrypi/rpi-imager/blob/qml/embedded/imager/package/rpi-imager/0001-rpi-imager-change-window-to-popup.patch
(Applying it automatically does not seem to work properly with SITE_METHOD=local)

Or have a go at using Wayland instead of EGLFS, if you do want to have multiple windows instead of a single one.
But that will probably enlarge image size by quite a bit.

**Comment by maxnet** [comment]
Oh, and "kernel panic" is a bit over stated. "Attempted to kill init" is just that the main program (init) has ended.
(Which it did because it cannot create extra top level windows in EGLFS mode, that is meant for full screen applications)

**Comment by cillian64** [comment]
Thanks, I saw that commit but didn't realise it needed manually applying.  I'm overdue for learning about buildroot anyway so I'll see if I can figure out how to make it automatically apply.

> Oh, and "kernel panic" is a bit over stated. "Attempted to kill init" is just that the main program (init) has ended.

Right, that makes sense. I've not seen this before so took it literally.

**Comment by maxnet** [comment]
>Thanks, I saw that commit but didn't realise it needed manually applying. 

Normally *.patch in a buildroot's package folder is applied automatically during download & extract.
But we currently not downloading anything, so it is skipping that phase.

Either uncomment the github line here and remove the path and METHOD=local lines: https://github.com/raspberrypi/rpi-imager/blob/qml/embedded/imager/package/rpi-imager/rpi-imager.mk#L9
Or create a PRE_CONFIGURE_HOOKS function that runs patch manually.
