### ISSUE TITLE
Cannot "Exit Full Screen"

### ISSUE THREAD

**Issue by Adam-Langley** [raspberrypi/rpi-imager#69]
Platform: MacOS 10.15.2

Once the main window is made full-screen, the "Exit Full Screen" button is disabled.
The only enabled button on the title bar, is "quit".

**Comment by maxnet** [comment]
In newer Mac OS X versions it no longer shows a button to *enter* full screen for the application.
So am assuming the problem of not being able to exit it also no longer exists.
