### ISSUE TITLE
"CHOOSE OS" written to storage

### ISSUE THREAD

**Issue by timg236** [raspberrypi/rpi-imager#696]
RPi Imager 1.8

1. Select "No filtering"
2. Select a custom image
3. Select storage e.g. Sd
4. Select "No filtering" AGAIN
5. OS now says "CHOOSE OS"
6. Select "Storage" again
7. Press Next

The imager will write the previously selected custom image to the SD card. It looks like the OS selection button gets reset when selecting filtering but internally the imager has remembered the custom image.

**Comment by tdewey-rpi** [comment]
@maxnet One for you, if you have time.
