### ISSUE TITLE
Feedback on the new ui.

### ISSUE THREAD

**Issue by steveiliop56** [raspberrypi/rpi-imager#701]
Hello,

I recently updated to raspberry pi imager 1.8.1 launched it and saw this: 

<img width="1080" alt="imager" src="https://github.com/raspberrypi/rpi-imager/assets/106091011/4c22e59a-cb54-41d6-b86e-ff9e4809ac2f">

I want to point some things out about it... Firstly the layout is bad... I prefer the old layout by far.... Secondly while the board selection menu is a good addition the actual board images are not displayed well... Thirdly the settings button disappeared again and I have to bring it up with the old ctr+shift+x shortcut... Anyway that's my personal opinion hope it helps!

**Comment by ghollingworth** [comment]
Thanks
