### ISSUE TITLE
Selecting/changing device clears OS selection (minor)

### ISSUE THREAD

**Issue by pelwell** [raspberrypi/rpi-imager#702]
People used to selecting the OS image first (because Devices didn't used to be a thing) may be surprised that, when subsequently selecting or choosing their device, the OS becomes unselected, even if the OS is one that is supported by the device.

**Comment by tdewey-rpi** [comment]
Definitely a quality of life improvement. We'll aim to schedule this for 1.8.3 or later, depending on the number of issues reported as part of Pi5 launch.

**Comment by tdewey-rpi** [comment]
I can confirm this is now the expected behaviour.
