### ISSUE TITLE
Possibility to choose the version

### ISSUE THREAD

**Issue by mkz212** [raspberrypi/rpi-imager#710]
You can only choose the latest version, at least in the case of Homebridge, there is no possibility to choose earlier versions. If you want to install the previous version, you have to manually download it and use the option Use Custom.

**Comment by cmitu** [comment]
The list of images is read by Imager from the the [json](https://homebridge.io/rpi-image-repo.json) file published by the Homebridge project, so it's something controller by them. Maybe ask the Homebridge maintainers to expand the list of images published for RPI Imager.

**Comment by mkz212** [comment]
Ok. Thank You.
