### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ricca665** [raspberrypi/rpi-imager#723]
**Describe the bug**
The bug happens when you finish the flashing, but when you see the settings for the automated install it prints out random gebrish

**To Reproduce**
Flash rasbian or other oses, open up the custom os settings, and there you are, Windows and linux

**Expected behavior**
Should reput the password prompts

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 and Ubuntu 23.10

**The name of the OS you are trying to write**

**Are you using OS Customisation?**
On windows rectify 11 but on linux nothing
**Additional context**

**Comment by tdewey-rpi** [comment]
Closing the issue - no response in 2 weeks, insufficient detail for me to progress.
