### ISSUE TITLE
Bookworm not available

### ISSUE THREAD

**Issue by heis2201** [raspberrypi/rpi-imager#726]
**Describe the bug**
I do not have to option to select bookworm. All I can select from is bullseye ("Legacy").

**To Reproduce**
Host os is Fedora 38 up-to-date. both rpm and flatpak show the same behaviour

**Expected behavior**
Raspberry Pi OS 12 "bookworm" available

**Screenshots**
![image](https://github.com/raspberrypi/rpi-imager/assets/17801574/90100a72-e7b0-4a7b-9ccd-8e0c628d02d4)

**The name of the OS you are trying to write**
Raspberry Pi OS 12 "bookworm" LITE

**Additional context**
I saw bookworm (with release day 2023-10-10), then rpi-imager couldn't write the image complaining about permissions on the SD card (probably I still had some partition on the SD card mounted). On the second attempt book worm does not show up as an option

**Comment by heis2201** [comment]
related: https://forums.raspberrypi.com/viewtopic.php?t=358721

**Comment by lurch** [comment]
Duplicate of #690 ?

**Comment by heis2201** [comment]
> Duplicate of #690 ?

indeed.
