### ISSUE TITLE
rpi-imager:1.8.1 missing from apt repos

### ISSUE THREAD

**Issue by yantarou** [raspberrypi/rpi-imager#732]
On both "Raspberry Pi OS" based on Bullseye and Bookworm, the latest installable package of `rpi-imager` is `1.7.5+rpt1`:

```
$ apt-cache policy rpi-imager
rpi-imager:
  Installed: (none)
  Candidate: 1.7.5+rpt1
  Version table:
     1.7.5+rpt1 500
        500 http://archive.raspberrypi.org/debian bullseye/main arm64 Packages
```

```
$ apt-cache policy rpi-imager
rpi-imager:
  Installed: 1.7.5+rpt1
  Candidate: 1.7.5+rpt1
  Version table:
 *** 1.7.5+rpt1 500
        500 http://archive.raspberrypi.com/debian bookworm/main arm64 Packages
        100 /var/lib/dpkg/status
```

Yet, the version downloadable from `https://downloads.raspberrypi.org/imager/imager_latest_amd64.deb` (as of 2023-11-18) is:

```
$ apt-cache policy rpi-imager
rpi-imager:
  Installed: 1.8.1
  Candidate: 1.8.1
  Version table:
 *** 1.8.1 100
        100 /var/lib/dpkg/status
```

Can we expect version 1.8.1 to enter the above mentioned repositories (including its `dsc` files)?

Thanks!

**Comment by tdewey-rpi** [comment]
We're expecting to roll out 1.8.3, which includes important changes, this week.
