### ISSUE TITLE
[FEATURE] Missing RPI5 Specific purpose OS for 3D Printing

### ISSUE THREAD

**Issue by chalb0** [raspberrypi/rpi-imager#734]
**Is your feature request related to a problem? Please describe.**
Previous versions of RPI imager include specific purpose OS.

**Describe the solution you'd like**
3D printing - specifically for Klipper and Mainsail.

**Describe alternatives you've considered**
Manual installation

**Additional context**
Nil Required

**Comment by tdewey-rpi** [comment]
Hi @chalb0, thanks for the report.

Unfortunately this is neither a bug nor a feature request for Raspberry Pi Imager. Please contact the projects you want to see and ask them to provide a Raspberry Pi 5-compatible image accordingly.

Closing as not applicable.
