### ISSUE TITLE
[BUG] Tab-header in options dialog goes crazy if you enter a long username

### ISSUE THREAD

**Issue by lurch** [raspberrypi/rpi-imager#739]
**Describe the bug**
In the "OS Customisation" window, if you enter a _really_ long username, then the tab-buttons at the top of the window get super-wide and the right-most tab ends up disappearing.

**To Reproduce**
Select an Image and Storage Device, press Next, select "Edit Settings", enter a really long username.

**Expected behaviour**
All three tabs should remain visible in the options window.

**Screenshots**
First screenshot shows what it looks like with a short username `abc` :
![20231121_11h53m34s_grim](https://github.com/raspberrypi/rpi-imager/assets/476186/bb68007f-c6f9-428d-859a-c12ded750208)

Second screenshot shows what it looks like with a long username `abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz` :
![20231121_11h54m17s_grim](https://github.com/raspberrypi/rpi-imager/assets/476186/afaaba09-bd6e-4d0a-9342-975a7b37f972)

**Desktop (please complete the following information):**
 - OS: Raspberry Pi OS Bookworm 64-bit, running on a Raspberry Pi 5

**The name of the OS you are trying to write**
N/A

**Are you using OS Customisation?**
Yes, that's where the bug happens :slightly_smiling_face: 

**Additional context**
It's obviously unlikely that somebody would enter a **real** username that long, which makes this low-priority, but it's still a UI-bug which is probably worth fixing.

**Comment by tdewey-rpi** [comment]
Confirmed it appears on Windows if you use a >51 character username.

**Comment by tdewey-rpi** [comment]
@lurch has correctly identified this is seemingly caused by the "Set authorized_keys" label on the 'Services' page, which should probably be width-constrained.

**Comment by tdewey-rpi** [comment]
This opens a wider question: are we correctly limiting the size of these fields to match established Linux distro norms? Eg, do we need to cap the Username field at 32 characters to be compatible with a range of downstream OSes that may be customisable?

**Comment by tdewey-rpi** [comment]
Certainly for the username, I don't see a solid argument to go beyond 31 characters, as systemd will not allow this: https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html

We may need to constrain other labels too.

**Comment by tdewey-rpi** [comment]
The hostname must additionally be constrained to 253 characters, per https://man7.org/linux/man-pages/man7/hostname.7.html
