### ISSUE TITLE
Make disk ejection after writing optional

### ISSUE THREAD

**Issue by schwa** [raspberrypi/rpi-imager#74]
I'll need to edit the wpa_supplicant.conf and ssh files on my newly written SD card (see also #73) - it's a little bit inconvenient for rbi-imager to always eject the disks after writing. Maybe make that optional? (Or flip this around and provide an option to mount disks after writing).

**Comment by ghollingworth** [comment]
The Raspberry Pi Imager application was designed with simplicity in mind, giving the user the smallest number of choices, in the simplest language possible.

Any request that requires extra 'options' or buttons, or may in any way confuse a beginner will not be implemented.

This functionality could only be implemented by adding extra options to the user interface.
