### ISSUE TITLE
download page (imager_latest.dmg) is stuck at 1.8.1 and 1.8.3 is only available via GitHub

### ISSUE THREAD

**Issue by core-code** [raspberrypi/rpi-imager#747]
is the download page stuck at 1.8.1 on purpose?

https://www.raspberrypi.com/software/

**Comment by lurch** [comment]
FYI
https://downloads.raspberrypi.org/os_list_imagingutility_v2.json
https://downloads.raspberrypi.org/os_list_imagingutility_v3.json
https://downloads.raspberrypi.org/os_list_imagingutility_v4.json

all still say `"latest_version": "1.7.4",` ?

**Comment by AmnaSN** [comment]
The download page is still stuck at 1.8.1 for Mac

**Comment by framps** [comment]
I just install latest bookworm desktop image and there ist rpi-image 1.8.3 is included.

**Comment by core-code** [comment]
i am referring to this link

https://downloads.raspberrypi.org/imager/imager_latest.dmg

others may be fine

**Comment by suschizu** [comment]
the website download still downloads version 1.8.1 instead of version 1.8.3 - is there a reason why the website link wasn't yet updated to version 1.8.3?

**Comment by tdewey-rpi** [comment]
No good reason, just illness taking longer to resolve than hoped. This is on my list for this week, alongside other website updates.

**Comment by suschizu** [comment]
ah ok sorry - get well soon :/

**Comment by tdewey-rpi** [comment]
The website now points to 1.8.3, and I'm about to deploy a change to the manifests to prompt people to upgrade.

**Comment by core-code** [comment]
thanks!
