### ISSUE TITLE
[BUG] When you choose raspberry pi 3 as a device you cannot choose raspian bookworm

### ISSUE THREAD

**Issue by bartex100** [raspberrypi/rpi-imager#756]
When you choose raspberry pi 3 as a device you cannot choose raspian bookworm, however based on my testing it works perfectly fine

**Comment by lurch** [comment]
Duplicate of #730 ?

**Comment by tdewey-rpi** [comment]
Thanks for the report, @bartex100.

As @lurch has pointed out, this issue has been raised previously in #730, so I'm going to close this one as a Duplicate.
