### ISSUE TITLE
[FEATURE] Please make WiFi functionality optional based on a cmake option

### ISSUE THREAD

**Issue by yurivict** [raspberrypi/rpi-imager#773]
**Is your feature request related to a problem? Please describe.**
The WiFi part seems to be Linux-specific.
I am trying to compile on FreeBSD, and linux/networkmanagerapi.cpp fails to compile due to it being Linux-specific.

However, WiFi shouldn't be required for basic image operations, so the WiFi parts should be made optional to allow for creating bootable media on non-Linux systems.

**Describe the solution you'd like**

Add a cmake option, for example RPI_IMAGER_WIFI_ENABLED, that would allow to isolate the Linux-specific WiFi code.

**Describe alternatives you've considered**
n/a

**Additional context**
I would like to create the FreeBSD port for rpi-imager.

**Comment by maxnet** [comment]
Don't see why we need the option when adding code to query the SSID under FreeBSD shouldn't be that hard.
Added some sample code that compiles but hasn't been really tested as I don't have wifi under virtualization.
