### ISSUE TITLE
[FEATURE] add option to enable `usb_max_current_enable=1` for pi 5

### ISSUE THREAD

**Issue by godalming123** [raspberrypi/rpi-imager#775]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to shut down windows, boot into Linux, mount the USB, and edit the max_current_enable setting just to use USB boot with my 5v 3a power supply.

**Describe the solution you'd like**
In the OS config menu, their should be an option to enable USB boot for 15 watt power supplies on the raspberry pi 5.

**Comment by maxnet** [comment]
>I'm always frustrated when I have to shut down windows, boot into Linux, mount the USB, and edit the max_current_enable setting just to use USB boot with my 5v 3a power supply.

Eh, shouldn't Windows be able to access the FAT partition with config.txt as well?

**Comment by godalming123** [comment]
Maybe that's possible, enabling USB boot would still be mildly annoying though.

**Comment by tdewey-rpi** [comment]
I think @maxnet's point is that after writing, you could hotplug the USB storage and adjust `config.txt` from inside Windows - no Linux PC use required?

**Comment by tdewey-rpi** [comment]
No further update in a month - closing as stale.

We may explore this for 2.0, however I can't immediately see how to expose this to new users without causing some degree of confusion.

**Comment by andrerav** [comment]
This would be a very useful feature. Hotplugging the USB stick does not work in Windows and can not be considered a workaround.

<img width="558" height="193" alt="Image" src="https://github.com/user-attachments/assets/34fcc150-f140-4355-bb4a-67cf085d991e" />

@tdewey-rpi @maxnet
