### ISSUE TITLE
Selects the language to use when recording an image.

### ISSUE THREAD

**Issue by paolosezart** [raspberrypi/rpi-imager#777]
I would like the default keyboard layout to be English. However, I would like to set a different keyboard layout right away. If I choose my own language when burning the image, will the English keyboard layout remain or will I have to install it separately?

**Comment by tdewey-rpi** [comment]
Hi @paolosezart

Unfortunately this isn't an issue with rpi-imager itself, and so I'm going to close the issue. In this case, I believe you'll want to seek support from the OS vendor or in the Raspberry Pi Forums.
