### ISSUE TITLE
[BUG] v1.8.5 Incorrect icon and window title: 'org.raspberrypi.rpi-imager' on GNOME

### ISSUE THREAD

**Issue by roliver-rpi** [raspberrypi/rpi-imager#785]
**Describe the bug**
Incorrect icon/window title under GNOME. Launcher is as expected.

![switcher_alt_tab](https://github.com/raspberrypi/rpi-imager/assets/146752093/4e585ff8-e24e-4bb5-9418-60b7e95af161)
![overview](https://github.com/raspberrypi/rpi-imager/assets/146752093/08fdef41-5621-4ced-8d44-00039d0d650d)
![dash](https://github.com/raspberrypi/rpi-imager/assets/146752093/32bca0f7-975c-4b85-bc45-f234ec737f63)
![window_title](https://github.com/raspberrypi/rpi-imager/assets/146752093/8508c404-18e0-4c9a-8f47-4def7dee67eb)
![launcher](https://github.com/raspberrypi/rpi-imager/assets/146752093/243385c7-bf3b-4628-8711-2af0435e1b38)

**To Reproduce**
rpi-imager: built from source 8c9de2d78cc5d618271f434341e254c548bfe82a (qml branch, v1.8.5) into '.deb' package (installed by apt)
host OS: Debian GNU/Linux 12 (bookworm) - GNOME

**Comment by maxnet** [comment]
Recall the wayland/gnome folks expect people to use their naming scheme for the .desktop file.
Try if it works any better if you do:

```
sudo mv /usr/share/applications/rpi-imager.desktop /usr/share/applications/org.raspberrypi.rpi-imager.desktop
```
