### ISSUE TITLE
[BUG] RUN SSH-KEYGEN button still enabled in embedded net install version

### ISSUE THREAD

**Issue by trejan** [raspberrypi/rpi-imager#786]
**Describe the bug**
The RUN SSH-KEYGEN button is enabled but does nothing in the net install Pi imager as no SSH client in the buildroot boot.img

This is on a Pi 5 running the beta net install.

**To Reproduce**
Run net install and press the RUN SSH-KEYGEN button in the SERVICES tab.

**Expected behaviour**
Button should be disabled in the net install version.

**Screenshots or video**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**
N/A

**The name of the OS you are trying to write**
N/A

**Are you using OS Customisation?**
Yes. Enable SSH in SERVICES tab.

**Additional context**

**Comment by tdewey-rpi** [comment]
Confirmed as an issue - the ssh-keygen binary appears to be assumed to be present on Linux environments.
