### ISSUE TITLE
[BUG] Error removing exsting partitions

### ISSUE THREAD

**Issue by AnmolrPunj** [raspberrypi/rpi-imager#788]
**Describe the bug**

**To Reproduce**
Include steps to allow us to reproduce the error. Include your host OS, and the version of Raspberry Pi Imager.
Wubdiws 10 version 1.8.4

**Expected behaviour**
Should format the sd card
**Screenshots or video**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 14, Windows 11, Ubuntu Server 22.04]

**The name of the OS you are trying to write**
Raspberry pi os legacy 32bit rpi os 64bit rpi os legacy 64 bit
**Are you using OS Customisation?**
No
**Additional context**
Image:
![image](https://github.com/raspberrypi/rpi-imager/assets/147607841/43ba9af0-b841-4bd5-9a4b-f87352a80fce)

**Comment by tdewey-rpi** [comment]
Are you writing to an SD card? If so, have you nudged the write protect switch?

**Comment by AnmolrPunj** [comment]
i fixed it by puting the sd card in another computer now it works on my computer as well

**Comment by lurch** [comment]
> now it works on my computer as well

So I guess this issue can be closed?

**Comment by tdewey-rpi** [comment]
Closing as 'Won't Fix' - there's no sign of an issue to be addressed in the Raspberry Pi Imager codebase.
