### ISSUE TITLE
[BUG] [REGRESSION] [macOS] 1.8.4. was Universal (ARM+Intel), 1.8.5 is Intel-only

### ISSUE THREAD

**Issue by core-code** [raspberrypi/rpi-imager#789]
the macOS build in 1.8.5 is no longer 'universal' but intel-only :(

**Comment by maxnet** [comment]
Knew I had forgotten something.
Replaced the .dmg

**Comment by core-code** [comment]
thanks for the quick fix! i see the files in GitHub have been updated, but i still get the old build here:

https://downloads.raspberrypi.org/imager/imager_latest.dmg

**Comment by lurch** [comment]
> thanks for the quick fix! i see the files in GitHub have been updated, but i still get the old build here:
> 
> https://downloads.raspberrypi.org/imager/imager_latest.dmg

I suspect that'll get fixed during (UK) office-hours tomorrow :slightly_smiling_face:

**Comment by core-code** [comment]
can you ping them? its office hours and they are still delivering the intel-only build

**Comment by core-code** [comment]
fixed now, thanks!
