### ISSUE TITLE
Raspberry Pi Imager presents user interface in Dutch

### ISSUE THREAD

**Issue by gcw0001** [raspberrypi/rpi-imager#81]
I am located in US east coast and am using a MacBook Pro to download and run the Raspberry Pi Imager.
The System Preferences -> Language and Region show:

> Language = English
> Region = United States

Entering "locale" in terminal shows:

> LANG="en_US.UTF-8"
> LC_COLLATE="en_US.UTF-8"
> LC_CTYPE="en_US.UTF-8"
> LC_MESSAGES="en_US.UTF-8"
> LC_MONETARY="en_US.UTF-8"
> LC_NUMERIC="en_US.UTF-8"
> LC_TIME="en_US.UTF-8"
> LC_ALL=

When running the Imager the user interface appears to be in Dutch as shown in attached.
![pi_imager](https://user-images.githubusercontent.com/67279103/85303086-0ae3d500-b478-11ea-95ae-9b60eb7a9c7d.png)

The site that I downloaded from was "downloads.raspberrypi.org" which resolves to 93.93.130.212.

**Comment by maxnet** [comment]
Strange.
Where you downloaded it from does not matter.
Imager has English, Dutch and Chinese all built into the same executable and what language it uses should depend on the locale reported by the system.


If you run on terminal: 

```
plutil -p ~/Library/Preferences/.GlobalPreferences.plist
```

Does it show "nl" anywhere, be it in the "AppleLanguages" field, "AppleLocale", or anywhere else?

**Comment by gcw0001** [comment]
"nl" appears three times in the output from plutil ...
In the AppleLanguages section there is one instance in the list ...

>  "AppleLanguages" => [
>     0 => "en-US"
>     1 => "ja-US"
>     2 => "fr-US" 
>     3 => "de-US"
>     4 => "es-US"
>     5 => "it-US"
>     6 => "pt-US"
>     7 => "pt-PT"
>     8 => "nl-US"
>     9 => "sv-US"
>     10 => "nb-US"

and twice in this list ...

> "NSLinguisticDataAssetsRequested" => [
>     0 => "en"
>     1 => "en_US"
>     2 => "ja"
>     3 => "ja_US"
>     4 => "fr"
>     5 => "fr_US"
>     6 => "de"
>     7 => "de_US"
>     8 => "es"
>     9 => "es_US"
>     10 => "it"
>     11 => "it_US"
>     12 => "pt"
>     13 => "pt_US"
>     14 => "pt_PT"
>     15 => "nl"
>     16 => "nl_US"
>     17 => "sv"
>     18 => "sv_US"
>     19 => "nb"
>     20 => "nb_US"

**Comment by maxnet** [comment]
>"AppleLanguages" => [

That you have multiple AppleLanguages is a bit strange.
Are you positive you only have English in the "preferred languages" list and nothing else?

Like in the following screenshot:

![Screenshot 2020-06-22 at 18 52 48](https://user-images.githubusercontent.com/1123701/85314591-06401080-b4ba-11ea-8a02-9392a873b467.png)

**Comment by gcw0001** [comment]
That may be it. I have multiple languages in the Preferred languages list, the first being English (US) as shown ...
![language_region](https://user-images.githubusercontent.com/67279103/85325519-c1a47d00-b499-11ea-84de-c19c56249a8d.png)
and Dutch, although not visible in the screenshot, is in the list further down.
I just removed the Netherlands (Dutch) entry from the list, executed the Raspberry Pi Imager and the display is now in English ..
![imager_en](https://user-images.githubusercontent.com/67279103/85325817-40011f00-b49a-11ea-9a21-bca1b845c8c2.png)
Alles ist in ordnung.
