### ISSUE TITLE
[BUG] Imager breaks sd cards used, regardless of version, restart, card, card reader, etc.

### ISSUE THREAD

**Issue by Ryaja2** [raspberrypi/rpi-imager#810]
**Describe the bug**
When the imager gets to "Verify" It simply says "Unable to read SD card. SD card may be broken." though I can use the erase feature to fix the sd. and can confirm it works.

**To Reproduce**
Try to install an OS

**Expected behaviour**

**Desktop (please complete the following information):**
 - OS: Windows 11

**The name of the OS you are trying to write**
Applicable to all.

**Comment by timg236** [comment]
Works for me.
Perhaps you could be more specific.

**Comment by tdewey-rpi** [comment]
@Ryaja2

Based on the information provided, I can't reproduce your issue. Please provide details on:

- rpi-imager version
- Where you downloaded it from
- The cards tried
- The card readers tried

**Comment by Ryaja2** [comment]
> @Ryaja2
> 
> Based on the information provided, I can't reproduce your issue. Please provide details on:
> 
> * rpi-imager version
> * Where you downloaded it from
> * The cards tried
> * The card readers tried

I've tried the 1.8.5, 1.7 something, 1.2
Ive downloaded it from the github & the website
Ive tried 2 micro sd cards, one is a 16gb that came w/ the pi and the other is a "onn" brand 64 gb I got from walmart.

**Comment by Ryaja2** [comment]
Ive also tried 2 readers

**Comment by tdewey-rpi** [comment]
@Ryaja2 Please confirm your card can be verified correctly - can you post a screenshot of the result of running H2testw against the storage device?

H2testw is available from https://www.heise.de/download/product/h2testw-50539/download and includes both German and English translations.

**Comment by tdewey-rpi** [comment]
Closing as stale, no response in >1month
