### ISSUE TITLE
i got this verifying error every time after installing the OS image on SD card

### ISSUE THREAD

**Issue by ghiathkamel** [raspberrypi/rpi-imager#815]
i got this verifying error every time after installing the OS image on SD card
please check the photo
![image](https://github.com/raspberrypi/rpi-imager/assets/60829719/6cbc4047-1ca0-4af8-986f-e81df77ca8ed)
**Desktop (please complete the following information):**
 Windows 11 

**The name of the OS you are trying to write**
Any RPI4 OS
**Are you using OS Customisation?**
No

**Comment by lurch** [comment]
@ghiathkamel Creating a single new issue is enough. **Please** don't spam multiple old issues too.

**Comment by tdewey-rpi** [comment]
Please confirm your card can be verified correctly - can you post a screenshot of the result of running H2testw against the storage device?

H2testw is available from https://www.heise.de/download/product/h2testw-50539/download and includes both German and English translations.

**Comment by ghiathkamel** [comment]
> Please confirm your card can be verified correctly - can you post a screenshot of the result of running H2testw against the storage device?
> 
> H2testw is available from https://www.heise.de/download/product/h2testw-50539/download and includes both German and English translations.

you are right, the SD card damaged, not the rpi imager :)
