### ISSUE TITLE
Question: RPI-Imager Wifi/Hostname configuration

### ISSUE THREAD

**Issue by hkfuertes** [raspberrypi/rpi-imager#824]
Hello, I'm right now building a buildroot image for an specific project, and I would like to make my image compatible with configurator on the imager, mainly setting the hostname and the wifi info. How does the app do that? What would I need to do on my buildroot?

Sorry, I did not know where to ask this. And thank you!

**Comment by tdewey-rpi** [comment]
Sounds like you are looking for this: https://cloud-init.io

Then take a look at how Canonical offer Ubuntu Server to see how they flag their cloud-init support.

Closing, as this isn't strictly an issue with the Raspberry Pi Imager codebase, and we don't yet have a mechanism for tracking documentation (and a blank GH issue isn't the route to do this).

**Comment by lurch** [comment]
> Then take a look at how Canonical offer Ubuntu Server to see how they flag their cloud-init support.

...by which I think Tom means "take a look at the Ubuntu Server entries in https://downloads.raspberrypi.com/os_list_imagingutility_v4.json " :wink:
