### ISSUE TITLE
[Opposite of a BUG]: New imager is SUPER FAST?

### ISSUE THREAD

**Issue by quitmeyer** [raspberrypi/rpi-imager#830]
### What happened?

Sorry, I didn't know how to submit a comment that isn't actually a bug report, but rather a "wow im surprised by how awesome you got it"

before, it would take my computer (windows 10, hp omen) about 20-30 mins to write an image to a disk.  But i just wrote the latest version of bookworm to a 64gb disk (like i have been doing for months), and it was ridiculously fast! like 5 minutes or less.

So like was i doing something very wrong before? or did the latest imager just really get fast somehow?

Either way, great work!

### Version

1.8.5 (Default)

### What host operating system were you using?

Windows

### Host OS Version

Windows 10

### Selected OS

Bookworm 64

### Which Raspberry Pi Device are you using?

Raspberry Pi 4B, 400, and Compute Modules 4, 4S

### What kind of storage device are you using?

microSD Card in a USB reader

### OS Customisation

- [X] Yes, I was using OS Customisation when the bug occurred.

**Comment by tdewey-rpi** [comment]
We don't generally encourage the use of the issue tracker for non-issues, as it can project a unrealistic view of project activity.

That said, however, I'm delighted to hear you're having a good experience. It's always a pleasure to hear users are finding the tool useful.

You may have encountered a cache hit this time around that improved your download time (and thus the complete select-write-verify cycle time). We're also looking at making additional improvements to the performance too, as part of some wider work around provisioning. I can't offer a timeframe for those yet, but my hope is that will improve the experience further.

I'm going to close this issue, as it's not something that requires a correction in the Raspberry Pi Imager codebase, but rest assured the feedback is welcome.
