### ISSUE TITLE
[OS Request]: 3DPrinterOS

### ISSUE THREAD

**Issue by art1415926** [raspberrypi/rpi-imager#835]
### Is your feature request related to a problem? Please describe.

none

### Describe the solution you would like to see implemented

Hi there :)
I'm the developer at 3DPrinterOS <https://3dprinteros.com/>, which uses Raspberry Pi computers to connect 3D printers to our cloud solution <https://cloud.3dprinteros.com/>. Our Raspberry Pi-based Cloud Client allows users to manage their printer from anywhere via the internet and do many things that make users’ lives easier and more predictable while managing tens to hundreds of printers.

Note that it should go in the Other specific purpose OS section.
```
{
    "os_list": [
        {
            "name": "3DPrinterOS",
            "description": "Allows you to manage your 3D printers fleet from anywhere",
            "icon": "https://rpi-imager.3dprinteros.com/3dprinteros.ico",
            "subitems_url": "https://rpi-imager.3dprinteros.com/os-list-3dprinteros.json"
        }
    ]
}
```

The JSON file is here: <https://rpi-imager.3dprinteros.com/os-list-3dprinteros.json>

Our Raspberry Pi image is usually downloaded from our download page: https://cloud.3dprinteros.com/download/

For now, more than 2500 users use our Raspberry Pi image daily, and this number is continuously growing.

Loving the RPi imager! :) Thanks for making it.

### Describe alternatives you've considered

none

### Additional context

none

### Version

1.8.5 (Default)

**Comment by tdewey-rpi** [comment]
Please fill out the form at https://forms.gle/z5RWokTPsuDJTcT38

Closing, as this is not something that requires a change in Raspberry Pi Imager.
