### ISSUE TITLE
[BUG]:  Not updating wpa country from options, copies hashed key instead of text key to wpa = when using for octopi

### ISSUE THREAD

**Issue by fargodwe** [raspberrypi/rpi-imager#836]
### What happened?

Used imager with options of network country of US and a text network psk when using for octopi.  The network country is left as GB in the resulting octopi wpa_supplicant and the network psk is passed as the hash key into resulting octopi wpa_supplicant.  I just happen to have a linux box so after booting the pi the 1st time from the USB output from imager I have use my linux box and edit wpa_supplicant to get the correct country and psk.

### Version

1.8.5 (Default)

### What host operating system were you using?

Windows

### Host OS Version

22H2

### Selected OS

Octopi

### Which Raspberry Pi Device are you using?

Raspberry Pi 4B, 400, and Compute Modules 4, 4S

### What kind of storage device are you using?

microSD Card in a USB reader

### OS Customisation

- [X] Yes, I was using OS Customisation when the bug occurred.

**Comment by tdewey-rpi** [comment]
I wouldn't expect wpa_supplicant.conf to be edited for an image based on a recent version of Raspberry Pi OS - which uses an alternative customisation scheme.

As OctoPi is a Raspberry Pi OS based distro, this all appears to be working as expected.

If you're seeing OctoPi not honouring your chosen customisation, I'd suggest contacting the OctoPi project first.

Closing as 'Won't Fix', as the description contains no evidence of unexpected behaviour.
