### ISSUE TITLE
[BUG]: Choos OS can't see PC folders nor .img files

### ISSUE THREAD

**Issue by Gattaro1989** [raspberrypi/rpi-imager#838]
### What happened?

I had to install a custom OS on a 32GB SD. 
But when I try to find the .img file through Pi imager, I can't navigate through the folders to find the right path and even if I place the image file in one of the few folders that are viewed, the imager doesn't see the .img.

Am I missing something? Never happened before last update...

### Version

1.8.5 (Default)

### What host operating system were you using?

Windows

### Host OS Version

10

### Selected OS

Custom

### Which Raspberry Pi Device are you using?

Raspberry Pi 4B, 400, and Compute Modules 4, 4S

### What kind of storage device are you using?

microSD Card in a USB reader

### OS Customisation

- [ ] Yes, I was using OS Customisation when the bug occurred.

**Comment by lurch** [comment]
Any chance you could provide a screenshot? Is there some kind of security-software on your PC that's restricting what folders you're able to access?

> Never happened before last update...

Older versions are available [here](https://github.com/raspberrypi/rpi-imager/releases), if you want to test to see if the older versions still work "correctly"?

**Comment by mr2malv** [comment]
This happened on my computer as well with a freshly downloaded exe. Opened and only see a C drive nothing else. Closed the appa dn restarted tried again, same thing. I left it open while I was searching for an answer and stumbled across this post...and when I looked back up at the app the drives had populated at some point. Closed the browse window and opened it again...back to just C: 
It took more than a few seconds for the remainder of the drives to populate in the browse window. I'm using a Windows 11 PC, all hardware raid SSD drives and 128G ram, big honkin GPU...wasn't for lack of power on my end.  

![Image](https://github.com/user-attachments/assets/bbb5ec25-27c1-492a-af73-ef0fe866dc0c)

![Image](https://github.com/user-attachments/assets/0e02740e-d997-444b-b80e-e072309c549c)

**Comment by mr2malv** [comment]
Now that I posted that and drill in to proceed...the same thing happened when I opened the folder with the .img file in it...took several seconds to populate the actual contents of the folder. Long enough that my brain kept telling me to 'click and fix' 'click and fix' before it finally popped up after I resisted the urge lol
