### ISSUE TITLE
[BUG]: Subitems randomisation is broken

### ISSUE THREAD

**Issue by tdewey-rpi** [raspberrypi/rpi-imager#842]
### What happened?

The _Home Assistants and Automation_ category should have item ordering randomisation applied - but it appears to present items in the same order on every invocation.

### Version

1.8.5 (Default)

### What host operating system were you using?

macOS

### Host OS Version

14.4

### Selected OS

N/A

### Which Raspberry Pi Device are you using?

Raspberry Pi 5

### What kind of storage device are you using?

Other

### OS Customisation

- [ ] Yes, I was using OS Customisation when the bug occurred.

**Comment by tdewey-rpi** [comment]
Tagging @cillian64, as it looks like our V4 server side processor is dropping the random key from subitems.

**Comment by cillian64** [comment]
Fixed by adding this to the schema in imager-manifester.
