### ISSUE TITLE
[BUG]: OS Customisation option is missing. 

### ISSUE THREAD

**Issue by salmanfarisvp** [raspberrypi/rpi-imager#843]
### What happened?

In the new version of v1.8.5, I see the OS customization option is missing in the MAC version (not sure about the other models). It was so handy to set up the network and SSH before powering the Pi. 

![image](https://github.com/raspberrypi/rpi-imager/assets/11945360/d2943f23-d059-47fb-84e5-ca513701111a)

### Version

1.8.5 (Default)

### What host operating system were you using?

macOS

### Host OS Version

14.2.1 (23C71)

### Selected OS

Raspberry Pi OS

### Which Raspberry Pi Device are you using?

Raspberry Pi 5

### What kind of storage device are you using?

microSD Card in a USB reader

### OS Customisation

- [ ] Yes, I was using OS Customisation when the bug occurred.

**Comment by lurch** [comment]
Note that in previous versions of RPi Imager, there was a "settings-icon" on the initial screen, but in recent versions of RPi Imager it has instead moved to only be triggered as part of the flashing process - see the screenshots / walkthrough at https://www.raspberrypi.com/documentation/computers/getting-started.html#raspberry-pi-imager
Is this also what you're seeing, or is there some other way in which the OS Customisation options are "missing" for you?

**Comment by salmanfarisvp** [comment]
Thanks for sharing the update update. But looks like it's not always triggering to open the settings-icon.

**Comment by lurch** [comment]
Perhaps I didn't explain it clearly enough - there now **isn't** a settings-icon. Again, see the walkthrough that I linked to, to see where / when the OS Customisation happens.

**Comment by jayjayseal** [comment]
ctrl+shift+x to trigger the window with settings.

**Comment by varunyellina** [comment]
Date: June 2, 2025
OS: macOS 15.5
Raspberry Pi Imager: v1.8.5

It did not prompt me to customize options. I used the keyboard shortcut after reading through the comments on this issue #843.

**Comment by salmanfarisvp** [comment]
Hi @varunyellina , I Just checked with Pi Image v1.8.5 and it's working fine. Please note, it will only prompt after you choose the **Pi Model**, **OS Version** and **Storage** or try with - **ctrl+shift+x** . 

**Tested on** 
OS: macOS 15.4.1
Raspberry Pi Imager: v1.8.5

![Image](https://github.com/user-attachments/assets/3476fd67-91cb-454b-aa6e-82fe1dad01b7)

![Image](https://github.com/user-attachments/assets/6716a5d4-0662-440d-9717-cb2920dfa24c)
