### ISSUE TITLE
[BUG]: Debian aarch64 system information

### ISSUE THREAD

**Issue by peltho** [raspberrypi/rpi-imager#848]
### What happened?

I'm currently **network** booting my diskless Raspberry Pi 4 (worker-2) from another one running under ArchLinuxARM `armv7l`:

server _(hostname: rpi4)_
```
> uname -a
> Linux rpi4 6.6.25-1-rpi #1 SMP Fri Apr  5 13:33:52 MDT 2024 armv7l GNU/Linux
```

I used RPI Imager in order to flash my diskless rpi bootloader to be able to boot on network thanks to [this tutorial](https://www.raspberrypi.com/documentation/computers/raspberry-pi.html#bootloader_update_stable).

The client is correctly booting and everything works fine thanks to some configuration with `dnsmasq` on the server, except one thing.
The client system information seems to be tied to Debian and differs from the supposed ArchlinuxARM configuration provided by the server:

client _(hostname: worker-2)_
```
> uname -a
> Linux worker-2 6.6.20+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.20-1+rpt1 (2024-03-07) aarch64 GNU/Linux
```

I suppose there's some configuration to do in rpi imager to provide an Archlinux armv7l system but I can't find it.

### Version

1.8.5 (Default)

### What host operating system were you using?

Other Linux environment

### Host OS Version

6.6.25-1-rpi

### Selected OS

ArchLinux ARM armv7l

### Which Raspberry Pi Device are you using?

Raspberry Pi 4B, 400, and Compute Modules 4, 4S

### What kind of storage device are you using?

USB SSD

### OS Customisation

- [ ] Yes, I was using OS Customisation when the bug occurred.

**Comment by tdewey-rpi** [comment]
As @lurch points out, it seems likely to followed the tutorial so closely that you copied our Raspberry Pi OS kernel to your tftpboot directory, per the tutorial here: https://www.raspberrypi.com/documentation/computers/remote-access.html#network-boot-your-raspberry-pi

You will want to adjust the contents of your tftpboot directory to match your expectations - eg, provide your ArchLinux kernel there.

I'm closing this as this isn't an issue with `rpi-imager`, but an issue with another tool. Again, as @lurch points out, you're best to ask in the Raspberry Pi Forums for additional support.

Good luck in your project!
