### ISSUE TITLE
[FEATURE]: Add disable-eject to CLI

### ISSUE THREAD

**Issue by veigaMak** [raspberrypi/rpi-imager#851]
### Is your feature request related to a problem? Please describe.

I'm using the CLI to write a .img to a SSD but I need to make further modifications after writing the image, namely create new partitions and increase partitions size. If I use the GUI version this option is available but I cannot make it work in the CLI version.

### Describe the solution you would like to see implemented

Add --disable-eject (or similar) to the CLI options.

### Describe alternatives you've considered

I've tried to use the GUI versions and it all works fine, but when I try to play with partitions after using the CLI version it does not work, I need to unplug and plug back in the disk.

### Additional context

.

### Version

1.8.5 (Default)

**Comment by tdewey-rpi** [comment]
Thanks for the suggestion, @veigaMak

A completely fair request - and one that I can see the merit of. For reference, I'd typically expect Raspberry Pi OS or others to perform an online resize of the rootfs partition to fill the storage device on the first boot - but I can see how that might not be something that's useful to you.

Feature request accepted.
