### ISSUE TITLE
[FEATURE]: Static IP address

### ISSUE THREAD

**Issue by Cubeman333** [raspberrypi/rpi-imager#855]
### Is your feature request related to a problem? Please describe.

it is annoying to set a static IP address on a Pi before first boot.

### Describe the solution you would like to see implemented

It would be nice if you could set a static IP address directly in the Imager.

### Describe alternatives you've considered

It would be way harder to implement a easy method of setting a static IP in the dhcp.conf, because you cant acess this partition on windows.

### Additional context

I dont know how difficult it is to do this with the different network interfaces, but it would be a nice addition to the Imager.

### Version

1.8.5 (Default)

**Comment by lurch** [comment]
Duplicate of #288 (and other similar requests)

**Comment by tdewey-rpi** [comment]
Closing as 'Won't Fix'.

The rationale has been documented in numerous locations now - if you're curious, a search should reveal it fairly promptly.

**Comment by zendainc** [comment]
> Closing as 'Won't Fix'.
> 
> The rationale has been documented in numerous locations now - if you're curious, a search should reveal it fairly promptly.

Wow. That is an incredibly unhelpful and condescending reply.

**Comment by NickNevzorov** [comment]
I really need this function. I often write images, and then I have to run each one to set a static address
