### ISSUE TITLE
[FEATURE]: Custom swap file size?

### ISSUE THREAD

**Issue by laleeroy** [raspberrypi/rpi-imager#896]
### Is your feature request related to a problem? Please describe.

I didn't notice this option, but it would be cool if we can customize the swap file while making an image

### Describe the solution you would like to see implemented

NA

### Describe alternatives you've considered

NA

### Additional context

NA

### Version

1.8.5 (Default)

**Comment by tdewey-rpi** [comment]
Feature request rejected.

Unfortunately, we cannot guarantee that any action to create a swap file will be honoured or used by the OS you write, so introducing this feature would lead to user confusion and frustration.
