### ISSUE TITLE
Allow installing Home Assistant

### ISSUE THREAD

**Issue by balloob** [raspberrypi/rpi-imager#9]
Opening an issue as per https://www.raspberrypi.org/blog/raspberry-pi-imager-imaging-utility/#comment-1523756

[Home Assistant](https://www.home-assistant.io/) is an open source home automation platform that focuses on local control and privacy. We provide our own operating system that turns your Raspberry Pi into a home automation hub, including easy updates via the UI. We recommend users that are starting out to get a Raspberry Pi 4. We support all variants of the Raspberry Pi. 

It would be great if Home Assistant would be available as an OS option in the Raspberry Pi Imager.

Our OS can be found here: https://github.com/home-assistant/operating-system/releases

**Comment by balloob** [comment]
@maxnet is there anything we can do to help move this forward?

**Comment by ghollingworth** [comment]
You'll need to provide a .json snippet for your images...

As per the top level .json

http://downloads.raspberrypi.org/os_list_imagingutility_v2.json

You can test your own changes using "rpi-imager --repo filename.json" on the command line

**Comment by agners** [comment]
@ghollingworth should we store that json snipet online somewhere? Are you going to update automatically if we maintain that using our release pipeline?

**Comment by balloob** [comment]
@agners looking at the entry for OctoPi, we just generate a JSON and add a reference in the main listing:

![image](https://user-images.githubusercontent.com/1444314/117513708-2a2c0980-af47-11eb-8c8a-132d4e7574ab.png)

https://unofficialpi.org/rpi-imager/rpi-imager-octopi.json

**Comment by agners** [comment]
Oh I see, somehow did not notice that this is referencing jsons. I guess Home Assistant would go under "Other specific purpose OS":

```
               {
                    "name": "Home Assistant",
                    "description": "Open-source home automation platform with a focus on local control and privacy.",
                    "icon": "https://version.home-assistant.io/rpi-imager-haos.png",
                    "subitems_url": "https://version.home-assistant.io/rpi-imager-haos.json"
               },
```

The icon/json should be up soon.

**Comment by agners** [comment]
It seems the image list made it in, Home Assistant is now available in the official repo! :tada: 

I think with that this can be closed.

**Comment by balloob** [comment]
🎉 

https://twitter.com/home_assistant/status/1396877204026363905

**Comment by b-reich** [comment]
> @ghollingworth should we store that json snipet online somewhere? Are you going to update automatically if we maintain that using our release pipeline?

Something with your release pipeline wont work. It's still on 6.2.

**Comment by agners** [comment]
It is a manual step currently. Updated to release 7.0.
