### ISSUE TITLE
[FEATURE]: Request to Create a Separate Version for PR #879

### ISSUE THREAD

**Issue by ykla** [raspberrypi/rpi-imager#915]
### Is your feature request related to a problem? Please describe.

Would it be possible to create a separate version specifically for the changes in https://github.com/raspberrypi/rpi-imager/pull/879? Your consideration is greatly appreciated. Thank you! I noticed that there hasn't been much activity recently, and it's been 8 months since the last release. Would it be possible to issue an interim release that includes my PR? Thank you for your consideration!

### Describe the solution you would like to see implemented

Create a Separate Version for https://github.com/raspberrypi/rpi-imager/pull/879.

### Describe alternatives you've considered

No.

### Additional context

No.

### Version

1.8.5 (Default)

**Comment by tdewey-rpi** [comment]
Thanks for the report, @ykla.

My attentions have indeed been elsewhere for the last few months (Connect, rpi-sb-provisioner, pi-gen, pi-gen-micro), however I am now returning to `rpi-imager` for a new release.

Your PR will be included in the upcoming 1.9.0.

**Comment by tdewey-rpi** [comment]
Included in v1.9.0. Let me know if it comes through OK!

**Comment by ykla** [comment]
Thank you very much for your efforts. I found a relatively obvious but non-critical error in my translation and made corrections to some minor mistakes. I believe this issue doesn't have a significant impact, so there's no need to rush the fix. It can be included in your next release.

**Comment by ykla** [comment]
Hi, I find that the <https://www.raspberrypi.com/software/> still releases 1.8.5. Please call them update it. Thanks.
