### ISSUE TITLE
Impossible to write OS on sd card - Ubuntu 20.04

### ISSUE THREAD

**Issue by londer1995** [raspberrypi/rpi-imager#93]
EDIT: problem not related to rpi-imager..

Hello, I got a couple of problems using rpi-imager that I never noticed before (maybe because it worked fine until now!).
First in first, I got this in the terminal:
![Schermata da 2020-07-26 12-13-19](https://user-images.githubusercontent.com/62596567/88476567-9817bf00-cf39-11ea-969e-52ec06e34ab8.jpg)
It seems ok, but when it check the card it shows:
![Schermata da 2020-07-26 12-15-35](https://user-images.githubusercontent.com/62596567/88476599-d90fd380-cf39-11ea-8319-279793997b46.jpg)
I can't be sure 100% (actually I'm not able to verify it!!) card is not broken, but it worked until 1 hour ago without problems.
Since I've tryied to change OS from raspberry OS to Ubuntu, I started having issues.
Is it related to rpi-imager? How can I verify the integrity of the SD card/rpi-imager? thx

**Comment by maxnet** [comment]
Can you read the whole card using other tools?
E.g.

```
sudo dd if=/dev/sdX of=/dev/null bs=512K
```

Where sdX is your SD card reader.

**Comment by londer1995** [comment]
![Schermata da 2020-07-26 15-11-48](https://user-images.githubusercontent.com/62596567/88479861-695a1280-cf52-11ea-85c0-3a91169378d4.png)

I went to buy another SD card (samsung evo plus 64gb) and got the same error.
Translated error message is:
dd: error while reading '/dev/sdb' : input/output Error.

**Comment by maxnet** [comment]
> ![Schermata da 2020-07-26 15-11-48](https://user-images.githubusercontent.com/62596567/88479861-695a1280-cf52-11ea-85c0-3a91169378d4.png)
> 
> I went to buy another SD card (samsung evo plus 64gb) and got the same error.
> Translated error message is:
> dd: error while reading '/dev/sdb' : input/output Error.

Well, if other tools like dd also give IO errors while reading from the card, than the problem is not in our software.

As far as another card having the same problem.
Problem does not necessarily have to be the SD card itself. Can also be something wrong with the reader, or the full-size SD card<->Micro SD adapter if you use any.

> EDIT: using sudo rpi-imager I get:
> `QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root' `

Warnings like that can be safely ignored.

**Comment by londer1995** [comment]
Well, I'm using the new adapter with the new SD card... I'm going to format and install again Ubuntu, last chance before throwing everything out the window!!

Btw thank you, I'll edit this answer in about 30 mins just for completeness
