### ISSUE TITLE
document how to integrate AppImage with the linux desktop

### ISSUE THREAD

**Issue by rgl** [raspberrypi/rpi-imager#930]
### What happened?

Since 1.9.0, we no longer have dist specific packages (e.g. for Debian/Ubuntu); instead, we have a AppImage binary, but using it, does not integrate it with the linux desktop (e.g. by creating a desktop entry).

Can the AppImage do that?

Or can it be documented?

### Version

1.9.0 (Default)

### What host operating system were you using?

Debian and derivatives (eg Ubuntu)

### Host OS Version

22.04

### Selected OS

N/A

### Which Raspberry Pi Device are you using?

Raspberry Pi 4B, 400, and Compute Modules 4, 4S

### What kind of storage device are you using?

microSD Card in an internal reader

### OS Customisation

- [ ] Yes, I was using OS Customisation when the bug occurred.

**Comment by tdewey-rpi** [comment]
Closing as answered.
