### ISSUE TITLE
[FEATURE]: Set static IP etc from Pi Imager

### ISSUE THREAD

**Issue by donsay** [raspberrypi/rpi-imager#967]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you would like to see implemented

Allow configuring of IP, subnet, gateway, & DNS server from within Imager.

### Describe alternatives you've considered

None.

### Additional context

None.

### Version

1.8.5

**Comment by donsay** [comment]
The changelog for 1.9.0 does not list this feature.

**Comment by tdewey-rpi** [comment]
Feature request rejected, per earlier rejections.

I have yet to see a compelling argument or design that mitigates the harms previously identified.
